### ISSUE TITLE
edmConfigBrowser fails to load python configuration file

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#12556]
Using recent IB CMSSW_8_0_X_2015-11-23-2300:

```
edmConfigBrowser  SimCalorimetry/HGCalSimProducers/test/testHGCalDigi_cfg.py
2015-11-24 18:06:38,470 INFO Start logging to /afs/cern.ch/user/y/yana/.vispa/log3.txt
2015-11-24 18:06:39,161 ERROR Application: openFile() - Error while opening 'SimCalorimetry/HGCalSimProducers/test/testHGCalDigi_cfg.py' : Traceback (most recent call last):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Main/Application.py", line 902, in openFile
    if self._knownExtensionsDictionary[ext].openFile(filename):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Plugins/Browser/BrowserPlugin.py", line 176, in openFile
    return tab.controller().open(filename)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigEditorTabController.py", line 339, in open
    if BrowserTabController.open(self, filename, update):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Main/TabController.py", line 207, in open
    if self.readFile(filename):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigEditorTabController.py", line 297, in readFile
    if self.dataAccessor().open(filename):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2015-11-23-2300/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigDataAccessor.py", line 165, in open
    self._file = imp.load_module(os.path.splitext(os.path.basename(self._filename))[0].replace(".", "_"), theFile, self._filename, ("py", "r", 1))
  File "SimCalorimetry/HGCalSimProducers/test/testHGCalDigi_cfg.py", line 4, in <module>
    process = cms.Process('SIMDIGI',eras.Run2_25ns)
TypeError: new___init__() takes exactly 2 arguments (3 given)
```

**Comment by ianna** [comment]
Problematic configuration file does not exist in CMSSW_9_2_x
