### ISSUE TITLE
Find thread-safety problem in JobReport

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13082]
The threaded IB shows a crash in JobReport once the mixing module became threaded:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_THREADED_X_2016-01-21-2300/pyRelValMatrixLogs/run/25208.0_SMS-T1tttt_mGl-1500_mLSP-100_13+SMS-T1tttt_mGl-1500_mLSP-100_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_SMS-T1tttt_mGl-1500_mLSP-100_13+SMS-T1tttt_mGl-1500_mLSP-100_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

The trackeback
```
Thread 3 (Thread 0x7f51337fe700 (LWP 24533)):
#0  0x000000387d2df113 in poll () from /lib64/libc.so.6
#1  0x00007f52284552c4 in full_read.constprop () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_THREADED_X_2016-01-21-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#2  0x00007f522845552c in edm::service::InitRootHandlers::stacktraceFromThread() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_THREADED_X_2016-01-21-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#3  0x00007f52284556ab in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_THREADED_X_2016-01-21-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f5231bb6e2d in __gnu_cxx::__exchange_and_add () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#6  0x00007f5231bb6ec2 in __gnu_cxx::__exchange_and_add_dispatch () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#7  0x00007f5231bbb310 in std::string::_Rep::_M_dispose(std::allocator<char> const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#8  0x00007f5231bb8a0a in std::string::assign(std::string const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#9  0x00007f523320e009 in edm::JobReport::inputFileOpened(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::vector<std::string, std::allocator<std::string> > const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/libFWCoreMessageLogger.so
#10 0x00007f5214ef42dd in edm::InputFile::inputFileOpened(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::vector<std::string, std::allocator<std::string> > const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#11 0x00007f5214f0df70 in edm::RootFile::reportOpened(std::string const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#12 0x00007f5214f24cc6 in edm::RootInputFileSequence::initTheFile(bool, bool, edm::InputSource*, char const*, edm::InputType) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#13 0x00007f5214f26369 in edm::RootInputFileSequence::skipToItemInNewFile(unsigned int, unsigned int, unsigned long long, unsigned long) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#14 0x00007f5214f266b6 in edm::RootInputFileSequence::skipToItem(unsigned int, unsigned int, unsigned long long, unsigned long, bool) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#15 0x00007f5214f083b1 in edm::RootEmbeddedFileSequence::readOneSpecified(edm::EventPrincipal&, unsigned long&, edm::SecondaryEventIDAndFileInfo const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_THREADED_X_2016-01-20-1100/lib/slc6_amd64_gcc493/pluginIOPoolInput.so
#16 0x00007f51e6c3a764 in edm::MixingModule::doPileUp(edm::Event&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_THREADED_X_2016-01-21-2300/lib/slc6_amd64_gcc493/pluginSimGeneralMixingModulePlugins.so
#17 0x00007f51e8ad341a in edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_THREADED_X_2016-01-21-2300/lib/slc6_amd64_gcc493/libMixingBase.so
```

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
#13083 is meant to fix this

**Comment by Dr15Jones** [comment]
+1
