### ISSUE TITLE
DetectorDescription/RegressionTest unit test failing

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#13286]
For 80X, DetectorDescriptionRegressionTestDOMCount unit test is failing with error
```
Traceback (most recent call last):
  File "/build/build/muz/CMSSW_8_0_X_2016-02-15-1100/src/DetectorDescription/RegressionTest/test/run_DOMCount.py", line 19, in <module>
    process.load(cfiFile)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_X_2016-02-15-1100/python/FWCore/ParameterSet/Config.py", line 511, in load
    module = __import__(moduleName)
ImportError: No module named cmsExtendedGeometryLiMaxXML_cfi
```

please provide a fix for this

**Comment by smuzaffar** [comment]
assign geometry

**Comment by ianna** [comment]
@smuzaffar - I think, this has been fixed a while ago. Should it be closed?

**Comment by ianna** [comment]
+1
