### ISSUE TITLE
Invalid use of AssociationMap lookup

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15369]
Trying to debug a reconstruction job which is throwing an exception is severly hampered by the following exception begin caught internally by the module TkConvValidator:

```
#0  __cxxabiv1::__cxa_throw (obj=0x7ffd79e62900, tinfo=0x7ffff79a9210 <typeinfo for edm::Exception>, dest=0x7ffff79525d0 <edm::Exception::~Exception()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:63
#1  0x00007ffff7952b7b in edm::Exception::throwThis(edm::errors::ErrorCodes, char const*, char const*, char const*, char const*, char const*) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-08-03-1100/lib/slc6_amd64_gcc530/libFWCoreUtilities.so
#2  0x00007fffb2ecb022 in edm::AssociationMap<edm::OneToManyWithQualityGeneric<edm::View<reco::Track>, std::vector<TrackingParticle, std::allocator<TrackingParticle> >, double, unsigned int, edm::RefToBaseProd<reco::Track>, edm::RefProd<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, edm::RefToBase<reco::Track>, edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > > >::operator[](edm::RefToBase<reco::Track> const&) const ()
   from /build/chrjones/temp/testAsyncPrefetch/CMSSW_8_1_X_2016-08-03-1100/lib/slc6_amd64_gcc530/pluginValidationRecoEgammaPlugins.so
#3  0x00007fffb2ec4cc1 in TkConvValidator::analyze(edm::Event const&, edm::EventSetup const&) () from /build/chrjones/temp/testAsyncPrefetch/CMSSW_8_1_X_2016-08-03-1100/lib/slc6_amd64_gcc530/pluginValidationRecoEgammaPlugins.so
#4  0x00007ffff7d639da in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) ()
   from /build/chrjones/temp/testAsyncPrefetch/CMSSW_8_1_X_2016-08-03-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
```

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by Dr15Jones** [comment]
I was running step 3 of workflow 250202.0

**Comment by Dr15Jones** [comment]
This looks like this was changed here:
https://github.com/cms-sw/cmssw/commit/e03797c768c1d484e8611f44ce33dc0f4e3fb851#diff-ffc4e69308058437f73ef09fc1b71c28
