### ISSUE TITLE
matplotlib does not work in CMSSW_8_1_DEVEL_X

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15660]
The python module matplotlib does not work in CMSSW_8_1_DEVEL_X_2016-08-27-1100 or later. The problem is

```
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-08-27-1100/src/FWCore/Concurrency/bin/edmStreamStallGrapher.py", line 247, in createPDFImage
    import matplotlib.pyplot as plt
  File "/cvmfs/cms-ib.cern.ch/2016-35/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-dpekbn/lib/python2.7/site-packages/matplotlib/__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/cvmfs/cms-ib.cern.ch/2016-35/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-dpekbn/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 34, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: No module named cycler
```

So it appears that the python module cycler is missing.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
It is also failing in CMSSW_8_1_X_2016-08-29-2300. All these tries have been on cmsdev02.cern.ch.

**Comment by Dr15Jones** [comment]
CMSSW_8_1_0_pre10 does work.

**Comment by smuzaffar** [comment]
@Dr15Jones , a few days ago, we updated matpltlib to 1.5.2 in 81X. 810pre10 is using an older version 1.2.1. 
@iahmad-khan , can you please check?

**Comment by davidlange6** [comment]
looks like matplotlib now depends on cycler,

For standard Python installations you will also need to install compatible versions of setuptools, numpy, python-dateutil, pytz,pyparsing, and cycler in addition to matplotlib.

(

**Comment by iahmad-khan** [comment]
yes matplotlib is looking for cycler , in build log grep:

```
cycler: yes [cycler was not found. pip will attempt to
cycler: yes [cycler was not found. pip will attempt to

```

**Comment by iahmad-khan** [comment]
after adding the external , it got fixed , in build log , grep showed:

```
cycler: yes [using cycler version 0.10.0]

```

thanks to shahzad for trobleshooting tip.

**Comment by smuzaffar** [comment]
@Dr15Jones , this was fix here https://github.com/cms-sw/cmsdist/pull/2474
Can you please check if it works as expected?

**Comment by Dr15Jones** [comment]
It now fails in a new way
```
[chrjones@cmsdev02 CMSSW_8_1_X_2016-09-01-1100]$ $CMSSW_RELEASE_BASE/src/FWCore/Concurrency/bin/edmStreamStallGrapher.py -g ../CMSSW_8_1_DEVEL_X_2016-08-28-0000/matrix/tracer_4_threads_4_streams.log 
>reading file
>processing data
>creating PDF
/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-01-1100/src/FWCore/Concurrency/bin/edmStreamStallGrapher.py", line 412, in <module>
    createPDFImage(processingSteps, numStreams, stalledModules)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-01-1100/src/FWCore/Concurrency/bin/edmStreamStallGrapher.py", line 247, in createPDFImage
    import matplotlib.pyplot as plt
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/cvmfs/cms-ib.cern.ch/2016-36/slc6_amd64_gcc530/external/py2-matplotlib/1.5.2-epaelh/lib/python2.7/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/external/python/2.7.11-giojec/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter
```
where I'm on cmsdev02
```
[chrjones@cmsdev02 CMSSW_8_1_X_2016-09-01-1100]$ pwd
/build/chrjones/temp/testAsyncPrefetch/CMSSW_8_1_X_2016-09-01-1100
```
A simple test would just be to do  ```import matplotlib.pyplot```

**Comment by smuzaffar** [comment]
looks like an other new dependency for matplotlib 1.5.x.
Look like we have explicitly removed this from our python  https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_8_1_X/gcc530/python.spec#L175

@davidlt, I see that originally it was removed from online releases but now it is dropped from every build. Do you recall any reason why it was removed.

**Comment by davidlt** [comment]
Well, that was in 2009. A couple of years before I started working on this :) See ce43e6ace2425c96767a6276abdeea404a0764a9

Looking at the history, it was removed as Lassi complained about it. Nothing is using Tcl/Tk in CMSSW. Technically you cannot build a Python without Tcl/Tk GUI package. But CMSSW actually has Tcl and Tk part of it bootstrap.

Right after `import matplotlib` one can select a different backend. See: http://matplotlib.org/faq/usage_faq.html#what-is-a-backend

**Comment by davidlange6** [comment]
Hi

Running into this issue as well..

It looks like the only backend cmssw supports now is Qt4Agg. So, could this be made the default?

Otherwise, do we really need Tcl/Tk or rather just TkInter which then could let Tcl/Tk come from the system as needed (obviously not a grid use case)?

**Comment by acarvalh** [comment]
Hi 
On top of the releases I also tried CMSSW_8_1_X_2016-10-22-1100
I still get the module missing

    import _tkinter # If this fails your Python may not be configured for Tk

Is there any hope of having it installed along with python in some release?

thanks much!

**Comment by smuzaffar** [comment]
@davidlt, we have dependency on tk/tck but not on their devel packages which I guess provide the libtk|tcl.so for these packages ....right?

**Comment by davidlt** [comment]
Correct, because bootstrap only contains run-time dependencies (i.e. does not incl. dev packages).

I thought, you fixed this in DEVEL IBs.

**Comment by davidlange6** [comment]
the workaround that ought to work for now is to use the "Qt4Agg" backend to avoid the issue

**Comment by davidlt** [comment]
That could work, but there is no long-term guarantees for Qt4Agg support. Qt4 is dead.

**Comment by davidlange6** [comment]
its the only backend currently working in cmssw:(
(as I mentioned a month ago) - let me try the devel IB

**Comment by davidlange6** [comment]
so same error in the devel IB.

**Comment by acarvalh** [comment]
Thank you David. 
I am sorry for the dumb question, but what does it means?

**Comment by smuzaffar** [comment]
We have enabled tk backend (TkAgg) in DEVEL IBs. I can run the following on lxplus (ssh -X lxplus) in CMSSW_8_1_DEVEL_X_2016-11-01-1100 release env.
```
#!/usr/bin/env python
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()
```
can you please test your usecase(s)  and confirm that if this works for you? We can then back-port it to normal 81X IBs/releases.

**Comment by acarvalh** [comment]
Thank you Malik
It works like a charm

**Comment by Dr15Jones** [comment]
Works for me as well.

**Comment by smuzaffar** [comment]
+core
