### ISSUE TITLE
exception during StreamSchedule::processOneEvent

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#17047]
While writing some test configurations, I ran into an other issue with subprocesses and unscheduled execution (this is not the same problem as #17046).

The scenario is similar as that described in #17046: a module in a subprocess tries to request a product from an unscheduled producer in the parent process.
However, adding an unrelated, unused producer in the parent process leads to a new error:
```
----- Begin Fatal Exception 15-Dec-2016 11:12:13 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Calling function StreamSchedule::processOneEvent
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 10) >= this->size() (which is 10)
----- End Fatal Exception -------------------------------------------------
cmsRun: /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre2-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre2-build/tmp/BUILDROOT/d3ea8a4e05f20cebcc5d21821fb03060/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_0_pre2/src/FWCore/Concurrency/src/WaitingTaskList.cc:57: void edm::WaitingTaskList::reset(): Assertion `m_head == nullptr' failed.
Aborted (core dumped)
```

The surprising thing is that whether or not the crash occurs depends on the *name* of the unused producer.

To reproduce, prepare an area with
```
cmsrel CMSSW_9_0_0_pre2
cd CMSSW_9_0_0_pre2/src/
cmsenv
git cms-init
git cms-merge-topic fwyzard:framework-examples
git cms-addpkg DataFormats/Examples FWCore/Examples
scram b -j8
```
and run the attached python files:
  - this one [bug17047_good.py](https://github.com/cms-sw/cmssw/files/654346/bug17047_good.txt) gives the familiar message from #17046 
  - this one [bug17047.py](https://github.com/cms-sw/cmssw/files/654345/bug17047.txt) gives the new crash

**Comment by fwyzard** [comment]
With CMSSW_9_0_DEVEL_X_2016-12-15-1100, [bug17047.py](https://github.com/cms-sw/cmssw/files/654345/bug17047.txt) does not crash, but hangs indefinitely.

Adding the Tracer service gives
```
...
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 15-Dec-2016 14:16:17.483 CET
++++ starting: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++ finished: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++ starting: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++++ starting: processing path 'subpath' : stream = 0
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'sampleAnalyzer' id = 6
++++++++++ starting: prefetching before processing event for module: stream = 0 label = 'sampleMerger' id = 1
```

**Comment by fwyzard** [comment]
strace gives
```
...
write(2, "++", 2++)                       = 2
write(2, "++", 2++)                       = 2
write(2, "++", 2++)                       = 2
write(2, "++", 2++)                       = 2
write(2, "++", 2++)                       = 2
write(2, " starting: prefetching before pr"..., 68 starting: prefetching before processing event for module: stream = ) = 68
write(2, "0", 10)                        = 1
write(2, " label = '", 10 label = ')              = 10
write(2, "sampleMerger", 12sampleMerger)            = 12
write(2, "' id = ", 7' id = )                  = 7
write(2, "1", 11)                        = 1
write(2, "\n", 1
)                       = 1
futex(0x7fa81a2db1a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
...
```

**Comment by fwyzard** [comment]
gdb does not add much
```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 15-Dec-2016 14:26:21.405 CET
++++ starting: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++ finished: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++ starting: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++++ starting: processing path 'subpath' : stream = 0
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'sampleAnalyzer' id = 6
++++++++++ starting: prefetching before processing event for module: stream = 0 label = 'sampleMerger' id = 1
^C
Thread 1 "cmsRun" received signal SIGINT, Interrupt.
0x00007ffff5251437 in sched_yield () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5251437 in sched_yield () from /lib64/libc.so.6
#1  0x00007ffff67c7a4f in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7ffff2993200, completion_ref_count=@0x7ffff2987d28: 2)
    at ../../src/tbb/custom_scheduler.h:299
#2  0x00007ffff67c95a0 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7ffff2993200, parent=..., child=<optimized out>)
    at ../../src/tbb/custom_scheduler.h:611
#3  0x00007ffff7aeaeea in tbb::task::spawn_and_wait_for_all (child=..., this=0x7ffff2987d40)
    at /cvmfs/cms-ib.cern.ch/2016-51/slc6_amd64_gcc620/external/tbb/2017_20161128oss/include/tbb/task.h:741
#4  edm::EventProcessor::readAndProcessEvent (this=0x7ffff208e200) at /data/user/fwyzard/CMSSW_9_0_DEVEL_X_2016-12-15-1100/src/FWCore/Framework/src/EventProcessor.cc:2007
...
```

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@fwyzard the 'hanging indefinitely' happens when the framework has failed to detect that a schedule is unrunnable (usually a circular dependency). Effectively, a data prefetch has been requested but the task that actually gets that data never runs. 

I definitely appreciate your excellent bug reports!

**Comment by Dr15Jones** [comment]
@fwyzard one thing I failed to say in my last commit. The 'hanging indefinitely' is a framework bug and these sorts of problems will be found before the job attempts to run.

**Comment by Dr15Jones** [comment]
I retested this in CMSSW_9_0_X_2016-12-29-1100 and both bug17047.py and bug17047_good.py run just fine.

**Comment by Dr15Jones** [comment]
+1
