### ISSUE TITLE
[segfault] xrootd handshake timed out, CMSSW segfault in XrdAdaptor::RequestManager::initialize

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#17180]
Happened twice:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_0_X_2017-01-15-2300/pyRelValMatrixLogs/run/4.6_MinimumBias2010A+MinimumBias2010A+RECOSKIMALCA+HARVESTDR1/step2_MinimumBias2010A+MinimumBias2010A+RECOSKIMALCA+HARVESTDR1.log

```
16-Jan-2017 01:04:02 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root
[2017-01-16 01:04:47.868149 +0100][Error  ][AsyncSock         ] [eoscms.cern.ch:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout
[2017-01-16 01:05:32.914155 +0100][Error  ][AsyncSock         ] [eoscms.cern.ch:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout
[2017-01-16 01:05:32.915157 +0100][Error  ][PostMaster        ] [eoscms.cern.ch:1094 #0] Unable to recover: [ERROR] Socket timeout.
[2017-01-16 01:05:32.915255 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: /eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root). Trying to recover.
[2017-01-16 01:05:32.915613 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: /eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/934/8EF645F4-4385-DF11-B48F-00E08179172F.root). Trying to recover.
[2017-01-16 01:05:32.915641 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: /eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/937/EEFDB418-4485-DF11-8ED9-001A64789DD4.root). Trying to recover.
[2017-01-16 01:05:32.915662 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2017-01-16 01:05:32.915714 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_open (file: /eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 16-Jan-2017 01:05:32 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root.
%MSG
[2017-01-16 01:05:32.917073 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Unable to send the message kXR_open (file: /eos/cms/store/user/cmsbuild/store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ): [FATAL] Socket timeout
16-Jan-2017 01:05:32 CET  Fallback request to file root://cms-xrd-global.cern.ch//store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root
%MSG-w XrdAdaptorInternal:  file_open 16-Jan-2017 01:08:29 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2010A/MinimumBias/RAW-RECO/v6/000/138/924/D87FB9A7-4485-DF11-88B8-0025B3E05DFE.root?tried=+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1098xrdcmsglobal02.cern.ch,cms-xrd-transit.cern.ch,eoscms.cern.ch,eoscms-srv-m2.cern.ch,xrootd.ba.infn.it.
%MSG
[2017-01-16 01:10:24.859835 +0100][Error  ][XRootDTransport   ] Message 0x6f202720, stream [1, 0] is a response that we're no longer interested in (timed out)


A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.

Thread 7 (Thread 0x7f6171788700 (LWP 3044)):
#0  0x0000003e8c8e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f617433142f in XrdSys::LinuxSemaphore::Wait (this=0x7f61795912b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f61748030b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f61748030a0) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f61743315b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f6172189700 (LWP 3043)):
#0  0x0000003e8c8e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f617433142f in XrdSys::LinuxSemaphore::Wait (this=0x7f61795912b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f61748030b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f61748030a0) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f61743315b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f6172b8a700 (LWP 3042)):
#0  0x0000003e8c8e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f617433142f in XrdSys::LinuxSemaphore::Wait (this=0x7f61795912b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f61748030b8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f61748030a0) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f61743315b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f617358b700 (LWP 3041)):
#0  0x0000003e8cc0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f61741bc323 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f61742d4e72 in XrdCl::TaskManager::RunTasks (this=0x7f6175861880) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f61742d5009 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:37
#4  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f6173f8c700 (LWP 3040)):
#0  0x0000003e8c8e90a3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f61741c0a87 in XrdSys::IOEvents::PollE::Begin (this=0x7f6174803180, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f61741bd095 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffc0540b630) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f61741bbb48 in XrdSysThread_Xeq (myargs=0x7f61748e2ea0) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysPthread.cc:86
#4  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f617acff700 (LWP 2994)):
#0  0x0000003e8cc0f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f618d93fd97 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f618d940722 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f61926c4a50 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#4  0x0000003e8cc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003e8c8e8aad in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f619235ebc0 (LWP 2347)):
#0  0x0000003e8c8df283 in poll () from /lib64/libc.so.6
#1  0x00007f618d940584 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f618d9407ea in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f618d941da2 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000003e8c8e5307 in syscall () from /lib64/libc.so.6
#6  0x00007f617425b97a in XrdAdaptor::RequestManager::initialize(std::weak_ptr<XrdAdaptor::RequestManager>) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#7  0x00007f6174238142 in XrdFile::open(char const*, int, int) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#8  0x00007f6174239cdb in XrdFile::XrdFile(std::string const&, int, int) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#9  0x00007f6175a06f24 in XrdStorageMaker::open(std::string const&, std::string const&, int, StorageMaker::AuxSettings const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginUtilitiesXrdAdaptorPlugin.so
#10 0x00007f61904d6615 in StorageFactory::open(std::string const&, int) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libUtilitiesStorageFactory.so
#11 0x00007f619042bf06 in TStorageFactoryFile::Initialize(char const*, char const*) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libIOPoolTFileAdaptor.so
#12 0x00007f619042c874 in TStorageFactoryFile::TStorageFactoryFile(char const*, char const*, char const*, int, int, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libIOPoolTFileAdaptor.so
#13 0x00007f618df000a9 in __cf_1 ()
#14 0x00007f6183ec3fb7 in TClingCallFunc::exec(void*, void*) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-15-2300/external/slc6_amd64_gcc530/lib/libCling.so
#15 0x00007f6183ec4b6b in TClingCallFunc::exec_with_valref_return(void*, cling::Value*) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-15-2300/external/slc6_amd64_gcc530/lib/libCling.so
#16 0x00007f6183ece7e9 in long long TClingCallFunc::ExecT<long long>(void*) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-15-2300/external/slc6_amd64_gcc530/lib/libCling.so
#17 0x00007f61935e52a1 in TMethodCall::Execute(void*, long&) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-15-2300/external/slc6_amd64_gcc530/lib/libCore.so
#18 0x00007f619380a940 in TFile::Open(char const*, char const*, char const*, int, int) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-15-2300/external/slc6_amd64_gcc530/lib/libRIO.so
#19 0x00007f61743ac8c3 in edm::InputFile::InputFile(char const*, char const*, edm::InputType) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginIOPoolInput.so
#20 0x00007f6174394953 in edm::RootInputFileSequence::initTheFile(bool, bool, edm::InputSource*, char const*, edm::InputType) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginIOPoolInput.so
#21 0x00007f61743d8e99 in edm::RootPrimaryFileSequence::RootPrimaryFileSequence(edm::ParameterSet const&, edm::PoolSource&, edm::InputFileCatalog const&) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginIOPoolInput.so
#22 0x00007f6174399443 in edm::PoolSource::PoolSource(edm::ParameterSet const&, edm::InputSourceDescription const&) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginIOPoolInput.so
#23 0x00007f617439fc95 in edmplugin::PluginFactory<edm::InputSource* (edm::ParameterSet const&, edm::InputSourceDescription const&)>::PMaker<edm::PoolSource>::create(edm::ParameterSet const&, edm::InputSourceDescription const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/pluginIOPoolInput.so
#24 0x00007f61941b5a92 in edm::InputSourceFactory::makeInputSource(edm::ParameterSet const&, edm::InputSourceDescription const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#25 0x00007f619417c940 in edm::makeInput(edm::ParameterSet&, edm::CommonParams const&, std::shared_ptr<edm::ProductRegistry>, std::shared_ptr<edm::BranchIDListHelper>, std::shared_ptr<edm::ThinnedAssociationsHelper>, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration const>, edm::PreallocationConfiguration const&) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#26 0x00007f619418387f in edm::EventProcessor::init(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#27 0x00007f61941859b6 in edm::EventProcessor::EventProcessor(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /cvmfs/cms-ib.cern.ch/nweek-02455/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-15-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#28 0x000000000040c787 in main::{lambda()#1}::operator()() const ()
#29 0x000000000040acc4 in main ()
```

**Comment by Dr15Jones** [comment]
This is the same as #14952
