### ISSUE TITLE
Possible infinite loop in TrackingTruthAccumulator::accumulateEvent

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#17306]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_0_X_2017-01-26-2300/pyRelValMatrixLogs/run/202.0_TTbar+TTbarINPUT+DIGIPU1+RECOPU1+HARVEST/step2_TTbar+TTbarINPUT+DIGIPU1+RECOPU1+HARVEST.log

Killed by external termination request, which usually means a timeout after 2 hours (should add a timestamp to the stack trace so we can tell for sure!).  On thread still processing in the MixingModule, everything else completed, remaining thread looks to be computable, not blocked.

```
A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.

Thread 10 (Thread 0x7f4ad92bf700 (LWP 14227)):
#0  0x0000003f480acbdd in nanosleep () from /lib64/libc.so.6
#1  0x0000003f480aca50 in sleep () from /lib64/libc.so.6
#2  0x00007f4b1647fb9e in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000003f480e5309 in syscall () from /lib64/libc.so.6
#5  0x00007f4b19122ad2 in tbb::internal::futex_wait (comparand=2, futex=0x7f4b1804f9ac) at ../../include/tbb/machine/linux_common.h:60
#6  tbb::internal::binary_semaphore::P (this=0x7f4b1804f9ac) at ../../src/tbb/semaphore.h:206
#7  rml::internal::thread_monitor::commit_wait (c=<synthetic pointer>..., this=0x7f4b1804f9a0) at ../../src/rml/include/../server/thread_monitor.h:259
#8  tbb::internal::rml::private_worker::run (this=0x7f4b1804f980) at ../../src/tbb/private_server.cpp:278
#9  0x00007f4b19122af9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#10 0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#11 0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 9 (Thread 0x7f4ad9d3e700 (LWP 14226)):
#0  0x0000003f480acbdd in nanosleep () from /lib64/libc.so.6
#1  0x0000003f480aca50 in sleep () from /lib64/libc.so.6
#2  0x00007f4b1647fb9e in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000003f480e5309 in syscall () from /lib64/libc.so.6
#5  0x00007f4b19122ad2 in tbb::internal::futex_wait (comparand=2, futex=0x7f4b1804faac) at ../../include/tbb/machine/linux_common.h:60
#6  tbb::internal::binary_semaphore::P (this=0x7f4b1804faac) at ../../src/tbb/semaphore.h:206
#7  rml::internal::thread_monitor::commit_wait (c=<synthetic pointer>..., this=0x7f4b1804faa0) at ../../src/rml/include/../server/thread_monitor.h:259
#8  tbb::internal::rml::private_worker::run (this=0x7f4b1804fa80) at ../../src/tbb/private_server.cpp:278
#9  0x00007f4b19122af9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#10 0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#11 0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 8 (Thread 0x7f4ada73f700 (LWP 14225)):
#0  0x0000003f480acbdd in nanosleep () from /lib64/libc.so.6
#1  0x0000003f480aca50 in sleep () from /lib64/libc.so.6
#2  0x00007f4b1647fb9e in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00007f4aea9a507c in std::vector<SimTrack, std::allocator<SimTrack> >::vector(std::vector<SimTrack, std::allocator<SimTrack> > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libSimDataFormatsTrackingAnalysis.so
#5  0x00007f4aea9a60e8 in TrackingParticle::TrackingParticle(TrackingParticle const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libSimDataFormatsTrackingAnalysis.so
#6  0x00007f4aea9a61a7 in TrackingParticle* std::__uninitialized_copy<false>::__uninit_copy<TrackingParticle*, TrackingParticle*>(TrackingParticle*, TrackingParticle*, TrackingParticle*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libSimDataFormatsTrackingAnalysis.so
#7  0x00007f4aea9a6244 in void std::vector<TrackingParticle, std::allocator<TrackingParticle> >::_M_emplace_back_aux<TrackingParticle const&>(TrackingParticle const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libSimDataFormatsTrackingAnalysis.so
#8  0x00007f4ae86a3b6a in (anonymous namespace)::addTrackAndParentVertex((anonymous namespace)::DecayChainTrack*, TrackingParticle const&, (anonymous namespace)::OutputCollectionWrapper*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralTrackingAnalysisPlugins.so
#9  0x00007f4ae86a4218 in (anonymous namespace)::addTrack((anonymous namespace)::DecayChainTrack*, TrackingParticleSelector const*, (anonymous namespace)::OutputCollectionWrapper*, (anonymous namespace)::OutputCollectionWrapper*, (anonymous namespace)::TrackingParticleFactory const&, bool, TrackerTopology const*) [clone .constprop.571] () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralTrackingAnalysisPlugins.so
#10 0x00007f4ae86a431b in (anonymous namespace)::addTrack((anonymous namespace)::DecayChainTrack*, TrackingParticleSelector const*, (anonymous namespace)::OutputCollectionWrapper*, (anonymous namespace)::OutputCollectionWrapper*, (anonymous namespace)::TrackingParticleFactory const&, bool, TrackerTopology const*) [clone .constprop.571] () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralTrackingAnalysisPlugins.so
#11 0x00007f4ae86ab775 in void TrackingTruthAccumulator::accumulateEvent<PileUpEventPrincipal>(PileUpEventPrincipal const&, edm::EventSetup const&, edm::Handle<edm::HepMCProduct> const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralTrackingAnalysisPlugins.so
#12 0x00007f4ae86a4798 in TrackingTruthAccumulator::accumulate(PileUpEventPrincipal const&, edm::EventSetup const&, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralTrackingAnalysisPlugins.so
#13 0x00007f4aea7120ee in edm::MixingModule::accumulateEvent(PileUpEventPrincipal const&, edm::EventSetup const&, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so
#14 0x00007f4aea712256 in edm::MixingModule::pileAllWorkers(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so
#15 0x00007f4aea71dd93 in void edm::PileUp::readPileUp<std::_Bind<std::_Mem_fn<void (edm::MixingModule::*)(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&)> (std::reference_wrapper<edm::MixingModule>, std::_Placeholder<1>, edm::ModuleCallingContext const*, int, std::_Placeholder<2>, int, std::reference_wrapper<edm::EventSetup const>, edm::StreamID)> >(edm::EventID const&, std::vector<edm::SecondaryEventIDAndFileInfo, std::allocator<edm::SecondaryEventIDAndFileInfo> >&, std::_Bind<std::_Mem_fn<void (edm::MixingModule::*)(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&)> (std::reference_wrapper<edm::MixingModule>, std::_Placeholder<1>, edm::ModuleCallingContext const*, int, std::_Placeholder<2>, int, std::reference_wrapper<edm::EventSetup const>, edm::StreamID)>, int, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so
#16 0x00007f4aea7187a1 in edm::MixingModule::doPileUp(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so
#17 0x00007f4aea64521a in edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libMixingBase.so
#18 0x00007f4b1a50ffd3 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#19 0x00007f4b1a4e8132 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#20 0x00007f4b1a3f6c1c in decltype ({parm#1}()) edm::convertException::wrap<void edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#21 0x00007f4b1a3f6e0c in void edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#22 0x00007f4b1a3f7169 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#23 0x00007f4b1912e88b in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f4b17f7fe00, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:501
#24 0x00007f4b19127a72 in tbb::internal::arena::process (this=0x7f4b1803b780, s=...) at ../../src/tbb/arena.cpp:159
#25 0x00007f4b19126514 in tbb::internal::market::process (this=0x7f4b18057e00, j=...) at ../../src/tbb/market.cpp:677
#26 0x00007f4b191228a6 in tbb::internal::rml::private_worker::run (this=0x7f4b1804fa00) at ../../src/tbb/private_server.cpp:271
#27 0x00007f4b19122af9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#28 0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#29 0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x7f4af555c700 (LWP 14144)):
#0  0x0000003f480e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f4af810542f in XrdSys::LinuxSemaphore::Wait (this=0x7f4af833e3a8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f4af890e598) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f4af890e580) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f4af81055b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f4af5f5d700 (LWP 14143)):
#0  0x0000003f480e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f4af810542f in XrdSys::LinuxSemaphore::Wait (this=0x7f4af833e3a8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f4af890e598) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f4af890e580) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f4af81055b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f4af695e700 (LWP 14142)):
#0  0x0000003f480e5309 in syscall () from /lib64/libc.so.6
#1  0x00007f4af810542f in XrdSys::LinuxSemaphore::Wait (this=0x7f4af833e3a8) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f4af890e598) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f4af890e580) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f4af81055b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f4af735f700 (LWP 14141)):
#0  0x0000003f4840f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f4af7f90323 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f4af80a8e72 in XrdCl::TaskManager::RunTasks (this=0x7f4af8828d40) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f4af80a9009 in RunRunnerThread (arg=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:37
#4  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f4af7d60700 (LWP 14140)):
#0  0x0000003f480e90a3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f4af7f94a87 in XrdSys::IOEvents::PollE::Begin (this=0x7f4af890e900, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f4af7f91095 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffe3c0b2620) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f4af7f8fb48 in XrdSysThread_Xeq (myargs=0x7f4af81a0460) at /build/cmsbuild/auto-builds/CMSSW_9_0_0_pre1-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre1-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysPthread.cc:86
#4  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f4b002ff700 (LWP 14137)):
#0  0x0000003f4840f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f4b1647fd97 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f4b16480722 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f4b1895ea50 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#4  0x0000003f48407aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003f480e8aad in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f4b185f4c00 (LWP 14123)):
#0  0x0000003f480df283 in poll () from /lib64/libc.so.6
#1  0x00007f4b16480584 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f4b164807ea in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f4b16481da2 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000003f480cf437 in sched_yield () from /lib64/libc.so.6
#6  0x00007f4b1912cb79 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7f4b18056400, completion_ref_count=@0x7f4b1804b628: 2) at ../../src/tbb/custom_scheduler.h:299
#7  0x00007f4b1912e833 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f4b18056400, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:611
#8  0x00007f4b1a4ab755 in edm::EventProcessor::readAndProcessEvent() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#9  0x00007f4b1a41752a in statemachine::HandleEvent::readAndProcessEvent() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#10 0x00007f4b1a418ab8 in statemachine::HandleEvent::HandleEvent(boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::my_context) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#11 0x00007f4b1a42083e in boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::shallow_construct(boost::intrusive_ptr<statemachine::HandleLumis> const&, boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#12 0x00007f4b1a420a0a in boost::statechart::simple_state<statemachine::FirstLumi, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#13 0x00007f4b1a4b0726 in boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#14 0x00007f4b1a4a482d in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-01-26-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#15 0x000000000040c85e in main::{lambda()#1}::operator()() const ()
#16 0x000000000040acc4 in main ()

Current Modules:

Module: none (crashed)
Module: MixingModule
Module: none
Module: none

A fatal system signal has occurred: external termination request
```

**Comment by smuzaffar** [comment]
looms like this has been fixed.
