### ISSUE TITLE
root/xrootd connection recovery thread safety?

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#19082]
Another possible threading bug at the intersection of xrootd error handling and ROOT thread safety, only seen once so far.  Possibly related to #17971 and #18107

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_9_2_X_2017-05-30-2300/pyRelValMatrixLogs/run/4.17_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT/step5_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT.log

```
[2017-05-31 04:02:17.893271 +0200][Error  ][AsyncSock         ] [transfer-4.ultralight.org:1094 #0.0] Socket error encountered: [ERROR] Socket error: Resource temporarily unavailable
[2017-05-31 04:02:17.893580 +0200][Error  ][XRootD            ] [transfer-4.ultralight.org:1094] Unable to get the response to request kXR_read (handle: 0x00000000, offset: 11124330, size: 115115)
[2017-05-31 04:02:17.893609 +0200][Error  ][File              ] [0x18152e80@root://cms-xrd-global.cern.ch:1094//store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/0699429A-B37F-E011-A57A-0019B9F72D71.root?tried=transfer-5.ultralight.org] Fatal file state error. Message kXR_read (handle: 0x00000000, offset: 11124330, size: 115115) returned with [ERROR] Socket error: Resource temporarily unavailable
%MSG-w XrdAdaptorInternal:  (NoModuleName) 31-May-2017 04:02:17 CEST pre-events
XrdRequestManager::handle(name='root://cms-xrd-global.cern.ch//store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/0699429A-B37F-E011-A57A-0019B9F72D71.root) failure when reading from transfer-4.ultralight.org:1094 (site T2_US_Caltech); failed with error '[ERROR] Socket error: Resource temporarily unavailable' (errno=11, code=102).
%MSG
%MSG-w XrdAdaptorInternal:  (NoModuleName) 31-May-2017 04:02:17 CEST pre-events
Request failure when reading from transfer-4.ultralight.org:1094 (site T2_US_Caltech)
%MSG
%MSG-w XrdAdaptor:  (NoModuleName) 31-May-2017 04:02:17 CEST pre-events
Data is now served from  instead of previous T2_US_Caltech
%MSG
%MSG-w XrdAdaptorInternal:  (NoModuleName) 31-May-2017 04:05:27 CEST pre-events
Caught a CMSSW exception when running connection recovery.
%MSG
[2017-05-31 04:05:27.896003 +0200][Error  ][XRootD            ] [cms-xrd-global.cern.ch:1094] Impossible to send message kXR_open (file: /store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/0699429A-B37F-E011-A57A-0019B9F72D71.root?tried=transfer-4.ultralight.org,transfer-5.ultralight.org, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
[2017-05-31 04:05:27.896028 +0200][Error  ][XRootD            ] [cms-xrd-global.cern.ch:1094] Unable to get the response to request kXR_open (file: /store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/0699429A-B37F-E011-A57A-0019B9F72D71.root?tried=transfer-4.ultralight.org,transfer-5.ultralight.org, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat )


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thread 10 (Thread 0x7f0a079ff700 (LWP 14643)):
#0  0x00007f0a4d4e9efd in nanosleep () from /lib64/libc.so.6
#1  0x00007f0a4d4e9d94 in sleep () from /lib64/libc.so.6
#2  0x00007f0a477354d3 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00007f0a4d507b77 in sched_yield () from /lib64/libc.so.6
#5  0x00007f0a4eb3faaf in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7f0a2b137e00, completion_ref_count=@0x7f0a2b13bf28: 2) at ../../src/tbb/custom_scheduler.h:299
#6  0x00007f0a4eb3a9b1 in tbb::internal::arena::process (this=0x7f0a4b683780, s=...) at ../../src/tbb/arena.cpp:154
#7  0x00007f0a4eb394cb in tbb::internal::market::process (this=0x7f0a4b697900, j=...) at ../../src/tbb/market.cpp:677
#8  0x00007f0a4eb357c6 in tbb::internal::rml::private_worker::run (this=0x7f0a4b4b5080) at ../../src/tbb/private_server.cpp:271
#9  0x00007f0a4eb359f9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#10 0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 9 (Thread 0x7f0a0847e700 (LWP 14642)):
#0  0x00007f0a4d51869d in poll () from /lib64/libc.so.6
#1  0x00007f0a47735bf4 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f0a477363ca in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f0a47737955 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f0a4fa5350a in TBranch::GetEntry(long long, int) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc630/cms/cmssw-patch/CMSSW_9_2_X_2017-05-30-2300/external/slc7_amd64_gcc630/lib/libTree.so
#6  0x00007f0a4fa6ac71 in TBranchElement::GetEntry(long long, int) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc630/cms/cmssw-patch/CMSSW_9_2_X_2017-05-30-2300/external/slc7_amd64_gcc630/lib/libTree.so
#7  0x00007f0a2fb010d5 in edm::RootTree::getEntry(TBranch*, long long) const () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginIOPoolInput.so
#8  0x00007f0a2fb23da6 in edm::FullProvenanceReader::readProvenance(unsigned int) const () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginIOPoolInput.so
#9  0x00007f0a2fb22ae0 in edm::SerialTaskQueue::QueuedTask<void edm::SerialTaskQueueChain::push<void edm::(anonymous namespace)::readProvenanceAsyncImpl<edm::FullProvenanceReader>(edm::FullProvenanceReader const*, edm::SerialTaskQueueChain&, edm::WaitingTask*, unsigned int, std::atomic<std::set<edm::ProductProvenance, std::less<edm::ProductProvenance>, std::allocator<edm::ProductProvenance> > const*>&, edm::ModuleCallingContext const*, edm::signalslot::Signal<void (edm::StreamContext const&, edm::ModuleCallingContext const&)> const*, edm::signalslot::Signal<void (edm::StreamContext const&, edm::ModuleCallingContext const&)> const*)::{lambda()#1}>(void edm::(anonymous namespace)::readProvenanceAsyncImpl<edm::FullProvenanceReader>(edm::FullProvenanceReader const*, edm::SerialTaskQueueChain&, edm::WaitingTask*, unsigned int, std::atomic<std::set<edm::ProductProvenance, std::less<edm::ProductProvenance>, std::allocator<edm::ProductProvenance> > const*>&, edm::ModuleCallingContext const*, edm::signalslot::Signal<void (edm::StreamContext const&, edm::ModuleCallingContext const&)> const*, edm::signalslot::Signal<void (edm::StreamContext const&, edm::ModuleCallingContext const&)> const*)::{lambda()#1} const&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginIOPoolInput.so
#10 0x00007f0a4eb41983 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f0a2afb7e00, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:501
#11 0x00007f0a4eb3a9d2 in tbb::internal::arena::process (this=0x7f0a4b683780, s=...) at ../../src/tbb/arena.cpp:159
#12 0x00007f0a4eb394cb in tbb::internal::market::process (this=0x7f0a4b697900, j=...) at ../../src/tbb/market.cpp:677
#13 0x00007f0a4eb357c6 in tbb::internal::rml::private_worker::run (this=0x7f0a4b4b5180) at ../../src/tbb/private_server.cpp:271
#14 0x00007f0a4eb359f9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#15 0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 8 (Thread 0x7f0a08e7f700 (LWP 14641)):
#0  0x00007f0a4d4e9efd in nanosleep () from /lib64/libc.so.6
#1  0x00007f0a4d4e9d94 in sleep () from /lib64/libc.so.6
#2  0x00007f0a477354d3 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00007f0a4d507b77 in sched_yield () from /lib64/libc.so.6
#5  0x00007f0a4eb3faaf in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7f0a2afa7e00, completion_ref_count=@0x7f0a2afabf28: 2) at ../../src/tbb/custom_scheduler.h:299
#6  0x00007f0a4eb3a9b1 in tbb::internal::arena::process (this=0x7f0a4b683780, s=...) at ../../src/tbb/arena.cpp:154
#7  0x00007f0a4eb394cb in tbb::internal::market::process (this=0x7f0a4b697900, j=...) at ../../src/tbb/market.cpp:677
#8  0x00007f0a4eb357c6 in tbb::internal::rml::private_worker::run (this=0x7f0a4b4b5100) at ../../src/tbb/private_server.cpp:271
#9  0x00007f0a4eb359f9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:224
#10 0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x7f0a1a201700 (LWP 12957)):
#0  0x00007f0a4d51d469 in syscall () from /lib64/libc.so.6
#1  0x00007f0a1cc4b89f in XrdSys::LinuxSemaphore::Wait (this=0x7f0a3607bca8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f0a2c3bb2f8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f0a2c3bb2e0) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f0a1cc4ba59 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f0a1ac02700 (LWP 12956)):
#0  0x00007f0a4d51d469 in syscall () from /lib64/libc.so.6
#1  0x00007f0a1cc4b89f in XrdSys::LinuxSemaphore::Wait (this=0x7f0a3607bca8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f0a2c3bb2f8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f0a2c3bb2e0) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f0a1cc4ba59 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f0a1b603700 (LWP 12955)):
#0  0x00007f0a4d51d469 in syscall () from /lib64/libc.so.6
#1  0x00007f0a1cc4b89f in XrdSys::LinuxSemaphore::Wait (this=0x7f0a3607bca8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f0a2c3bb2f8) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f0a2c3bb2e0) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f0a1cc4ba59 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f0a1c004700 (LWP 12954)):
#0  0x00007f0a4d7fc96d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f0a1cad6773 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f0a1cbf0627 in XrdCl::TaskManager::RunTasks (this=0x7f0a25c22b00) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f0a1cbf0779 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdCl/XrdClTaskManager.cc:37
#4  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f0a1ca05700 (LWP 12953)):
#0  0x00007f0a4d5232c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f0a1cadb824 in XrdSys::IOEvents::PollE::Begin (this=0x7f0a2db2ab60, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f0a1cad7e95 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffc6ad19220) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f0a1cad5f98 in XrdSysThread_Xeq (myargs=0x7f0a2befeda0) at /build/cmsbld/auto-builds/CMSSW_9_1_0_pre3-slc7_amd64_gcc630/build/CMSSW_9_1_0_pre3-build/BUILD/slc7_amd64_gcc630/external/xrootd/4.6.1.RC2/xrootd-4.6.1.RC2/src/XrdSys/XrdSysPthread.cc:86
#4  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f0a3af3f700 (LWP 12483)):
#0  0x00007f0a4d7fcca9 in waitpid () from /lib64/libpthread.so.0
#1  0x00007f0a477356c7 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f0a47735da5 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f0a4dddec3f in std::execute_native_thread_routine (__p=0x7f0a3b03fc30) at ../../../../../libstdc++-v3/src/c++11/thread.cc:83
#4  0x00007f0a4d7f5dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f0a4d522ced in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f0a4bc02c80 (LWP 12404)):
#0  0x00007f0a4d4e9efd in nanosleep () from /lib64/libc.so.6
#1  0x00007f0a4d4e9d94 in sleep () from /lib64/libc.so.6
#2  0x00007f0a477354d3 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00007f0a4d507b77 in sched_yield () from /lib64/libc.so.6
#5  0x00007f0a4eb3faaf in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7f0a4b692600, completion_ref_count=@0x7f0a4b687328: 5) at ../../src/tbb/custom_scheduler.h:299
#6  0x00007f0a4eb41600 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f0a4b692600, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:611
#7  0x00007f0a4ff5c95a in edm::EventProcessor::readAndProcessEvent() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#8  0x00007f0a4fe9bdbf in statemachine::HandleEvent::readAndProcessEvent() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#9  0x00007f0a4fe9d7d7 in statemachine::HandleEvent::HandleEvent(boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::my_context) () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#10 0x00007f0a4fea5f9e in boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::shallow_construct(boost::intrusive_ptr<statemachine::HandleLumis> const&, boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>&) () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#11 0x00007f0a4fea615a in boost::statechart::simple_state<statemachine::FirstLumi, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#12 0x00007f0a4ff62054 in boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&) () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#13 0x00007f0a4ff557cd in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/nweek-02474/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_2_X_2017-05-28-0000/lib/slc7_amd64_gcc630/libFWCoreFramework.so
#14 0x000000000040e6d4 in main::{lambda()#1}::operator()() const ()
#15 0x000000000040d0a5 in main ()

Current Modules:

Module: none (crashed)
Module: none
Module: none
Module: none

A fatal system signal has occurred: segmentation violation
```

**Comment by smuzaffar** [comment]
looks like this has been fixed
