### ISSUE TITLE
Passed exception causes segfault in FWCore

### ISSUE THREAD

**Issue by nsmith-** [cms-sw/cmssw#19960]
In debugging #19812, I discovered a bug introduced between 930_pre1 and 930_pre2 relating to the EventSetupProvider.

The cfg:
```
import FWCore.ParameterSet.Config as cms

from Configuration.StandardSequences.Eras import eras
process = cms.Process("TEST",eras.Run2_2017)

process.source = cms.Source('EmptySource',
    firstRun = cms.untracked.uint32(1)
)
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(1) )

process.load('L1Trigger.L1TGlobal.GlobalParameters_cff')
process.SecondGlobalParams = process.GlobalParameters.clone()
```

produces the expected behavior in pre1, namely an exception:
```
[ncsmith@uwlogin src (from-CMSSW_9_3_0_pre1)]$ cmsRun test_doubleESProducer.py
----- Begin Fatal Exception 28-Jul-2017 17:38:53 CEST-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
two EventSetup Producers want to deliver type="L1TGlobalParameters" label=""
 from record L1TGlobalParametersRcd. The two providers are
1) type="StableParametersTrivialProducer" label="GlobalParameters"
2) type="StableParametersTrivialProducer" label="SecondGlobalParams"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
...
```

but in pre2, a segfault:
```
[ncsmith@uwlogin src (from-CMSSW_9_3_0_pre2)]$ cmsRun test_doubleESProducer.py


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thread 2 (Thread 0x7fd92053f700 (LWP 11500)):
#0  0x000000365600f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007fd92d3ab167 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007fd92d3ab705 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007fd92e8aec2f in std::execute_native_thread_routine (__p=0x7fd921679070) at ../../../../../libstdc++-v3/src/c++11/thread.cc:83
#4  0x0000003656007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003655ce8bcd in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7fd92e563c20 (LWP 11480)):
#0  0x0000003655cdf383 in poll () from /lib64/libc.so.6
#1  0x00007fd92d3ab554 in full_read.constprop () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007fd92d3abd2a in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007fd92d3acd85 in sig_dostack_then_abort () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007fd9301dac7f in edm::eventsetup::EventSetupProvider::finishConfiguration() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#6  0x00007fd9301f3bb4 in edm::eventsetup::EventSetupsController::eventSetupForInstance(edm::IOVSyncValue const&) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#7  0x00007fd930202065 in edm::EventProcessor::endRun(edm::Hash<2> const&, unsigned int, bool) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#8  0x00007fd93020244e in std::_Sp_counted_ptr_inplace<edm::(anonymous namespace)::RunResources, std::allocator<edm::(anonymous namespace)::RunResources>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#9  0x0000000000411cb6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#10 0x00007fd930208aa8 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#11 0x000000000040e772 in main::{lambda()#1}::operator()() const ()
#12 0x000000000040d135 in main ()

Current Modules:

Module: none (crashed)

A fatal system signal has occurred: segmentation violation
Segmentation fault (core dumped)
```

The segfault is because [the exception](https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/EventSetupRecord.cc#L124), which is thrown during `EventSetupProvider::finishConfiguration()`, is passed somewhere (not sure how, got confused by `EventProcessor.cc` :) which leaves `EventSetupProvider` in a bad state since now [finders_](https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/EventSetupProvider.cc#L306) is null but [mustFinishConfiguration_](https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/EventSetupProvider.cc#L397) is still true.  Then, next time `EventSetupProvider::finishConfiguration()` is called (since the above is still true), [this dereference](https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/EventSetupProvider.cc#L285) segfaults.

**Comment by Dr15Jones** [comment]
Assign core

**Comment by Dr15Jones** [comment]
Thanks for the detailed report. I was able to reproduce the behavior.

**Comment by Dr15Jones** [comment]
https://github.com/cms-sw/cmssw/pull/19966 fixes the problem

**Comment by Dr15Jones** [comment]
+1
