### ISSUE TITLE
html5lib dependency missing for jupyter in CMSSW 9.2.X

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmssw#20031]
Dear experts,

I've been trying to set-up a jupyter notebook for the CMS Physics Object School and I realized that some features appear to be broken moving from 9.1.X to 9.2.X

I do the following:
```
ssh -L localhost:4444:localhost:4444 lxplus.cern.ch
cmsrel CMSSW_9_2_7_patch1
cd CMSSW_9_2_7_patch1/src
cmsenv
jupyter notebook --no-browser --port=4444 --ip=127.0.0.1
```

and get the following error

```
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/bin/jupyter-notebook", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 677, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs/5.0-njopjo3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'html5lib>=0.99999999' distribution was not found and is required by bleach
```

The same was not happening using CMSSW_9_0_1. Is it a known issue? Is there a new syntax/workaround?

Thanks for the help.
Best,

Mauro

**Comment by davidlange6** [comment]
hi - i thought i had fixed this...let me check to see what went wrong..

**Comment by mverzett** [comment]
@davidlange6 any updates on the issue?

**Comment by davidlange6** [comment]
Hi - could you check that CMSSW_9_2_8 works ok for you?
Thanks-

**Comment by mverzett** [comment]
@davidlange6 , I can confirm it works. Thanks!
