### ISSUE TITLE
Early delete exception message does not have proper context

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#20190]
If a data product which was deleted early is requested via prefetching, we get the message

```
----- Begin Fatal Exception 16-Aug-2017 13:52:35 CDT-----------------------
An exception of category 'ProductDeleted' occurred while
   [0] Processing Event run: 1 lumi: 1 event: 1
   [1] Running path 'AODSIMoutput_step'
Exception Message:
ProductResolverBase::resolveProduct_: The product matching all criteria was already deleted
Looking for type: RegionsSeedingHitSets
Looking for module label: tripletElectronHitTriplets
Looking for productInstanceName: 
Looking for process: RECO
This means there is a configuration error.
The module which is asking for this data must be configured to state that it will read this data.
----- End Fatal Exception -------------------------------------------------
```
which does not contain information about what module requested the prefetch. The traceback for the throw is

```
#0  __cxxabiv1::__cxa_throw (obj=0x7fff97719e00, tinfo=0x7ffff7dc7aa0 <typeinfo for edm::ProductDeletedException>, dest=0x7ffff7c26600 <edm::ProductDeletedException::~ProductDeletedException()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:63
#1  0x00007ffff7c20b2b in edm::DataManagingProductResolver::throwProductDeletedException() const ()
   from /cvmfs/cms-ib.cern.ch/nweek-02485/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-08-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#2  0x00007ffff7c20c38 in edm::FunctorWaitingTask<edm::UnscheduledProductResolver::prefetchAsync_(edm::WaitingTask*, edm::Principal const&, bool, edm::SharedResourcesAcquirer*, edm::ModuleCallingContext const*) const::{lambda(std::__exception_ptr::exception_ptr const*)#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02485/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-08-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#3  0x00007ffff68a8953 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7ffff55c7200, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:501
#4  0x00007ffff7ccac3c in edm::EventProcessor::readAndProcessEvents() () from /cvmfs/cms-ib.cern.ch/nweek-02485/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-08-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#5  0x00007ffff7cd5591 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/nweek-02485/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-08-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#6  0x000000000040e752 in main::{lambda()#1}::operator()() const ()
#7  0x000000000040d115 in main ()
```

and it is ultimately caught in the Path handling code.

This needs to be fixed so that the module doing the prefetching is in the context.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , is this still an open issue?

**Comment by Dr15Jones** [comment]
@makortel did we do something about this?

**Comment by makortel** [comment]
I guess we did not
