### ISSUE TITLE
edmConfigBrower broken when using era

### ISSUE THREAD

**Issue by beaudett** [cms-sw/cmssw#20415]
Hello,

I wanted to have a detailed look at the reconstruction for the upgrade and to do so I wanted to use the edmConfigBrowser.
I first dumped the python into a file
`
cmsDriver.py step3  --conditions auto:phase2_realistic -n 1 --era Phase2 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,PAT,VALIDATION:@phase2Validation+@miniAODValidation,DQM:@phase2+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --geometry Extended2023D17 --filein file:in.root --fileout file:out.root --no_exec
`
the resulting config file unfortunately breaks the edmConfigBrowser with:
`
2017-09-07 11:08:36,511 ERROR Application: openFile() - Error while opening 'step3_RAW2DIGI_L1Reco_RECO_PAT_VALIDATION_DQM.py' : Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Main/Application.py", line 902, in openFile
    if self._knownExtensionsDictionary[ext].openFile(filename):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Plugins/Browser/BrowserPlugin.py", line 176, in openFile
    return tab.controller().open(filename)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigEditorTabController.py", line 339, in open
    if BrowserTabController.open(self, filename, update):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Main/TabController.py", line 207, in open
    if self.readFile(filename):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigEditorTabController.py", line 297, in readFile
    if self.dataAccessor().open(filename):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/python/FWCore/GuiBrowsers/Vispa/Plugins/ConfigEditor/ConfigDataAccessor.py", line 165, in open
    self._file = imp.load_module(os.path.splitext(os.path.basename(self._filename))[0].replace(".", "_"), theFile, self._filename, ("py", "r", 1))
  File "step3_RAW2DIGI_L1Reco_RECO_PAT_VALIDATION_DQM.py", line 10, in <module>
    process = cms.Process('RECO',eras.Phase2)
TypeError: new___init__() takes exactly 2 arguments (3 given)
`

The workaround I found since I contacted @ahinzmann is to first do edmConfigDump and launch the edmConfigBrowser on the result. 
It would be however nice if it could be fixed directly in the edmConfigBrowser.

Thanks
Florian

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
It appears that edmConfigBrowser is unable to properly show 'unscheduled' configurations.

**Comment by Dr15Jones** [comment]
@20419 fixes the crashes seen when parsing the file. That is the best I can do. The code in FWCore/GuiBrowsers was not created by the Core team and therefore is not maintained by us. Developers outside of Core would be needed to modernize edmConfigBrowser.

**Comment by Dr15Jones** [comment]
#20419 I have now made edmConfigBrowser always go to 'unscheduled' mode since all configs are now implicitly unscheduled. However, doing that originally made edmConfigBrowser startup to not finish within the 'heat death of the universe' (I let it run for > 30 minutes and it never finished). I made performance improvements on the code and now it only takes a long time (several minutes) to finally finish its startup.

**Comment by Dr15Jones** [comment]
+1
