### ISSUE TITLE
FastSim premix configuration error

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21249]
With the change of fastsim to use era, the premix workflows are failing due to a configuration error
e.g. wf 250400
```
----- Begin Fatal Exception 10-Nov-2017 03:43:08 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
Exception Message:
EDAlias does not match data
There are no products of type 'recoTracks'
with module label 'mix' and instance name 'generalTracks'.
----- End Fatal Exception -------------------------------------------------
```

The problem appears to be from changes made in RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py. The function `loadDigiAliases` from `FastSimulation/Configuration/DigiAliases_cff.py` is being called indirectly from there (for a second time in the job) and is taking the using the argument `False`.

**Comment by Dr15Jones** [comment]
The traceback of the problem is
```
Traceback (most recent call last):
  File "ZEE_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_L1Reco_RECO_VALIDATION.py", line 31, in <module>
    process.load('FastSimulation.Configuration.Reconstruction_AftMix_cff')
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2017-11-09-2300/python/FWCore/ParameterSet/Config.py", line 583, in load
    self.extend(sys.modules[moduleName])
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2017-11-09-2300/python/FWCore/ParameterSet/Config.py", line 638, in extend
    item.apply(self)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2017-11-09-2300/python/FWCore/ParameterSet/Config.py", line 1439, in apply
    self.__func(process)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2017-11-09-2300/python/RecoTracker/FinalTrackSelectors/MergeTrackCollections_cff.py", line 64, in _fastSimGeneralTracks
    from Configuration.StandardSequences.Digi_cff import generalTracks
  File "/uscms_data/d2/cdj/build/temp/fastSim/CMSSW_10_0_X_2017-11-09-2300/python/Configuration/StandardSequences/Digi_cff.py", line 48, in <module>
    loadDigiAliases(premix = False)
  File "/uscms_data/d2/cdj/build/temp/fastSim/CMSSW_10_0_X_2017-11-09-2300/python/FastSimulation/Configuration/DigiAliases_cff.py", line 19, in loadDigiAliases
```

**Comment by Dr15Jones** [comment]
It looks like the function 
```
def _fastSimGeneralTracks(process):
    if hasattr(process,"generalTracks") and isinstance(process.generalTracks,cms.EDAlias):
        return
    from Configuration.StandardSequences.Digi_cff import generalTracks
    process.generalTracks = generalTracks
modifyMergeTrackCollections_fastSimGeneralTracks = fastSim.makeProcessModifier( _fastSimGeneralTracks )
```
should have returned early from the clause `if hasattr(...) and isinstance(...):`

**Comment by Dr15Jones** [comment]
The `if hasattr(process,"generalTracks") and isinstance(process.generalTracks,cms.EDAlias):` clause always fails because `_fastSimGeneralTracks` is not run until after the `Process` has finished loading the file and this file was already resetting `generalTracks` to a non `cms.EDAlias`.

**Comment by Dr15Jones** [comment]
I have a fix that appears to work. I'm running more tests to be sure.

**Comment by Dr15Jones** [comment]
assign fastsim

**Comment by Dr15Jones** [comment]
pull request #21263 fixes this problem.
