### ISSUE TITLE
heap-buffer-overflow, read of 4 bytes, HLTExoticaPlotter::analyze

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#21358]
CMSSW: `CMSSW_10_0_ASAN_X_2017-11-15-1800`
SCRAM_ARCH: `slc6_amd64_gcc700`
Workflow: `10224.0`
Step: `step3`

Note that files used are important here.

Detailed report:
```
17-Nov-2017 14:47:43 CET  Initiating request to open file file:step2.root
17-Nov-2017 14:47:46 CET  Successfully opened file file:step2.root
17-Nov-2017 14:48:51 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_4_0_pre3/RelValMinBias_13/GEN-SIM/94X_mc2017_realistic_v4-v1/10000/8A7E57B1-5FB9-E711-8848-0CC47A4C8F06.root
17-Nov-2017 14:48:53 CET  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_4_0_pre3/RelValMinBias_13/GEN-SIM/94X_mc2017_realistic_v4-v1/10000/8A7E57B1-5FB9-E711-8848-0CC47A4C8F06.root
Begin processing the 1st record. Run 1, Event 5651, LumiSection 114 at 17-Nov-2017 14:52:17.389 CET
17-Nov-2017 14:52:20 CET  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_4_0_pre3/RelValMinBias_13/GEN-SIM/94X_mc2017_realistic_v4-v1/10000/8A7E57B1-5FB9-E711-8848-0CC47A4C8F06.root
17-Nov-2017 14:52:20 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_4_0_pre3/RelValMinBias_13/GEN-SIM/94X_mc2017_realistic_v4-v1/10000/60212749-5CB9-E711-9643-0CC47A4C8F06.root
17-Nov-2017 14:52:22 CET  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_4_0_pre3/RelValMinBias_13/GEN-SIM/94X_mc2017_realistic_v4-v1/10000/60212749-5CB9-E711-9643-0CC47A4C8F06.root
[..]
Begin processing the 7th record. Run 1, Event 5652, LumiSection 114 at 17-Nov-2017 15:00:49.753 CET
=================================================================
==6634==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602005113ed4 at pc 0x7faf3c0d4543 bp 0x7fff4c0567e0 sp 0x7fff4c0567d8
READ of size 4 at 0x602005113ed4 thread T0
    #0 0x7faf3c0d4542 in HLTExoticaPlotter::fillHist(bool const&, std::string const&, std::string const&, std::string const&, float const&) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaPlotter.cc:275
    #1 0x7faf3c0d1003 in HLTExoticaPlotter::analyze(bool const&, std::string const&, std::vector<reco::LeafCandidate, std::allocator<reco::LeafCandidate> > const&, std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > >, std::vector<float, st
d::allocator<float> >&) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaPlotter.cc:167
    #2 0x7faf3c10ec80 in HLTExoticaSubAnalysis::analyze(edm::Event const&, edm::EventSetup const&, EVTColContainer*) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc:726
    #3 0x7faf3c0e99c5 in HLTExoticaValidator::analyze(edm::Event const&, edm::EventSetup const&) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaValidator.cc:99
    #4 0x7faf94a3ba53 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/li
b/slc6_amd64_gcc700/libFWCoreFramework.so+0x6cda53)
    #5 0x7faf9468665c in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd6
4_gcc700/libFWCoreFramework.so+0x31865c)
    #6 0x7faf9451ff9d in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::Eve
ntSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::Occurrenc
eTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week0/
slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b1f9d)
    #7 0x7faf94520422 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext
const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b2422)
    #8 0x7faf94527f3c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::Branch
ActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15
-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b9f3c)
    #9 0x7faf9452ae29 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1
bce29)
    #10 0x7faf928ac055 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) ../../src/tbb/custom_scheduler.h:509
    #11 0x7faf947ef50f in edm::EventProcessor::readAndProcessEvents() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x48150f)
    #12 0x7faf9481d366 in edm::EventProcessor::runToCompletion() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x4af366)
    #13 0x412f67 in main::{lambda()#1}::operator()() const (/cvmfs/cms-ib.cern.ch/nweek-02498/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/bin/slc6_amd64_gcc700/cmsRun+0x412f67)
    #14 0x40d322 in main (/cvmfs/cms-ib.cern.ch/nweek-02498/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/bin/slc6_amd64_gcc700/cmsRun+0x40d322)
    #15 0x326f01ed1c in __libc_start_main (/lib64/libc.so.6+0x326f01ed1c)
    #16 0x40da88  (/cvmfs/cms-ib.cern.ch/nweek-02498/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/bin/slc6_amd64_gcc700/cmsRun+0x40da88)

0x602005113ed4 is located 0 bytes to the right of 4-byte region [0x602005113ed0,0x602005113ed4)
allocated by thread T0 here:
    #0 0x7faf94c3e1c0 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:80
    #1 0x7faf80685805 in void std::vector<float, std::allocator<float> >::_M_realloc_insert<float const&>(__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, float const&) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_A
SAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libDataFormatsPatCandidates.so+0x3e2805)
    #2 0x7faf6be1523c in std::vector<float, std::allocator<float> >::push_back(float const&) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libPhysicsToolsUtilAlgos.so+0x6b23c)
    #3 0x7faf3c10e8aa in HLTExoticaSubAnalysis::analyze(edm::Event const&, edm::EventSetup const&, EVTColContainer*) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc:712
    #4 0x7faf3c0e99c5 in HLTExoticaValidator::analyze(edm::Event const&, edm::EventSetup const&) /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaValidator.cc:99
    #5 0x7faf94a3ba53 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/li
b/slc6_amd64_gcc700/libFWCoreFramework.so+0x6cda53)
    #6 0x7faf9468665c in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd6
4_gcc700/libFWCoreFramework.so+0x31865c)
    #7 0x7faf9451ff9d in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::Eve
ntSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::Occurrenc
eTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week0/
slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b1f9d)
    #8 0x7faf94520422 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext
const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b2422)
    #9 0x7faf94527f3c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::Branch
ActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15
-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1b9f3c)
    #10 0x7faf9452ae29 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_0_ASAN_X_2017-11-15-1800/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x
1bce29)
    #11 0x7faf928ac055 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) ../../src/tbb/custom_scheduler.h:509

SUMMARY: AddressSanitizer: heap-buffer-overflow /build/davidlt/CMSSW_10_0_ASAN_X_2017-11-15-1800/src/HLTriggerOffline/Exotica/src/HLTExoticaPlotter.cc:275 in HLTExoticaPlotter::fillHist(bool const&, std::string const&, std::string const&, std::string const&, float const&)
Shadow bytes around the buggy address:
  0x0c0480a1a780: fa fa 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480a1a790: fa fa 00 00 fa fa fd fd fa fa fd fa fa fa fa fa
  0x0c0480a1a7a0: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480a1a7b0: fa fa fd fd fa fa fa fa fa fa fa fa fa fa 04 fa
  0x0c0480a1a7c0: fa fa fa fa fa fa fd fa fa fa 04 fa fa fa 04 fa
=>0x0c0480a1a7d0: fa fa 04 fa fa fa fa fa fa fa[04]fa fa fa fa fa
  0x0c0480a1a7e0: fa fa 04 fa fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c0480a1a7f0: fa fa fa fa fa fa fa fa fa fa 00 00 fa fa 04 fa
  0x0c0480a1a800: fa fa fa fa fa fa 04 fa fa fa fa fa fa fa fd fa
  0x0c0480a1a810: fa fa 04 fa fa fa fa fa fa fa fd fd fa fa 01 fa
  0x0c0480a1a820: fa fa fa fa fa fa 04 fa fa fa 04 fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6634==ABORTING
```

The problem is here:
https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Exotica/src/HLTExoticaPlotter.cc#L167

`dxys` only contains one element and `j` is 1 thus out-of-bounds access.

As mentioned files are important and one needs to run workflow exactly as does IB infrastructure. For example:
```
export CMS_PATH=/cvmfs/cms-ib.cern.ch/week0
# or
unset CMS_PATH
. /cvmfs/cms-ib.cern.ch/week0/cmsset_default.sh

scram p <REL>
cd <REL>
cmsenv
git clone https://github.com/cms-sw/cms-bot
export PATH=${CMSSW_BASE}/cms-bot/das-utils:$PATH
cms-bot/das-utils/use-ibeos-sort
runTheMatrix -i all -l <WORKFLOW>
```

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by jfernan2** [comment]
please test

**Comment by davidlt** [comment]
@jfernan2 this is not a PR, but a bug report. "please test" will not work here.

**Comment by davidlt** [comment]
ping

@jfernan2 @dmitrijus is anyone looking into this from DQM side?

**Comment by jfernan2** [comment]
@davidlt we are overloaded and @dmitrijus is on holiday until 28th, he will look into this once he is back. I'm sorry

**Comment by davidlt** [comment]
It's fine. Just good to know the current status.

**Comment by schneiml** [comment]
@Dr15Jones is this issue still observed somewhere? Where could we check that?

**Comment by Dr15Jones** [comment]
@schneiml I suggest looking at the git history for the line of code mentioned in this issue and see if it has been changed since this issue was created.

**Comment by fioriNTU** [comment]
+1

This issue look very similar (the same?) to this one https://github.com/cms-sw/cmssw/issues/25782
Probably we can close this one and keep open the newer one
