### ISSUE TITLE
Excessive exceptions thrown in omtf::translateOmtf2Pact

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21420]
While debugging another problem with workflow 250202.0 step3, having gdb stop on exception throws causes many 10s of exceptions to be caught from:

```
#0  __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fff777ed2c0, tinfo=0x7ffff6395a78 <typeinfo for std::out_of_range>, dest=0x7ffff62c5920 <std::out_of_range::~out_of_range()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:63
#1  0x00007ffff62d8977 in std::__throw_out_of_range (__s=0x7fffae0b47af "map::at") at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:90
#2  0x00007fffae0aee3d in omtf::translateOmtf2Pact(omtf::RpcLinkMap const&, RPCReadOutMapping const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_ROOT6_X_2017-11-20-1000/lib/slc6_amd64_gcc630/libEventFilterL1TRawToDigi.so
#3  0x00007fffae09ab05 in omtf::RpcUnpacker::init(edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_ROOT6_X_2017-11-20-1000/lib/slc6_amd64_gcc630/libEventFilterL1TRawToDigi.so
#4  0x00007fff9fe1c0df in omtf::OmtfUnpacker::beginRun(edm::Run const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_ROOT6_X_2017-11-20-1000/lib/slc6_amd64_gcc630/pluginEventFilterL1TRawToDigiAuto.so
```

Exceptions should be used for exceptional cases, not for control flow.

**Comment by smuzaffar** [comment]
this has been fixed via https://github.com/cms-sw/cmssw/pull/22191
