### ISSUE TITLE
gfal compatibility with CMSSW_10

### ISSUE THREAD

**Issue by aminnj** [cms-sw/cmssw#21740]
I'm unable to use gfal-copy in CMSSW_10_0_0_pre1, for example. With
```bash
export SCRAM_ARCH=slc6_amd64_gcc630
cmsrel CMSSW_10_0_0_pre1
cd CMSSW_10_0_0_pre1; cmsenv
gfal-copy -V
```
I get [1]. I saw that the issue at https://github.com/cms-sw/cmssw/issues/14231 discusses something similar. I don't get a crash if I do `LD_PRELOAD=/usr/lib64/gfal2-plugins//libgfal_plugin_xrootd.so gfal-copy -V`. While I understand that CMSSW isn't obligated to support such stageout commands, it would be convenient if it did, if it's easy to do so.

[1]
```
Traceback (most recent call last):
  File "/usr/bin/gfal-copy", line 12, in <module>
    sys.exit(Gfal2Shell().main(sys.argv))
  File "/usr/lib/python2.6/site-packages/gfal2_util/shell.py", line 69, in main
    inst.parse(command_func, args)
  File "/usr/lib/python2.6/site-packages/gfal2_util/base.py", line 215, in parse
    self.params = self.parser.parse_args(a[1:])
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/6.0-mmelna/lib/python2.7/site-packages/argparse.py", line 1725, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/6.0-mmelna/lib/python2.7/site-packages/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/6.0-mmelna/lib/python2.7/site-packages/argparse.py", line 1960, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/6.0-mmelna/lib/python2.7/site-packages/argparse.py", line 1900, in consume_optional
    take_action(action, args, option_string)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/6.0-mmelna/lib/python2.7/site-packages/argparse.py", line 1828, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.6/site-packages/gfal2_util/base.py", line 72, in __call__
    for plugin in sorted(gfal2.creat_context().get_plugin_names()):
gfal2.GError: Unable to open the /usr/lib64/gfal2-plugins//libgfal_plugin_xrootd.so plugin specified in the plugin directory, failure : /usr/lib64/gfal2-plugins//libgfal_plugin_xrootd.so: undefined symbol: _ZNK5XrdCl6Status8ToStringEv
```

**Comment by davidlange6** [comment]
Hi @aminnj - can you confirm this is not working since CMSSW_9_3_0?

**Comment by aminnj** [comment]
Hi, I just now tried CMSSW_9_3_0 and see the same crash. Going back to 9_2_0, I see the same crash if my SCRAM_ARCH is using gcc630, but not when my SCRAM_ARCH is using gcc530.

**Comment by davidlange6** [comment]
right - while its working by luck in 9_2_0 (eg, no good reason the python libraries have to be compatible, but they happen to be) - the ABI change in gcc630 is breaking this tool in the CMSSW environment.

**Comment by davidlange6** [comment]
assign core

**Comment by smuzaffar** [comment]
`gfal-*` tools explicitly run `/usr/bin/python2` which will not work in cmssw.

**Comment by smuzaffar** [comment]
not going to fix it. mixing system python with cmssw env will not work
