### ISSUE TITLE
cmsShow crashes in CMSSW_10_1_X IB with 2017 reco geometry

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#22161]
To reproduce the crash:

```
cmsrel CMSSW_10_1_X_2018-02-06-2300
cd CMSSW_10_1_X_2018-02-06-2300/src
cmsenv
cmsShow
```

```
$ cmsShow
Starting cmsShow, version CMSSW_10_1_X_2018-02-06-2300.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Info: No data file given.
Info: Load idToGeo 2017 from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/data/Fireworks/Geometry/data/cmsGeom10.root
Program received signal ID = 11
Printing stack trace ... 
#0  0x0000003858aac86d in waitpid () from /lib64/libc.so.6
#1  0x0000003858a3e479 in do_system () from /lib64/libc.so.6
#2  0x0000003858a3e7b0 in system () from /lib64/libc.so.6
#3  0x00000000004033be in (anonymous namespace)::signal_handler_wrapper(int, siginfo*, void*) ()
#4  <signal handler called>
#5  0x00007f9b7c0b9e42 in FWGeometry::loadMap(char const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/lib/slc6_amd64_gcc630/libFireworksCore.so
#6  0x00007f9b7c0a5bf2 in CmsShowMainBase::loadGeometry() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/lib/slc6_amd64_gcc630/libFireworksCore.so
#7  0x00007f9b7c0b2dcf in CmsShowTaskExecutor::doNextTaskImp() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/lib/slc6_amd64_gcc630/libFireworksCore.so
#8  0x00007f9b7bfdae35 in CmsShowTaskExecutorBase::doNextTask() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/lib/slc6_amd64_gcc630/libFireworksCore.so
#9  0x00007f9b7c0e45ed in CmsShowTaskTimer::Notify() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/lib/slc6_amd64_gcc630/libFireworksCore.so
#10 0x00007f9b78d4c061 in TTimer::CheckTimer(TTime const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#11 0x00007f9b78df3eb9 in TUnixSystem::DispatchTimers(bool) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#12 0x00007f9b78df4933 in TUnixSystem::DispatchOneEvent(bool) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#13 0x00007f9b78d3bd04 in TSystem::InnerLoop() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#14 0x00007f9b78d3a91f in TSystem::Run() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#15 0x00007f9b78cd542f in TApplication::Run(bool) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/external/slc6_amd64_gcc630/lib/libCore.so
#16 0x0000000000403106 in run_app(TApplication&, int, char**) ()
#17 0x0000000000402b7a in main ()
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-02-06-2300/bin/slc6_amd64_gcc630/cmsShow: line 152: glxinfo: command not found

  #############################################################################
  #                                                                           # 
  #  Abnormal program termination!                                            # 
  #                                                                           # 
  #  Please send:                                                             # 
  #  /tmp/cmsshow-crash-report-lHVdYREH.txt                                   # 
  #  to hn-cms-visualization@cern.ch.                                         # 
  #                                                                           # 
  #############################################################################


```
Note, it works fine with cmsShow -g cmsGeomRun1.root

FYI @alja

**Comment by fabiocos** [comment]
assign geometry, visualization

**Comment by alja** [comment]
@ianna 
Looks like there is a problem with the default geometry file. I will look at it.
Thanks,
Alja

**Comment by fabiocos** [comment]
@alja @ianna the fix has been integrated, is this finally solving the problem and closing the issue?

**Comment by alja** [comment]
The PR closes the issue.

**Comment by ianna** [comment]
+1

fixed
