### ISSUE TITLE
Jupyter notebook broken

### ISSUE THREAD

**Issue by HeinerTholen** [cms-sw/cmssw#23401]
``jupyter notebook`` fails with the traceback below, starting from CMSSW_10_1_0_pre3. It is still working in CMSSW_10_1_0_pre2.

    Traceback (most recent call last):
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/bin/jupyter-notebook", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
        @_call_aside
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
        f(*args, **kwargs)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
        ws.require(__requires__)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/py2-pippkgs/6.0-omkpbe3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'Send2Trash' distribution was not found and is required by notebook

**Comment by VinInn** [comment]
in 10_4 is 'ipaddress'  that is missing instead
```
jupyter notebook --no-browser --port=8890
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-30-2300/external/slc7_amd64_gcc700/bin/jupyter-notebook", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/cvmfs/cms-ib.cern.ch/nweek-02548/slc7_amd64_gcc700/external/py2-setuptools/28.3.0-gnimlf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by notebook
```

**Comment by davidlange6** [comment]
argh - fixed this once - apparently I didn't commit it. Will look into this again - thanks for reporting

**Comment by smuzaffar** [comment]
this has been fixed 
```
muzaffar@cmsdev31.cern.ch>jupyter notebook --no-browser --port=8890
[I 00:17:04.536 NotebookApp] Serving notebooks from local directory: /build/muz/pt/x/CMSSW_11_1_X_2019-12-02-1100/src/135.9_ZMM_13+ZMMFS_13+HARVESTUP15FS+MINIAODMCUP15FS
[I 00:17:04.536 NotebookApp] The Jupyter Notebook is running at:
[I 00:17:04.537 NotebookApp] http://localhost:8890/?token=74e4f2b79f66f8deed51b4ed51a7688d51a25887e9fe40d9
[I 00:17:04.537 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:17:04.560 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///afs/cern.ch/user/m/muzaffar/.local/share/jupyter/runtime/nbserver-9207-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=74e4f2b79f66f8deed51b4ed51a7688d51a25887e9fe40d9

```
