### ISSUE TITLE
RelVal failure for BMTF code update

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24628]
After the merge of #24557 two RelVal workflows (134.813 and 136.8562) fail with exception

----- Begin Fatal Exception 24-Sep-2018 05:55:13 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 256259 lumi: 167 event: 15552527 stream: 3
   [1] Calling method for module L1TStage2RegionalMuonCandComp/'l1tdeStage2Bmtf'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: BXVector&lt;l1t::RegionalMuonCand&gt;
Looking for module label: valBmtfAlgoSel
Looking for productInstanceName: BMTF

----- End Fatal Exception -------------------------------------------------

and a SIGSEV in L1TBMTFAlgoSelector:valBmtfAlgoSel (crashed)

Thread 1 (Thread 0x7f4ef3f53480 (LWP 24682)):
#0  0x00007f4ef587ef0d in poll () from /lib64/libc.so.6
#1  0x00007f4ee1e00bd7 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02543/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_3_X_2018-09-23-0000/lib/slc7_amd64_gcc700/pluginFWCoreServicesPlugins.so
#2  0x00007f4ee1e0126c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02543/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_3_X_2018-09-23-0000/lib/slc7_amd64_gcc700/pluginFWCoreServicesPlugins.so
#3  0x00007f4ee1e022d9 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02543/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_3_X_2018-09-23-0000/lib/slc7_amd64_gcc700/pluginFWCoreServicesPlugins.so
#4  &lt;signal handler called&gt;
#5  0x00007f4edfed62b3 in FEDHeader::bxID() const () from /cvmfs/cms-ib.cern.ch/nweek-02543/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_3_X_2018-09-23-0000/lib/slc7_amd64_gcc700/libDataFormatsFEDRawData.so
#6  0x00007f4e8783e421 in dqmBmtfAlgoSelector::L1TBMTFAlgoSelector::produce(edm::Event&amp, edm::EventSetup const&amp) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_3_X_2018-09-23-2300/lib/slc7_amd64_gcc700/pluginDQML1TMonitorPlugins.so

**Comment by fabiocos** [comment]
it looks fixed by #24652

**Comment by fabiocos** [comment]
@rekovic @thomreis sorry, mixing two different L1 issues, this is solved, it is #24578 causing this new issue (the addition of the L1 emulator in the DQM sequence)
