### ISSUE TITLE
Bad memory read in MPUnpacker_0x10010010 for WF 136.733

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#25121]
The AddressSanitizer found a read outside the bounds of an array in MPUnpacker_0x10010010 for WF 136.733.

**Comment by Dr15Jones** [comment]
assign l1

**Comment by Dr15Jones** [comment]
I recompiled the code with the debug symbols and reran the AddressSantizer on the workflow. The infomration was
```
==28805==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6040056bd538 at pc 0x7f964455faeb bp 0x7fff32d492a0 sp 0x7fff32d49298
READ of size 4 at 0x6040056bd538 thread T0
    #0 0x7f964455faea in l1t::stage2::MPUnpacker_0x10010010::unpack(l1t::Block const&, l1t::UnpackerCollections*) /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/plugins/implementations_stage2/MPUnpacker_0x10010010.cc:319
    #1 0x7f96442e74fb in l1t::L1TRawToDigi::produce(edm::Event&, edm::EventSetup const&) /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc:285
    #2 0x7f968def5b8b in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/s
lc6_amd64_gcc700/libFWCoreFramework.so+0x756b8b)
    #3 0x7f968dae2a2c in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_g
cc700/libFWCoreFramework.so+0x343a2c)
    #4 0x7f968d9646d3 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventS
etup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTrait
s<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd6
4_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1c56d3)
    #5 0x7f968d964b62 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext con
st&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1c5b62)
    #6 0x7f968d96bd9c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchAct
ionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/
lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1ccd9c)
    #7 0x7f968d971669 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1d26
69)
    #8 0x7f968b960095 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) ../../src/tbb/custom_scheduler.h:509
    #9 0x7f968dc7048d in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x4d148d)
    #10 0x7f968dc82fbe in edm::EventProcessor::runToCompletion() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x4e3fbe)
    #11 0x415924 in main::{lambda()#1}::operator()() const (/cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/bin/slc6_amd64_gcc700/cmsRun+0x415924)
    #12 0x40ed83 in main (/cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/bin/slc6_amd64_gcc700/cmsRun+0x40ed83)
    #13 0x395241ed1f in __libc_start_main (/lib64/libc.so.6+0x395241ed1f)
    #14 0x40f4c8  (/cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/bin/slc6_amd64_gcc700/cmsRun+0x40f4c8)

0x6040056bd538 is located 0 bytes to the right of 40-byte region [0x6040056bd510,0x6040056bd538)
allocated by thread T0 here:
    #0 0x7f968e1221e0 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:80
    #1 0x7f96540d72f5 in __gnu_cxx::new_allocator<unsigned int>::allocate(unsigned long, void const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/external/slc6_amd64_gcc700/lib/libfastjetcontribfragile.so+0x1022f5)
    #2 0x7f96540d71e5 in std::allocator_traits<std::allocator<unsigned int> >::allocate(std::allocator<unsigned int>&, unsigned long) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/external/slc6_amd64_gcc700/lib/libfastjetcontribfragile.so+0x1021e5)
    #3 0x7f96540d7095 in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_allocate(unsigned long) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/external/slc6_amd64_gcc700/lib/libfastjetcontribfragile.so+0x102095)
    #4 0x7f9644511297 in void std::vector<unsigned int, std::allocator<unsigned int> >::_M_range_initialize<unsigned int const*>(unsigned int const*, unsigned int const*, std::forward_iterator_tag) /cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/include/c++/7.3.1/bits/stl_vector.h:1323
    #5 0x7f964450fd9b in void std::vector<unsigned int, std::allocator<unsigned int> >::_M_initialize_dispatch<unsigned int const*>(unsigned int const*, unsigned int const*, std::__false_type) /cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/include/c++/7.3.1/bits/stl_vector.h:1299
    #6 0x7f964450eee7 in std::vector<unsigned int, std::allocator<unsigned int> >::vector<unsigned int const*, void>(unsigned int const*, unsigned int const*, std::allocator<unsigned int> const&) /cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/include/c++/7.3.1/bits/stl_vector.h:414
    #7 0x7f9643a81fba in l1t::Block::Block(l1t::BlockHeader const&, unsigned int const*, unsigned int const*) /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/interface/Block.h:51
    #8 0x7f9643a7d3d4 in l1t::Payload::getBlock() /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/src/Block.cc:97
    #9 0x7f96442e67d7 in l1t::L1TRawToDigi::produce(edm::Event&, edm::EventSetup const&) /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc:254
    #10 0x7f968def5b8b in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x756b8b)
    #11 0x7f968dae2a2c in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x343a2c)
    #12 0x7f968d9646d3 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1c56d3)
    #13 0x7f968d964b62 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1c5b62)
    #14 0x7f968d96bd9c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1ccd9c)
    #15 0x7f968d971669 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_ASAN_X_2018-11-02-2300/lib/slc6_amd64_gcc700/libFWCoreFramework.so+0x1d2669)
    #16 0x7f968b960095 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) ../../src/tbb/custom_scheduler.h:509

SUMMARY: AddressSanitizer: heap-buffer-overflow /build/chrjones/temp/asan/CMSSW_10_4_ASAN_X_2018-11-02-2300/src/EventFilter/L1TRawToDigi/plugins/implementations_stage2/MPUnpacker_0x10010010.cc:319 in l1t::stage2::MPUnpacker_0x10010010::unpack(l1t::Block const&, l1t::UnpackerCollections*)
Shadow bytes around the buggy address:
  0x0c0880acfa50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0880acfa60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0880acfa70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0880acfa80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0880acfa90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c0880acfaa0: fa fa 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa
  0x0c0880acfab0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880acfac0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0880acfad0: fa fa fa fa fa fa fa fa fa fa fd fd fd fd fd fa
  0x0c0880acfae0: fa fa fa fa fa fa fa fa fa fa fd fd fd fd fd fa
  0x0c0880acfaf0: fa fa fa fa fa fa fa fa fa fa fd fd fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==28805==ABORTING
```

**Comment by Dr15Jones** [comment]
The line of code with the invalid read is
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/EventFilter/L1TRawToDigi/plugins/implementations_stage2/MPUnpacker_0x10010010.cc#L319

with the memory coming from 
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/EventFilter/L1TRawToDigi/interface/Block.h#L51

where the constructor is called from 
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/EventFilter/L1TRawToDigi/src/Block.cc#L97

from this, the `header.getSize()` must be less than `faux == 10`.

**Comment by thomreis** [comment]
Hi @bundocka 
could you take a look at this please?

**Comment by bundocka** [comment]
I am a bit busy with HI stuff at the moment, but soon I will provide a PR that updates the unpackers such that the index is checked to be within the size of the block.
It is very bizarre that this problem has occurred however, since the firmware version is unpacked from the header and used to call the correct unpacker. In this case, for some reason, the extra frame that should be present in the readout does not appear to be there. I will investigate this also.

**Comment by bundocka** [comment]
This should now be handled by #25303

**Comment by thomreis** [comment]
+1
