### ISSUE TITLE
Failure in NanoAOD wf 1325.9 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25409]
After the integration of #25373 in the 10_4_X branch, the test wf 1325.9 fails in its step 2 with a configuration problem:

entry filelist:step1_dasquery.log
found files:  ['/store/relval/CMSSW_9_2_12/RelValTTbar_13/MINIAODSIM/PU25ns_92X_upgrade2017_realistic_v11-v1/00000/080E2624-F59D-E711-ACEE-0CC47A7C35A4.root', '/store/relval/CMSSW_9_2_12/RelValTTbar_13/MINIAODSIM/PU25ns_92X_upgrade2017_realistic_v11-v1/00000/507B6124-F59D-E711-A09A-0CC47A4C8EC6.root']
Step: NANO Spec: 
Step: DQM Spec: ['@nanoAODDQM']
customising the process with nanoAOD_customizeMC from PhysicsTools/NanoAOD/nano_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/bin/slc7_amd64_gcc700/cmsDriver.py", line 56, in &lt;module&gt;
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/bin/slc7_amd64_gcc700/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/Configuration/Applications/ConfigBuilder.py", line 2248, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/Configuration/Applications/ConfigBuilder.py", line 883, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/PhysicsTools/NanoAOD/nano_cff.py", line 279, in nanoAOD_customizeMC
    process = nanoAOD_customizeCommon(process)
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/PhysicsTools/NanoAOD/nano_cff.py", line 241, in nanoAOD_customizeCommon
    process = nanoAOD_activateVID(process)
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/PhysicsTools/NanoAOD/nano_cff.py", line 190, in nanoAOD_activateVID
    process.electronSequence.insert(process.electronSequence.index(bitmapVIDForEle),process.egmGsfElectronIDSequence)
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 368, in index
    return self._seq.index(item)
  File "/cvmfs/cms-ib.cern.ch/nweek-02553/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-12-03-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 182, in index
    return self._collection.index(item)
ValueError: cms.EDProducer("EleVIDNestedWPBitmapProducer",
    WorkingPoints = cms.vstring(
        'egmGsfElectronIDs:cutBasedElectronID-Fall17-94X-V2-veto', 
        'egmGsfElectronIDs:cutBasedElectronID-Fall17-94X-V2-loose', 
        'egmGsfElectronIDs:cutBasedElectronID-Fall17-94X-V2-medium', 
        'egmGsfElectronIDs:cutBasedElectronID-Fall17-94X-V2-tight'
    ),
    src = cms.InputTag("slimmedElectronsUpdated")
)
 is not in list

**Comment by fabiocos** [comment]
The issue in itself should be solved now
