### ISSUE TITLE
Still memory problems in CSCTriggerPrimitivesProducer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#25709]
The Address Santizer has found the following problem:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc700/CMSSW_10_5_ASAN_X_2019-01-18-2300/pyRelValMatrixLogs/run/22034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D23_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D23+RecoFullGlobal_2023D23+HARVESTFullGlobal_2023D23/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D23_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D23+RecoFullGlobal_2023D23+HARVESTFullGlobal_2023D23.log

With the full message being:
```
=================================================================
==19376==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6170010d8030 at pc 0x7fbd7497a08a bp 0x7fff0bed3e50 sp 0x7fff0bed3e48
READ of size 4 at 0x6170010d8030 thread T0
    #0 0x7fbd7497a089 in CSCGEMMotherboard::getPad(CSCCLCTDigi const&amp, CSCPart) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xfd089)
    #1 0x7fbd74925132 in GEMCoPadDigi CSCGEMMotherboard::bestMatchingPad<GEMCoPadDigi>(CSCALCTDigi const&amp, CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > > const&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xa8132)
    #2 0x7fbd7496610b in CSCGEMMotherboardME11::correlateLCTsGEM(CSCALCTDigi const&amp, CSCALCTDigi const&amp, CSCCLCTDigi const&amp, CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMPadDigi>, std::allocator<std::pair<unsigned int, GEMPadDigi> > > const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > > const&amp, CSCCorrelatedLCTDigi&amp, CSCCorrelatedLCTDigi&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xe910b)
    #3 0x7fbd7496a829 in CSCGEMMotherboardME11::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xed829)
    #4 0x7fbd7494d872 in CSCTriggerPrimitivesBuilder::build(CSCBadChambers const*, MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigiCluster> const*, MuonDigiCollection<CSCDetId, CSCALCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTPreTriggerDigi>&amp, MuonDigiCollection<CSCDetId, int>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<GEMDetId, GEMCoPadDigi>&amp) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xd0872)
    #5 0x7fbd74a6c776 in CSCTriggerPrimitivesProducer::produce(edm::StreamID, edm::Event&amp, edm::EventSetup const&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/pluginCSCTriggerPrimitivesPlugins.so+0x1c776)
    #6 0x7fbdad169768 in edm::global::EDProducerBase::doEvent(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x70d768)
    #7 0x7fbdacdc321c in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x36721c)
    #8 0x7fbdacc8a363 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e363)
    #9 0x7fbdacc8a7f2 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e7f2)
    #10 0x7fbdacc91a2c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x235a2c)
    #11 0x7fbdacc971d9 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x23b1d9)
    #12 0x7fbdaac0c175 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&amp, tbb::task*) ../../src/tbb/custom_scheduler.h:521
    #13 0x7fbdacf4c91d in edm::EventProcessor::processLumis(std::shared_ptr<void> const&amp) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x4f091d)
    #14 0x7fbdacf5f43e in edm::EventProcessor::runToCompletion() (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x50343e)
    #15 0x415c01 in main::{lambda()#1}::operator()() const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/bin/slc7_amd64_gcc700/cmsRun+0x415c01)
    #16 0x40f083 in main (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/bin/slc7_amd64_gcc700/cmsRun+0x40f083)
    #17 0x7fbda9519444 in __libc_start_main (/lib64/libc.so.6+0x22444)
    #18 0x40f7c8  (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/bin/slc7_amd64_gcc700/cmsRun+0x40f7c8)

0x6170010d8030 is located 48 bytes to the right of 768-byte region [0x6170010d7d00,0x6170010d8000)
freed by thread T0 here:
    #0 0x7fbdad3f3ee0 in operator delete(void*) ../../../../libsanitizer/asan/asan_new_delete.cc:124
    #1 0x7fbd7492ba8a in void CSCGEMMotherboard::matchingPads<GEMCoPadDigi>(CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xaea8a)
    #2 0x7fbd7492c57f in void CSCGEMMotherboard::matchingPads<CSCCLCTDigi, GEMCoPadDigi>(CSCCLCTDigi const&amp, CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xaf57f)
    #3 0x7fbd7492f0a5 in void CSCGEMMotherboard::matchingPads<GEMCoPadDigi>(CSCCLCTDigi const&amp, CSCCLCTDigi const&amp, CSCALCTDigi const&amp, CSCALCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xb20a5)
    #4 0x7fbd7496a5b3 in CSCGEMMotherboardME11::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xed5b3)
    #5 0x7fbd7494d872 in CSCTriggerPrimitivesBuilder::build(CSCBadChambers const*, MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigiCluster> const*, MuonDigiCollection<CSCDetId, CSCALCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTPreTriggerDigi>&amp, MuonDigiCollection<CSCDetId, int>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<GEMDetId, GEMCoPadDigi>&amp) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xd0872)
    #6 0x7fbd74a6c776 in CSCTriggerPrimitivesProducer::produce(edm::StreamID, edm::Event&amp, edm::EventSetup const&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/pluginCSCTriggerPrimitivesPlugins.so+0x1c776)
    #7 0x7fbdad169768 in edm::global::EDProducerBase::doEvent(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x70d768)
    #8 0x7fbdacdc321c in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x36721c)
    #9 0x7fbdacc8a363 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e363)
    #10 0x7fbdacc8a7f2 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e7f2)
    #11 0x7fbdacc91a2c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x235a2c)
    #12 0x7fbdacc971d9 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x23b1d9)
    #13 0x7fbdaac0c175 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&amp, tbb::task*) ../../src/tbb/custom_scheduler.h:521

previously allocated by thread T0 here:
    #0 0x7fbdad3f31e0 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:80
    #1 0x7fbd748ad390 in CSCGEMMotherboardLUTME11::get_csc_hs_to_gem_pad(Parity, CSCPart) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0x30390)
    #2 0x7fbd7492b5f9 in void CSCGEMMotherboard::matchingPads<GEMCoPadDigi>(CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xae5f9)
    #3 0x7fbd7492c57f in void CSCGEMMotherboard::matchingPads<CSCCLCTDigi, GEMCoPadDigi>(CSCCLCTDigi const&amp, CSCCLCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xaf57f)
    #4 0x7fbd7492f0a5 in void CSCGEMMotherboard::matchingPads<GEMCoPadDigi>(CSCCLCTDigi const&amp, CSCCLCTDigi const&amp, CSCALCTDigi const&amp, CSCALCTDigi const&amp, std::vector<std::pair<unsigned int, GEMCoPadDigi>, std::allocator<std::pair<unsigned int, GEMCoPadDigi> > >&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xb20a5)
    #5 0x7fbd7496a5b3 in CSCGEMMotherboardME11::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xed5b3)
    #6 0x7fbd7494d872 in CSCTriggerPrimitivesBuilder::build(CSCBadChambers const*, MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigiCluster> const*, MuonDigiCollection<CSCDetId, CSCALCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCLCTPreTriggerDigi>&amp, MuonDigiCollection<CSCDetId, int>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&amp, MuonDigiCollection<GEMDetId, GEMCoPadDigi>&amp) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xd0872)
    #7 0x7fbd74a6c776 in CSCTriggerPrimitivesProducer::produce(edm::StreamID, edm::Event&amp, edm::EventSetup const&amp) const (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/pluginCSCTriggerPrimitivesPlugins.so+0x1c776)
    #8 0x7fbdad169768 in edm::global::EDProducerBase::doEvent(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x70d768)
    #9 0x7fbdacdc321c in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventPrincipal const&amp, edm::EventSetup const&amp, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x36721c)
    #10 0x7fbdacc8a363 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e363)
    #11 0x7fbdacc8a7f2 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x22e7f2)
    #12 0x7fbdacc91a2c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&amp, edm::EventSetup const&amp, edm::StreamID, edm::ParentContext const&amp, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x235a2c)
    #13 0x7fbdacc971d9 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libFWCoreFramework.so+0x23b1d9)
    #14 0x7fbdaac0c175 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&amp, tbb::task*) ../../src/tbb/custom_scheduler.h:521

SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/nweek-02559/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_ASAN_X_2019-01-18-2300/lib/slc7_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so+0xfd089) in CSCGEMMotherboard::getPad(CSCCLCTDigi const&amp, CSCPart) const
Shadow bytes around the buggy address:
  0x0c2e80212fb0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80212fc0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80212fd0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80212fe0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80212ff0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c2e80213000: fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa fa fa
  0x0c2e80213010: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80213020: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80213030: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80213040: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2e80213050: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19376==ABORTING
```

It appears that the fixes for #25200 were not completely successful.

**Comment by kpedro88** [comment]
attn: @dildick @tahuang1991

**Comment by tahuang1991** [comment]
I am looking into it

**Comment by kpedro88** [comment]
@rekovic please sign

**Comment by smuzaffar** [comment]
this has been fixed
