### ISSUE TITLE
Random failures in CondTools/SiStrip O2O unit test

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26388]
We have observed recently non systematic failures in the unit test SiStripDAQ_O2O_test 👍 

```
[2019-04-03 06:00:36,014] INFO: Running O2O SiStripO2OBadStrip on machine [b6w03n0511.cern.ch]
[2019-04-03 06:00:36,014] INFO: Running O2O in /pool/condor/dir_18525/jenkins/workspace/ib-run-qa/CMSSW_10_6_X_2019-04-02-2300/308698/SiStripO2OBadStrip
[2019-04-03 06:00:36,014] INFO: Use template config file /pool/condor/dir_18525/jenkins/workspace/ib-run-qa/CMSSW_10_6_X_2019-04-02-2300/src/CondTools/SiStrip/python/SiStripO2O_cfg_template.py
[2019-04-03 06:00:36,080] INFO: Start running O2O...
[2019-04-03 06:00:37,197] INFO: 
----- Begin Fatal Exception 03-Apr-2019 06:00:37 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named cfg_SiStripO2OBadStrip_308698.py
Exception Message:
 unknown python problem occurred.
TypeError: 'NoneType' object is not iterable

At:
  cfg_SiStripO2OBadStrip_308698.py(73): &lt;module&gt;

----- End Fatal Exception -------------------------------------------------


[2019-04-03 06:00:37,197] INFO: @@@CMSSW job return code = 90@@@
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-02-2300/bin/slc7_amd64_gcc700/SiStripDAQPopCon.py", line 181, in &lt;module&gt;
    main()
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-02-2300/bin/slc7_amd64_gcc700/SiStripDAQPopCon.py", line 174, in main
    runjob(args)
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-02-2300/bin/slc7_amd64_gcc700/SiStripDAQPopCon.py", line 89, in runjob
    raise RuntimeError('O2O job FAILED!')
RuntimeError: O2O job FAILED!
Failure running SiStripDAQPopCon.py: status 1

---&gt; test SiStripDAQ_O2O_test had ERRORS
 ```

**Comment by fabiocos** [comment]
assign db

**Comment by ggovi** [comment]
@mmusich 
Hello Marco, who can give advice on this?

**Comment by mmusich** [comment]
Ciao @ggovi
adding @ocolegro @hqucms @quinnanm to cc

**Comment by hqucms** [comment]
This line 
```python
user, _, passwd = auth.get_credentials('COND_AUTH_PATH', 'cms_omds_tunnel/cms_trk_r')
```
in https://github.com/cms-sw/cmssw/blob/master/CondTools/SiStrip/python/SiStripO2O_cfg_template.py#L29 is probably the only one that can cause the type of error like `TypeError: 'NoneType' object is not iterable`. The error could happen if the `.netrc` file for authentication is missing, or it does not contain the entry needed (`cms_omds_tunnel/cms_trk_r`). 

As a proof, 

```
In [1]: import CondCore.Utilities.credentials as auth

In [2]: user, _, passwd = auth.get_credentials('COND_AUTH_PATH', 'cms_omds_tunnel/cms_trk_r')

In [3]: user, _, passwd = auth.get_credentials('COND_AUTH_PATH', 'cms_omds_tunnel/cms_trk_r0000')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-98c3c6e08389> in <module>()
----> 1 user, _, passwd = auth.get_credentials('COND_AUTH_PATH', 'cms_omds_tunnel/cms_trk_r0000')

TypeError: 'NoneType' object is not iterable

```

**Comment by mmusich** [comment]
> The error could happen if the .netrc file for authentication is missing, or it does not contain the entry needed (cms_omds_tunnel/cms_trk_r).

this looks like something for @smuzaffar ?

**Comment by smuzaffar** [comment]
@hqucms thanks for the hint. Indeed the .netrc file on afs was missing the entry. This is now fixed. We started to see these errors as now we run unit tests on HTCondor and there cmsbuild home directory was missing this file.

**Comment by mmusich** [comment]
>  This is now fixed.

If it is so, can this issue be closed?

**Comment by fabiocos** [comment]
@mmusich @hqucms thanks
