### ISSUE TITLE
Pyquen workflow failing in CLANG IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#28065]
We noticed that since we moved to GCC8 then few Pyquen workflows in CLANG IB are failing. Running one of these workflows locally I get this stack trace

```
 #3  0x00007fb98b16624f in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_CLANG_X_2019-09-23-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007fb990ce9866 in __memcpy_ssse3_back () from /lib64/libc.so.6
#6  0x00007fb989118c1c in _gfortran_concat_string (destlen=<optimized out>, dest=<optimized out>, len1=3544668429585743873, s1=<optimized out>, len2=1, s2=0x7fb9732abdba " ") at ../../../libgfortran/intrinsics/string_intrinsics_inc.c:139
#7  0x00007fb973128759 in pyinit (frame=<error reading variable: value requires 167911 bytes, which is more than max-value-size>, beam=<error reading variable: value requires 167971 bytes, which is more than max-value-size>, target=<error reading variable: value requires 746178688 bytes, which is more than max-value-size>, win=2760, _frame=3, _beam=1, _target=3544668429585743873) at pyinit.f:157
#8  0x00007fb9735091e6 in call_pyinit (frame=0x3131312800000001 <error: Cannot access memory at address 0x3131312800000001>, beam=0x3131312800000001 <error: Cannot access memory at address 0x3131312800000001>, target=0x3131312800000001 <error: Cannot access memory at address 0x3131312800000001>, win=2760) at /build/muz/w/slc7_amd64_gcc820/external/hepmc/2.06.07-pafccj/include/HepMC/PythiaWrapper6_4.h:262
#9  gen::PyquenHadronizer::initializeForInternalPartons (this=0x7fb97ae6b6a8) at src/GeneratorInterface/PyquenInterface/src/PyquenHadronizer.cc:210
#10 0x00007fb973532c4e in edm::GeneratorFilter<gen::PyquenHadronizer, gen::ExternalDecayDriver>::beginLuminosityBlockProduce (this=0x7fb97ae6b600, lumi=..., es=...) at /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_CLANG_X_2019-09-23-2300/src/GeneratorInterface/Core/interface/GeneratorFilter.h:255
#11 0x00007fb9937b89a4 in edm::one::EDFilterBase::doBeginLuminosityBlock(edm::LuminosityBlockPrincipal const&, edm::EventSetupImpl const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_CLANG_X_2019-09-23-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#12 0x00007fb9936d8d3d in edm::WorkerT<edm::one::EDFilterBase>::implDoBegin(edm::LuminosityBlockPrincipal const&, edm::EventSetupImpl const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_CLANG_X_2019-09-23-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
```

**Comment by fabiocos** [comment]
assign generator

**Comment by fabiocos** [comment]
assign generators

**Comment by qliphy** [comment]
adding @SiewYan

**Comment by mkirsano** [comment]
Add @wouf

**Comment by smuzaffar** [comment]
this has been fixed https://github.com/cms-sw/cmsdist/commit/e6eb35485a76ef6e6b061d1447003507b0d0cc4d
