### ISSUE TITLE
Prevent adding e.g. interegers to Schedule

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28179]
It is possible to add e.g. integer to a `cms.Schedule` by
```python
import FWCore.ParameterSet.Config as cms
p = cms.Process("foo") 
p.a = cms.EDProducer("Foo") 
p.p = cms.Path(p.a)
p.s = cms.Schedule(p.p)
p.s += [3]
```
after which the `Schedule` is in a weird state
```python
print(p.s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../CMSSW_11_0_0_pre10/python/FWCore/ParameterSet/SequenceTypes.py", line 693, in __str__
    return self.dumpPython() 
  File  ".../CMSSW_11_0_0_pre10/python/FWCore/ParameterSet/SequenceTypes.py", line 669, in dumpPython
    pathNames = ['process.'+p.label_() for p in self]
AttributeError: 'int' object has no attribute 'label_'
```

We should find a way to prevent adding unsupported objects into `Schedule` (or `FWCore.ParameterSet.Mixins._ValidatingListBase`).

**Comment by makortel** [comment]
assign core
