### ISSUE TITLE
Problem with JetCorrectorParameters::Record::operator<

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28283]
The address sanitizer found a problem while calling `std::sort` on the `vector<JetCorrectorParameters::Record>`:

From https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_0_ASAN_X_2019-10-25-2300/addOnTests/logs/cmsDriver-hlt_mc_Fake_cmsRun__cvmfs_cms-ib.cern.ch_nweek-02599_slc7_amd64_gcc820_cms_cmssw_CMSSW_11_0_ASAN_X_2019-10-25-2300_src_HLTrigger_Configuration_test_OnLine_HLT_Fak.log#/
```
26-Oct-2019 07:30:55 CEST  Successfully opened file file:RelVal_Raw_Fake_MC.root
=================================================================
==13433==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000b0de74 at pc 0x2b2a59a04b1a bp 0x2b2a604c2660 sp 0x2b2a604c2658
READ of size 4 at 0x602000b0de74 thread T4
    #0 0x2b2a59a04b19 in void std::__move_median_to_first&lt;__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__ops::_Iter_less_iter&gt;(__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__ops::_Iter_less_iter) (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsJetMETObjects.so+0x1dab19)
    #1 0x2b2a59a0513b in void std::__introsort_loop&lt;__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, long, __gnu_cxx::__ops::_Iter_less_iter&gt;(__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, long, __gnu_cxx::__ops::_Iter_less_iter) (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsJetMETObjects.so+0x1db13b)
    #2 0x2b2a599ee764 in JetCorrectorParameters::init() (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsJetMETObjects.so+0x1c4764)
    #3 0x2b2a596ba225 in DataProxy&lt;JetCorrectionsRecord, JetCorrectorParametersCollection, JetCorrectorParametersInitializeTransients&gt;::make(JetCorrectionsRecord const&amp, edm::eventsetup::DataKey const&amp) (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/pluginCondCoreJetMETPlugins.so+0x108225)
...

0x602000b0de74 is located 0 bytes to the right of 4-byte region [0x602000b0de70,0x602000b0de74)
allocated by thread T4 here:
    #0 0x2b2a37fa9d90 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:90
    #1 0x2b2a46ba2f48 in std::vector&lt;float, std::allocator&lt;float&gt; &gt;::reserve(unsigned long) (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsL1TObjects.so+0x501f48)
    #2 0x2b2a46d803ed in boost::archive::detail::iserializer&lt;eos::portable_iarchive, std::vector&lt;float, std::allocator&lt;float&gt; &gt; &gt;::load_object_data(boost::archive::detail::basic_iarchive&amp, void*, unsigned int) const (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsL1TObjects.so+0x6df3ed)
    #3 0x2b2a485d8aba in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&amp) (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/external/slc7_amd64_gcc820/lib/libboost_serialization.so.1.67.0+0x16aba)
...

SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/nweek-02599/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_ASAN_X_2019-10-25-2300/lib/slc7_amd64_gcc820/libCondFormatsJetMETObjects.so+0x1dab19) in void std::__move_median_to_first&lt;__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__ops::_Iter_less_iter&gt;(__gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::allocator&lt;JetCorrectorParameters::Record&gt; &gt; &gt;, __gnu_cxx::__normal_iterator&lt;JetCorrectorParameters::Record*, std::vector&lt;JetCorrectorParameters::Record, std::a
Shadow bytes around the buggy address:
  0x0c0480159b70: fa fa 00 04 fa fa 04 fa fa fa 04 fa fa fa 00 04
  0x0c0480159b80: fa fa 00 04 fa fa 04 fa fa fa 04 fa fa fa 00 04
  0x0c0480159b90: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480159ba0: fa fa 04 fa fa fa 04 fa fa fa 00 04 fa fa 04 fa
  0x0c0480159bb0: fa fa 00 04 fa fa 04 fa fa fa 04 fa fa fa 00 04
=&gt;0x0c0480159bc0: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa[04]fa
  0x0c0480159bd0: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480159be0: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480159bf0: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480159c00: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0480159c10: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13433==ABORTING
```

His happened while running the addOnTest hlt_mc_Fake for step 2. It looks to me like the comparison function:

https://github.com/cms-sw/cmssw/blob/master/CondFormats/JetMETObjects/interface/JetCorrectorParameters.h#L81-L91

assume the member data `Record::mMin` is at least size 3, but that is not true in this case where the size appears to be 1.

It is unclear if the problem is with the conditions object stored in the DB or with the comparison function.

**Comment by Dr15Jones** [comment]
assign analysis, db

**Comment by tvami** [comment]
@panwarlsweet here is another ASAN issue, please pass this info to JETMET

**Comment by kirschen** [comment]
Hi @tvami , not sure I got what ASAN stands for, but good to look into it. @laurenhay - would you mind taking a look?

**Comment by tvami** [comment]
> Hi @tvami , not sure I got what ASAN stands for

Address Sanitizer, I guess the correct spelling would be ASan :)

**Comment by santocch** [comment]
+1
