### ISSUE TITLE
SiPixelPhase1Summary seg violation in wf 150.0

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29462]
We are getting segmentation violation in wf 150.0, step4, since CMSSW_11_1_X_2020-04-10-1100 ie. after having integrated #29355
`cmsDriver.py step4  --conditions auto:phase1_2018_realistic -s HARVESTING:validationHarvesting+dqmHarvestingFakeHLT --scenario HeavyIons --filetype DQM -n 2 --era Run2_2018 --mc   --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --prefix '/data/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 9000 '  --filein file:step3_inDQM.root --fileout file:step4.root  --suffix "-j JobReport4.xml "  > step4_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018+RECOHI2018+HARVESTHI2018.log  2>&1`

```
A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Fri Apr 10 14:22:52 CEST 2020
Thread 2 (Thread 0x2b1d4c826700 (LWP 6534)):
#0  0x00002b1d357b7199 in waitpid () from /lib64/libpthread.so.0
#1  0x00002b1d3cdbbb27 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002b1d3cdbc5ea in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00002b1d353c2ccf in execute_native_thread_routine () at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#4  0x00002b1d357afe65 in start_thread () from /lib64/libpthread.so.0
#5  0x00002b1d35ac288d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x2b1d377e6180 (LWP 6454)):
#0  0x00002b1d35ab7bed in poll () from /lib64/libc.so.6
#1  0x00002b1d3cdbbf8f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002b1d3cdbc6cc in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00002b1d3cdbd5a9 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  &lt;signal handler called&gt;
#5  0x00002b1d59c4893a in SiPixelPhase1Summary::fillSummaries(dqm::implementation::IBooker&amp, dqm::implementation::IGetter&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-04-10-1100/lib/slc7_amd64_gcc820/pluginDQMSiPixelPhase1Summary.so
#6  0x00002b1d59c4f2a0 in virtual thunk to DQMEDHarvester::endJob() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-04-10-1100/lib/slc7_amd64_gcc820/pluginDQMSiPixelPhase1Summary.so
#7  0x00002b1d332a756e in edm::Worker::endJob() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#8  0x00002b1d33233500 in edm::WorkerManager::endJob(edm::ExceptionCollector&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#9  0x00002b1d3326ad15 in edm::Schedule::endJob(edm::ExceptionCollector&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#10 0x00002b1d33244610 in edm::EventProcessor::endJob() () from /cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#11 0x0000000000412dde in main::{lambda()#1}::operator()() const ()
#12 0x0000000000411372 in main ()

Current Modules:

Module: none (crashed)

A fatal system signal has occurred: segmentation violation
```

**Comment by silviodonato** [comment]
assign dqm

**Comment by silviodonato** [comment]
@dmeuser

**Comment by boudoul** [comment]
I guess this is what is already reported here  https://github.com/cms-sw/cmssw/issues/29460 and getting solved here : https://github.com/cms-sw/cmssw/pull/29461  . Am I wrong ?

**Comment by silviodonato** [comment]
duplicate of https://github.com/cms-sw/cmssw/issues/29460, sorry for the spam

**Comment by mmusich** [comment]
@silviodonato this is a duplicate of https://github.com/cms-sw/cmssw/issues/29460 (already addressed) please close!
