### ISSUE TITLE
cms.Process.process cannot set the process name

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#29507]
The python `cms.Process` object defines the property `process` to get and set the process name.

Getting the name works:
```python
>>> process = cms.Process('TEST')
>>> process.process
'TEST'
```

Setting it doesn't work:
```python
>>> process.process = 'TEST2'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre6/python/FWCore/ParameterSet/Config.py", line 392, in __setattr__
    +"an instance of "+str(type(value))+" will not work - requested label is "+name)
TypeError: can only assign labels to an object that inherits from '_ConfigureComponent'
an instance of <type 'str'> will not work - requested label is process
```

Setting the name directly or via the setter does work:
```python
>>> process._Process__name = 'TEST3'
>>> process.process
'TEST3'
```
```python
>>> process.setName_('TEST4')
>>> process.process
'TEST4'
```

**Comment by fwyzard** [comment]
assign core
