### ISSUE TITLE
Improvements of ReduceMantissaToNbitsRounding

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29564]
`ReduceMantissaToNbitsRounding` https://github.com/cms-sw/cmssw/commits/master/DataFormats/Math/interface/libminifloat.h was added by @arizzi and  @gpetruc with #18739 #20367.
@VinInn suggested a re-implementation of `ReduceMantissaToNbitsRounding` (see #29513 #29518).

**Comment by silviodonato** [comment]
assign reco

**Comment by smuzaffar** [comment]
In UBSAN IBs we have [a] runtime error about `shift exponent -1`. This happens when `ReduceMantissaToNbitsRounding` is called with `bits=23` causing `test(1 << (shift - 1))` to have a -ve shift exponent.  I see that this issue was opened to look in to the improved version of `ReduceMantissaToNbitsRounding`  ? Are there any plans to replace this function? If not then should I open a PR to suppress this runtime error? 

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_amd64_gcc12/CMSSW_14_2_UBSAN_X_2024-10-25-2300/pyRelValMatrixLogs/run/139.005_AlCaPhiSym2021/step3_AlCaPhiSym2021.log
```
src/DataFormats/Math/interface/libminifloat.h:61:78: runtime error: shift exponent -1 is negative
    #0 0x7fc173925d59 in MiniFloatConverter::ReduceMantissaToNbitsRounding::ReduceMantissaToNbitsRounding(int) src/DataFormats/Math/interface/libminifloat.h:61
    #1 0x7fc1739cfe6d in void MiniFloatConverter::reduceMantissaToNbitsRounding<__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > >(int, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >) src/DataFormats/Math/interface/libminifloat.h:96
    #2 0x7fc1739cfe6d in void nanoaod::flatTableHelper::MaybeMantissaReduce<float>::bulk<edm::Span<__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > > >(edm::Span<__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > > >&&) const src/DataFormats/NanoAOD/interface/FlatTable.h:33
    #3 0x7fc1739cfe6d in void nanoaod::FlatTable::addColumn<float, std::vector<float, std::allocator<float> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<float, std::allocator<float> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) src/DataFormats/NanoAOD/interface/FlatTable.h:127
    #4 0x7fc1739d4fb8 in FuncVariable<EcalPhiSymRecHit, StringObjectFunction<EcalPhiSymRecHit, false>, float>::fill(std::vector<EcalPhiSymRecHit const*, std::allocator<EcalPhiSymRecHit const*> >&, nanoaod::FlatTable&) const src/PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:68
    #5 0x7fc1739b40b1 in RunSimpleFlatTableProducer<EcalPhiSymRecHit, std::vector<EcalPhiSymRecHit, std::allocator<EcalPhiSymRecHit> > >::fillTable(edm::Run const&, edm::Handle<std::vector<EcalPhiSymRecHit, std::allocator<EcalPhiSymRecHit> > > const&) const src/PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:862
    #6 0x7fc1739e63f4 in SimpleFlatTableProducerBaseRun<EcalPhiSymRecHit, std::vector<EcalPhiSymRecHit, std::allocator<EcalPhiSymRecHit> > >::endRunProduce(edm::Run&, edm::EventSetup const&) src/PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:799

```

**Comment by smuzaffar** [comment]
I opened  https://github.com/cms-sw/cmssw/pull/46535 to suppress this runtime error mentioned in https://github.com/cms-sw/cmssw/issues/29564#issuecomment-2441870354

**Comment by smuzaffar** [comment]
closing it as https://github.com/cms-sw/cmssw/pull/46535 has been merged and it has fixed this issue
