### ISSUE TITLE
pythia8 version 302 is causing seg faults in WF 1361.181

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#30234]
Right after the switch to pythia8 version 302 we see segmentation faults in WF 1361.181. This workflow is using the Pythia8ConcurrentHadronizerFilter module and is using concurrent LuminosityBlocks. The segmentation fault appears to be happening right when the LuminosityBlock boundary is crossed.

**Comment by Dr15Jones** [comment]
assign generator

**Comment by Dr15Jones** [comment]
An example traceback from the crash is below
```
Begin processing the 6th record. Run 1, Event 6, LumiSection 2 on stream 0 at 11-Jun-2020 16:15:51.342 CEST


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thu Jun 11 16:15:51 CEST 2020
Thread 6 (Thread 0x2baa03800700 (LWP 7762)):
#0  0x00002ba9d922b85d in nanosleep () from /lib64/libc.so.6
#1  0x00002ba9d922b6f4 in sleep () from /lib64/libc.so.6
#2  0x00002ba9de52a890 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  &lt;signal handler called&gt;
#4  0x00002ba9d6a67da0 in edm::WorkerManager::resetAll() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#5  0x00002ba9d6985667 in edm::FunctorTask&lt;void edm::StreamSchedule::processOneStreamAsync&lt;edm::OccurrenceTraits&lt;edm::LuminosityBlockPrincipal, (edm::BranchActionType)1&gt; &gt;(edm::WaitingTaskHolder, edm::OccurrenceTraits&lt;edm::LuminosityBlockPrincipal, (edm::BranchActionType)1&gt;::MyPrincipal&amp, edm::EventSetupImpl const&amp, edm::ServiceToken const&amp, bool)::{lambda()#2}&gt;::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#6  0x00002ba9d81c125d in tbb::internal::custom_scheduler&lt;tbb::internal::IntelSchedulerTraits&gt;::process_bypass_loop (this=this@entry=0x2ba9dbae7e00, context_guard=..., t=t@entry=0x2ba9dbb1a540, isolation=isolation@entry=0) at ../../src/tbb/custom_scheduler.h:388
[cut]

Thread 5 (Thread 0x2baa02801700 (LWP 7759)):
#0  0x00002ba9d922b85d in nanosleep () from /lib64/libc.so.6
#1  0x00002ba9d922b6f4 in sleep () from /lib64/libc.so.6
#2  0x00002ba9de52a890 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  &lt;signal handler called&gt;
#4  0x00002ba9d92a4e21 in __strcmp_sse42 () from /lib64/libc.so.6
#5  0x00002ba9d8b3e600 in std::type_info::operator== (this=0x2ba9d8c21738 &lt;typeinfo for std::ctype&lt;char&gt;&gt;, __arg=...) at ../../../../libstdc++-v3/libsupc++/tinfo.h:171
#6  __cxxabiv1::__vmi_class_type_info::__do_dyncast (this=0x2ba9d8c21738 &lt;typeinfo for std::ctype&lt;char&gt;&gt;, src2dst=0, access_path=__cxxabiv1::__class_type_info::__contained_public, dst_type=0x2ba9d8c21738 &lt;typeinfo for std::ctype&lt;char&gt;&gt;, obj_ptr=0x2ba9d8c2c0c0 &lt;(anonymous namespace)::ctype_c&gt;, src_type=0x2ba9d8c20660 &lt;typeinfo for std::locale::facet&gt;, src_ptr=0x2ba9d8c2c0c0 &lt;(anonymous namespace)::ctype_c&gt;, result=...) at ../../../../libstdc++-v3/libsupc++/vmi_class_type_info.cc:91
#7  0x00002ba9d8b3b536 in __cxxabiv1::__dynamic_cast (src_ptr=0x2ba9d8c2c0c0 &lt;(anonymous namespace)::ctype_c&gt;, src_type=0x2ba9d8c20660 &lt;typeinfo for std::locale::facet&gt;, dst_type=0x2ba9d8c21738 &lt;typeinfo for std::ctype&lt;char&gt;&gt;, src2dst=src2dst@entry=0) at ../../../../libstdc++-v3/libsupc++/dyncast.cc:71
#8  0x00002ba9d8baa7c0 in std::has_facet&lt;std::ctype&lt;char&gt; &gt; (__loc=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/locale_classes.tcc:104
#9  0x00002ba9d8b9e2f4 in std::basic_ios&lt;char, std::char_traits&lt;char&gt; &gt;::_M_cache_locale (this=this@entry=0x2baa027f8f68, __loc=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_ios.tcc:157
#10 0x00002ba9d8b9e720 in std::basic_ios&lt;char, std::char_traits&lt;char&gt; &gt;::init (this=0x2baa027f8f68, __sb=0x2baa027f8f00) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_ios.tcc:126
#11 0x00002ba9f90a10ad in Pythia8::Settings::init(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#12 0x00002ba9f902aeb8 in Pythia8::Pythia::Pythia(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#13 0x00002ba9f82255e8 in gen::Py8InterfaceBase::readSettings(int) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/libGeneratorInterfacePythia8Interface.so
#14 0x00002ba9f7956c2c in edm::ConcurrentHadronizerFilter&lt;Pythia8Hadronizer, gen::ConcurrentExternalDecayDriver&gt;::initLumi(edm::gen::StreamCache&lt;Pythia8Hadronizer, gen::ConcurrentExternalDecayDriver&gt;*, edm::LuminosityBlock const&amp, edm::EventSetup const&amp) const () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginGeneratorInterfacePythia8Filters.so
#15 0x00002ba9d6a7d0d0 in edm::global::EDFilterBase::doStreamBeginLuminosityBlock(edm::StreamID, edm::LuminosityBlockPrincipal const&amp, edm::EventSetupImpl const&amp, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/libFWCoreFramework.so
[cut]

Thread 4 (Thread 0x2baa01e00700 (LWP 7758)):
#0  0x00002ba9d922b85d in nanosleep () from /lib64/libc.so.6
#1  0x00002ba9d922b6f4 in sleep () from /lib64/libc.so.6
#2  0x00002ba9de52a890 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  &lt;signal handler called&gt;
#4  0x00002ba9d65fc9b0 in __tls_get_addr () from /lib64/ld-linux-x86-64.so.2
#5  0x00002ba9dec1092f in CLHEP::(anonymous namespace)::theDefaults() () at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/external/clhep/2.4.1.3-khbdan/clhep-2.4.1.3/Random/src/Random.cc:157
#6  0x00002ba9dec10e19 in CLHEP::HepRandom::getTheEngine () at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/external/clhep/2.4.1.3-khbdan/clhep-2.4.1.3/Random/src/Random.cc:268
#7  0x00002ba9fcddbf81 in G4UniversalFluctuation::SampleFluctuations(G4MaterialCutsCouple const*, G4DynamicParticle const*, double, double, double) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#8  0x00002ba9fce068c1 in G4VEnergyLossProcess::AlongStepDoIt(G4Track const&amp, G4Step const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#9  0x00002ba9fd1be6b7 in G4SteppingManager::InvokeAlongStepDoItProcs() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#10 0x00002ba9fd1bc96f in G4SteppingManager::Stepping() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#11 0x00002ba9fcc60efa in G4TrackingManager::ProcessOneTrack(G4Track*) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#12 0x00002ba9fc9079a2 in G4EventManager::DoProcessing(G4Event*) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#13 0x00002ba9fc5fd040 in RunManagerMTWorker::produce(edm::Event const&amp, edm::EventSetup const&amp, RunManagerMT&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
#14 0x00002ba9fc5d5e97 in OscarMTProducer::produce(edm::Event&amp, edm::EventSetup const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
[cut]

Thread 3 (Thread 0x2ba9fe90c700 (LWP 7582)):
#0  0x00002ba9d8f55a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00002ba9d8b6062c in __gthread_cond_wait (__mutex=&lt;optimized out&gt;, __cond=&lt;optimized out&gt;) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=&lt;optimized out&gt;, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00002ba9fc5e9de3 in OscarMTMasterThread::OscarMTMasterThread(edm::ParameterSet const&amp)::{lambda()#1}::operator()() const [clone .isra.88] () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/biglib/slc7_amd64_gcc820/pluginSimulation.so
[cut]

Thread 2 (Thread 0x2ba9ec2bb700 (LWP 4919)):
#0  0x00002ba9d8f591d9 in waitpid () from /lib64/libpthread.so.0
#1  0x00002ba9de52aa47 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002ba9de52b50a in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
[cut]

Thread 1 (Thread 0x2ba9daf86a40 (LWP 31806)):
#0  0x00002ba9d9259c3d in poll () from /lib64/libc.so.6
#1  0x00002ba9de52aeaf in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002ba9de52b5ec in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00002ba9de52c4c9 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  &lt;signal handler called&gt;
#5  0x00002ba9f8fdcb7c in Pythia8::PhysicsBase::beginEvent() [clone .localalias.28] () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#6  0x00002ba9f9014dac in Pythia8::Pythia::beginEvent() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#7  0x00002ba9f901d9d9 in Pythia8::Pythia::next() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#8  0x00002ba9f792486b in Pythia8Hadronizer::hadronize() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginGeneratorInterfacePythia8Filters.so
#9  0x00002ba9f795eedd in edm::ConcurrentHadronizerFilter&lt;Pythia8Hadronizer, gen::ConcurrentExternalDecayDriver&gt;::filter(edm::StreamID, edm::Event&amp, edm::EventSetup const&amp) const () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginGeneratorInterfacePythia8Filters.so
[cut]

Current Modules:

Module: Pythia8ConcurrentHadronizerFilter:generator (crashed)
Module: none
Module: Pythia8ConcurrentHadronizerFilter:generator
Module: OscarMTProducer:g4SimHits

A fatal system signal has occurred: segmentation violation
```

**Comment by Dr15Jones** [comment]
From anecdotal evidence, it appears that the crash happens when one Pythia8 instance is starting to process the first event in the next LuminosityBlock while a different Pythia8 instance is re-initializing itself at the new LuminosityBlock transition.

**Comment by Dr15Jones** [comment]
assign generators

**Comment by Dr15Jones** [comment]
Searching more crash records, I seem to have found a case where 3 of the streams were still processing events in the 1st LuminosityBlock and the crash happened when Pythia8 tried to process the 1st event in the 2nd LuminosityBlock.

**Comment by silviodonato** [comment]
@mkirsano we are getting this error since #29995 was merged

**Comment by mkirsano** [comment]
I checked that it does not crash in runs with several lumi blocks, but in a single thread.
How can I look into this?

**Comment by Dr15Jones** [comment]
Either
```
runTheMatrix.py -l 1361.181 -t 4
```

or (which is what the above does)
```
cmsDriver.py Configuration/Generator/python/GGHZZ4L_JHUGen_Pow_NNPDF30_LHE_13TeV_cfi.py --conditions auto:phase1_2018_realistic -n 10 --customise_commands "process.source.numberEventsInLuminosityBlock=cms.untracked.uint32(5)" --era Run2_2018 --relval 9000,50 -s LHE,GEN,SIM --nStreams 4 --datatier GEN-SIM,LHE --beamspot Realistic25ns13TeVEarly2018Collision --eventcontent FEVTDEBUG,LHE --geometry DB:Extended --nConcurrentLumis 2 --fileout file:step1.root --nThreads 4
```

**Comment by Dr15Jones** [comment]
I then took the _cfg.py file generated from the above and edited it to comment out the multi-thread use
```python
#Setup FWK for multithreaded                                                                                                                                                                                                                
#process.options.numberOfThreads=cms.untracked.uint32(4)                                                                                                                                                                                    
#process.options.numberOfStreams=cms.untracked.uint32(4)                                                                                                                                                                                    
#process.options.numberOfConcurrentLuminosityBlocks=cms.untracked.uint32(2)                                                                                                                                                                 ```
and it did seg fault after crossing the LuminosityBlock boundary. Therefore the problem is not related to multi-threading but related to resetting Pythia 8 a the LuminosityBlock boundary.

**Comment by mkirsano** [comment]
I see now the general problem: it crashes at the lumi block boundary if a UserHook is used for pythia8. There were changes in this sector, studying further

**Comment by makortel** [comment]
> Can we close this issue?

I think so. Preferably @cms-sw/generators-l2 would sign the issue (in principle @Dr15Jones or those with permissions could also directly close it).

**Comment by agrohsje** [comment]
+generators
