### ISSUE TITLE
Is Eigen from within TensorFlow spawning extra threads?

### ISSUE THREAD

**Issue by dpiparo** [cms-sw/cmssw#30747]
While debugging an unrelated issue I stumbled on what may look like a potential overcommit of grid nodes. It seems that TensorFlow relies on Eigen that spawns a thread pool of its own. E.g. see these stacktraces [1]. Can this be verified and, if necessary, fixed?
@smuzaffar @makortel for your info.

[1]
```
 (gdb) thr 12
[Switching to thread 12 (Thread 0x7fffa25d2700 (LWP 30971))]
#0  0x00007ffff51a6a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff51a6a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffff578962c in _gthread_cond_wait (_mutex=<optimized out>, __cond=<optimized out>)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fffb3a4aa3c in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#4  0x00007fffb3a47963 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#5  0x00007ffff578ed2f in execute_native_thread_routine () at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007ffff51a2ea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff4ecb8dd in clone () from /lib64/libc.so.6
(gdb) thr 11
[Switching to thread 11 (Thread 0x7fffa2dd3700 (LWP 30970))]
#0  0x00007ffff51a6a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff51a6a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffff578962c in _gthread_cond_wait (_mutex=<optimized out>, __cond=<optimized out>)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fffb3a4aa3c in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#4  0x00007fffb3a47963 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#5  0x00007ffff578ed2f in execute_native_thread_routine () at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007ffff51a2ea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff4ecb8dd in clone () from /lib64/libc.so.6
(gdb) 
#0  0x00007ffff51a6a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffff578962c in _gthread_cond_wait (_mutex=<optimized out>, __cond=<optimized out>)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre7-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre7-build/BUILD/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/gcc-8.2.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fffb3a4aa3c in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#4  0x00007fffb3a47963 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_p3_ROOT618/external/slc7_amd64_gcc820/lib/libtensorflow_framework.so.2
#5  0x00007ffff578ed2f in execute_native_thread_routine () at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007ffff51a2ea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff4ecb8dd in clone () from /lib64/libc.so.6
```

**Comment by makortel** [comment]
assign core

**Comment by Dr15Jones** [comment]
@dpiparo this is a known behavior we've been unable to stop. On the plus side, as far as we can tell the threads are never actually used for processing.

**Comment by dpiparo** [comment]
thanks @Dr15Jones , I thought it was worth checking. If the threads are not spinning, fine. I understand from Marcel that in TF2.1 this could be avoided: let's see... For me it's fine to close the issue.
