### ISSUE TITLE
Unknown parameter name ClusterShapeCacheSrc specified while calling Modifier

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#30766]
We have three failing workflows (see https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_2/2020-07-16-1100?selectedArchs=slc7_amd64_gcc820&selectedFlavors=X&selectedStatus=failed). The message is
```
RAW2DIGI,RECO:reconstruction_trackingOnly,VALIDATION:@trackingOnlyValidation,DQM:@trackingOnlyDQM
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
entry file:step2.root
Step: RAW2DIGI Spec: 
Step: RECO Spec: ['reconstruction_trackingOnly']
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in &lt;module&gt;
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/Applications/ConfigBuilder.py", line 2119, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/Applications/ConfigBuilder.py", line 759, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = '+'.join(stepSpec))
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/Applications/ConfigBuilder.py", line 1623, in prepare_RECO
    self.loadDefaultOrSpecifiedCFF(sequence,self.RECODefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/Applications/ConfigBuilder.py", line 1195, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(defaultCFF)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/Applications/ConfigBuilder.py", line 325, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Config.py", line 683, in load
    module = __import__(moduleName)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/Configuration/StandardSequences/Reconstruction_cff.py", line 9, in &lt;module&gt;
    from RecoTracker.Configuration.RecoTracker_cff import *
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/RecoTracker/Configuration/RecoTracker_cff.py", line 5, in &lt;module&gt;
    from RecoTracker.IterativeTracking.iterativeTk_cff import *
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/RecoTracker/IterativeTracking/iterativeTk_cff.py", line 10, in &lt;module&gt;
    from RecoTracker.IterativeTracking.PixelLessStep_cff import *
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/RecoTracker/IterativeTracking/PixelLessStep_cff.py", line 182, in &lt;module&gt;
    ClusterShapeCacheSrc      = 'siPixelClusterShapeCache' # not really needed here since FilterPixelHits=False
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Config.py", line 1616, in toModify
    Modifier._toModify(obj,func,**kw)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Config.py", line 1623, in _toModify
    temp(obj)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Config.py", line 1517, in __call__
    _modifyParametersFromDict(params, self.__args, self._raiseUnknownKey)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Mixins.py", line 711, in _modifyParametersFromDict
    ("%s.%s" if isinstance(key, str) else "%s[%s]")%(keyDepth,key))
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Mixins.py", line 739, in _modifyParametersFromDict
    errorRaiser(key)
  File "/cvmfs/cms-ib.cern.ch/nweek-02637/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-16-1100/python/FWCore/ParameterSet/Config.py", line 1526, in _raiseUnknownKey
    raise KeyError("Unknown parameter name "+key+" specified while calling Modifier")
KeyError: 'Unknown parameter name ClusterShapeCacheSrc specified while calling Modifier'
```

I suspect it is related to https://github.com/cms-sw/cmssw/pull/30671 which applies changes to `RecoTracker/IterativeTracking/python/PixelLessStep_cff.py`. 
@jeongeun could you check and eventually provide a fix? Thanks.

**Comment by silviodonato** [comment]
assign reconstruction

**Comment by silviodonato** [comment]
Fixed https://github.com/cms-sw/cmssw/pull/30767
