### ISSUE TITLE
ASAN problem with L1FPGATrackProducer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#30913]
The L1FPGATrackProducer is seeing a heap-buffer-overflow

```
==19775==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60601e4a9ca0 at pc 0x2b05069596be bp 0x2b050475b400 sp 0x2b050475b3f8
READ of size 8 at 0x60601e4a9ca0 thread T9
    #0 0x2b05069596bd in trklet::FitTrack::execute() (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0xf76bd)
    #1 0x2b0506adeb67 in trklet::Sector::executeFT() (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0x27cb67)
    #2 0x2b0506bfd7cb in trklet::TrackletEventProcessor::event(trklet::SLHCEvent&amp) (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0x39b7cb)
    #3 0x2b05067efbb8 in L1FPGATrackProducer::produce(edm::Event&amp, edm::EventSetup const&amp) (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/pluginTrackFindingTrackletPlugins.so+0x37bb8)
[cut for clarity]   
 
0x60601e4a9ca0 is located 0 bytes to the right of 64-byte region [0x60601e4a9c60,0x60601e4a9ca0)
allocated by thread T9 here:
    #0 0x2b04c6f1cdb0 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:90
    #1 0x2b050695106c in trklet::FitTrack::orderedMatches(std::vector&lt;trklet::FullMatchMemory*, std::allocator&lt;trklet::FullMatchMemory*&gt; &gt;&amp) (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0xef06c)
    #2 0x2b05069523b2 in trklet::FitTrack::execute() (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0xf03b2)
    #3 0x2b0506adeb67 in trklet::Sector::executeFT() (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0x27cb67)
    #4 0x2b0506bfd7cb in trklet::TrackletEventProcessor::event(trklet::SLHCEvent&amp) (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0x39b7cb)
    #5 0x2b05067efbb8 in L1FPGATrackProducer::produce(edm::Event&amp, edm::EventSetup const&amp) (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/pluginTrackFindingTrackletPlugins.so+0x37bb8)
[cut]

SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/nweek-02638/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ASAN_X_2020-07-24-2300/lib/slc7_amd64_gcc820/libL1TriggerTrackFindingTracklet.so+0xf76bd) in trklet::FitTrack::execute()
Shadow bytes around the buggy address:
  0x0c0c83c8d340: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c0c83c8d350: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
  0x0c0c83c8d360: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0c83c8d370: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c0c83c8d380: fa fa fa fa fa fa fa fa fa fa fa fa 00 00 00 00
=&gt;0x0c0c83c8d390: 00 00 00 00[fa]fa fa fa fd fd fd fd fd fd fd fd
  0x0c0c83c8d3a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c83c8d3b0: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
  0x0c0c83c8d3c0: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0c83c8d3d0: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c0c83c8d3e0: 00 00 00 00 00 00 00 04 fa fa fa fa 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19775==ABORTING
```

**Comment by Dr15Jones** [comment]
assign l1, upgrade

**Comment by Dr15Jones** [comment]
The problem is with the order of the logic in the following `while` loops

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/FitTrack.cc#L937

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/FitTrack.cc#L949

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/FitTrack.cc#L961

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/FitTrack.cc#L973

The check against the `size` needs to be done first in order to avoid reading off the end of the container.

**Comment by Dr15Jones** [comment]
Is anyone looking into this?

**Comment by makortel** [comment]
FYI @skinnari

**Comment by makortel** [comment]
@skinnari @rekovic @benkrikler Please take a look of this issue reported by ASAN.

**Comment by skinnari** [comment]
@makortel thanks for pointing me to this! will try to fix today.

**Comment by Dr15Jones** [comment]
Any progress?

**Comment by Dr15Jones** [comment]
Any progress?

**Comment by makortel** [comment]
@skinnari Any progress?

**Comment by makortel** [comment]
@skinnari Any progress? (@cms-sw/l1-l2)

**Comment by kpedro88** [comment]
@skinnari ping

**Comment by makortel** [comment]
@skinnari Any progress? (@rekovic @benkrikler)

**Comment by makortel** [comment]
The fix #31555 has been merged a few days ago, this issue can be closed.

**Comment by kpedro88** [comment]
+upgrade

**Comment by cecilecaillol** [comment]
+l1
