### ISSUE TITLE
Unit test failure in Validation/Geometry  for DEVEL IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#30939]
The unit test `materialBudgetTrackerPlots` in Validation/Geometry fails due to py2 vs py3 issue. In DEVEL IBs , it fails [a] as https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/test/genTrackerPlots.sh#L12 starts python (i.e. python2) while cmsRun uses python3.

[a] 11.2.X DEVEL IBs 
Traceback (most recent call last):
  File "/build/muz/CMSSW_11_2_DEVEL_X_2020-07-27-2300/src/Validation/Geometry/test/runP_Tracker.py", line 10, in <module>
    from FWCore.PythonFramework.CmsRun import CmsRun
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_DEVEL_X_2020-07-27-2300/python/FWCore/PythonFramework/CmsRun.py", line 1, in <module>
    import libFWCorePythonFramework as _pf
ImportError: dynamic module does not define init function (initlibFWCorePythonFramework)

**Comment by smuzaffar** [comment]
since we moved to py3 so this is not an issue any more
