### ISSUE TITLE
Segmentation violation in 2026D62 workflow (29034.0)

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#30980]
The new workflow associated to D62  (`_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D62_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D62+RecoFullGlobal_2026D62+HARVESTFullGlobal_2026D62`) is crashing with:

```
A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thu Jul 30 06:25:20 CEST 2020
Thread 8 (Thread 0x2acc3d795700 (LWP 7722)):
#0  0x00002acbb6172c3d in poll () from /lib64/libc.so.6
#1  0x00002acbbcdd876f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002acbbcdd8eac in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00002acbbcdd9d89 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  &lt;signal handler called&gt;
#5  0x00002acbd71924cf in HGCalDDDConstants::waferInLayerTest(int, int, bool) const () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/libGeometryHGCalCommonData.so
#6  0x00002acbd6f27c8c in HGCalGeometryLoader::build(HGCalTopology const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/libGeometryHGCalGeometry.so
#7  0x00002acbd91fea4a in HGCalGeometryESProducer::produce(IdealGeometryRecord const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#8  0x00002acbd920373d in decltype ({parm#1}()) edm::convertException::wrap&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const::{lambda()#1}&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#9  0x00002acbd9203991 in edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#10 0x00002acbd9203bff in void edm::SerialTaskQueueChain::actionToRun&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#11 0x00002acbd9203c71 in edm::SerialTaskQueue::QueuedTask&lt;edm::SerialTaskQueueChain::push&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp&amp)::{lambda()#1}&gt;::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02639/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#12 0x00002acbb50babfd in tbb::internal::custom_scheduler&lt;tbb::internal::IntelSchedulerTraits&gt;::process_bypass_loop (this=this@entry=0x2acc3b653e00, context_guard=..., t=t@entry=0x2acc3b657440, isolation=isolation@entry=0) at ../../src/tbb/custom_scheduler.h:393
#13 0x00002acbb50baef5 in tbb::internal::custom_scheduler&lt;tbb::internal::IntelSchedulerTraits&gt;::local_wait_for_all (this=0x2acc3b653e00, parent=..., child=&lt;optimized out&gt;) at ../../include/tbb/task.h:1003
#14 0x00002acbb50b49ff in tbb::internal::arena::process (this=0x2acbb8bf5800, s=...) at ../../src/tbb/arena.cpp:196
#15 0x00002acbb50b33d3 in tbb::internal::market::process (this=0x2acbb8bf7580, j=...) at ../../src/tbb/market.cpp:667
#16 0x00002acbb50af7dc in tbb::internal::rml::private_worker::run (this=0x2acbb8c1af80) at ../../src/tbb/private_server.cpp:266
#17 0x00002acbb50af9e9 in tbb::internal::rml::private_worker::thread_routine (arg=&lt;optimized out&gt;) at ../../src/tbb/private_server.cpp:219
#18 0x00002acbb5e6aea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00002acbb617d8dd in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x2acc3cd94700 (LWP 7721)):

[...]


Current Modules:

Module: none (crashed)
Module: L1TCaloLayer1:simCaloStage2Layer1Digis
Module: none
Module: L1TCaloLayer1:simCaloStage2Layer1Digis
Module: none

A fatal system signal has occurred: segmentation violation
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc820/CMSSW_11_2_X_2020-07-29-2300/pyRelValMatrixLogs/run/29034.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D62_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D62+RecoFullGlobal_2026D62+HARVESTFullGlobal_2026D62/step2_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D62_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D62+RecoFullGlobal_2026D62+HARVESTFullGlobal_2026D62.log

The workflow was added with https://github.com/cms-sw/cmssw/pull/30891.
It's weird that the PR test was fine (https://github.com/cms-sw/cmssw/pull/30891#issuecomment-664507153). Perhaps the error appears only when multithreading is on.

@bsunanda

**Comment by silviodonato** [comment]
assign geometry

**Comment by silviodonato** [comment]
assign upgrade

**Comment by ianna** [comment]
@silviodonato, @kpedro88  - can we, please, fix this issue after https://github.com/cms-sw/cmssw/pull/30963 is merged?

**Comment by kpedro88** [comment]
@bsunanda please take a look

**Comment by bsunanda** [comment]
I hope #30996 will fix this error

**Comment by makortel** [comment]
#30996 was included in CMSSW_11_2_X_2020-08-03-1100, but 29034.0 still fails with
```
Thread 5 (Thread 0x2b079ea00700 (LWP 6414)):
#0  0x00002b076d113c3d in poll () from /lib64/libc.so.6
#1  0x00002b0773d7d76f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00002b0773d7deac in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00002b0773d7ed89 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  &lt;signal handler called&gt;
#5  0x00002b078e2bf4cf in HGCalDDDConstants::waferInLayerTest(int, int, bool) const () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/libGeometryHGCalCommonData.so
#6  0x00002b078e054c8c in HGCalGeometryLoader::build(HGCalTopology const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/libGeometryHGCalGeometry.so
#7  0x00002b079032ea4a in HGCalGeometryESProducer::produce(IdealGeometryRecord const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#8  0x00002b079033373d in decltype ({parm#1}()) edm::convertException::wrap&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const::{lambda()#1}&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#9  0x00002b0790333991 in edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}::operator()() const () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#10 0x00002b0790333bff in void edm::SerialTaskQueueChain::actionToRun&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
#11 0x00002b0790333c71 in edm::SerialTaskQueue::QueuedTask&lt;edm::SerialTaskQueueChain::push&lt;edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&gt;(edm::eventsetup::Callback&lt;HGCalGeometryESProducer, std::unique_ptr&lt;HGCalGeometry, std::default_delete&lt;HGCalGeometry&gt; &gt;, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator&lt;IdealGeometryRecord&gt; &gt;::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&amp)::{lambda()#1}&amp&amp)::{lambda()#1}&gt;::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02640/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-02-0000/lib/slc7_amd64_gcc820/pluginGeometryHGCalGeometryPlugins.so
```
which is a bit strange given that the test of 29034.0 in the PR passed. Maybe hints to a threading problem (IBs are run multithreaded, PRs with a single thread).

**Comment by makortel** [comment]
I'm not sure what log I looked earlier (https://github.com/cms-sw/cmssw/issues/30980#issuecomment-668174830), but now 29034.0 looks clean in CMSSW_11_2_X_2020-08-03-1100. So it looks like #30996 indeed fixed the error, and this issue can be closed.

**Comment by bsunanda** [comment]
I checked that in a recent IB and there is no segmentation violation there. I shall continue investigating

**Comment by kpedro88** [comment]
+upgrade
