### ISSUE TITLE
runTheMatrix massive failure for 11.2.X IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#31088]
Last night 11.2.X IBs failed to run runTheMatrix due to error [a]  .
@kpedro88  , may be this change https://github.com/cms-sw/cmssw/pull/31060/files has caused this issue?

[a]
```
runTheMatrix.py -n
processing relval_standard
processing relval_highstats
processing relval_pileup
processing relval_generator
processing relval_extendedgen
processing relval_production
processing relval_ged
ignoring relval_upgrade from default matrix
processing relval_2017
processing relval_2026
ERROR reading file: relval_2026 'DigiFullTrigger_2026D65'
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-06-2300/bin/slc7_amd64_gcc820/runTheMatrix.py", line 362, in <module>
    ret = runSelected(opt)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-06-2300/bin/slc7_amd64_gcc820/runTheMatrix.py", line 23, in runSelected
    mrd.prepare(opt.useInput, opt.refRel, opt.fromScratch)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-06-2300/python/Configuration/PyReleaseValidation/MatrixReader.py", line 500, in prepare
    self.readMatrix(matrixFile, useInput, refRel, fromScratch)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-06-2300/python/Configuration/PyReleaseValidation/MatrixReader.py", line 245, in readMatrix
    if self.relvalModule.steps[stepName] is None:
KeyError: 'DigiFullTrigger_2026D65'
```

**Comment by silviodonato** [comment]
I tried to reproduce the error by adding the recent PRs. The origin of the error is #30976 (cc: @bsunanda ).
I was able to run `runTheMatrix.py -n` with `CMSSW_11_2_X_2020-08-06-1100` + #31060

**Comment by silviodonato** [comment]
I'm preparing a temporary fix for the morning IB

**Comment by mmusich** [comment]
I think  #31091 could be a better fix.

**Comment by silviodonato** [comment]
#31090 closed in favour of #31091

**Comment by silviodonato** [comment]
#31091 has been merged, so the morning IB should be ok.
We didn't catch the error because the PR tests of https://github.com/cms-sw/cmssw/pull/30976 were rather old (based `CMSSW_11_2_X_2020-07-31-2300`) and we recently merged https://github.com/cms-sw/cmssw/pull/30988

**Comment by smuzaffar** [comment]
this is fixed now
