### ISSUE TITLE
Crash in pythia8 in cc8

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#31773]
Workflow 2018.11 step 1 crashes (or gets stuck/slow and gets killed by timeout) in CMSSW_11_2_X_2020-10-12-2300 for cc8_amd64_gcc8
```
#3  0x00002b2d102a3349 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b2d102a16d0 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/pluginFWCoreServicesPlugins.so
#6  <signal handler called>
#7  0x00002b2d0429d6c3 in __muldc3 (a=0, b=0, c=0, d=0) at ../../../libgcc/libgcc2.c:1988
#8  0x00002b2d36cc335e in Pythia8::Sigma2qqbar2gluinogluino::sigmaHat() () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#9  0x00002b2d36b893ca in Pythia8::Sigma2Process::sigmaHatWrap(int, int) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#10 0x00002b2d36c9c038 in Pythia8::SigmaProcess::sigmaPDF(bool, bool, bool, double, double) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#11 0x00002b2d36b59ba6 in Pythia8::PhaseSpace::trialKin123(bool, bool, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#12 0x00002b2d36b885f5 in Pythia8::ProcessContainer::trialProcess() () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#13 0x00002b2d36b9bb6b in Pythia8::ProcessLevel::nextOne(Pythia8::Event&) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#14 0x00002b2d36b9d365 in Pythia8::ProcessLevel::next(Pythia8::Event&) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#15 0x00002b2d36ba6f95 in Pythia8::Pythia::next() () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/external/cc8_amd64_gcc8/lib/libpythia8.so
#16 0x00002b2d3572fa16 in Pythia8Hadronizer::generatePartonsAndHadronize() () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/pluginGeneratorInterfacePythia8Filters.so
#17 0x00002b2d3576d597 in edm::GeneratorFilter<Pythia8Hadronizer, gen::ExternalDecayDriver>::filter(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/pluginGeneratorInterfacePythia8Filters.so
#18 0x00002b2d01fdd706 in edm::one::EDFilterBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#19 0x00002b2d01fc190e in edm::WorkerT<edm::one::EDFilterBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#20 0x00002b2d01f28245 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#21 0x00002b2d01f283fd in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/lib/cc8_amd64_gcc8/libFWCoreFramework.so
```
http://cmssdt.cern.ch/SDT/cgi-bin/logreader/cc8_amd64_gcc8/CMSSW_11_2_X_2020-10-12-2300/pyRelValMatrixLogs/run/2018.11_SMS-T1tttt_mGl-1500_mLSP-100_13_UP18+SMS-T1tttt_mGl-1500_mLSP-100FS_13_UP18+HARVESTUP18FS+MINIAODMCUP18FS/step1_SMS-T1tttt_mGl-1500_mLSP-100_13_UP18+SMS-T1tttt_mGl-1500_mLSP-100FS_13_UP18+HARVESTUP18FS+MINIAODMCUP18FS.log

In the previous cc8 IB CMSSW_11_2_X_2020-10-11-0000 this workflow succeeded.

**Comment by makortel** [comment]
assign generators

**Comment by agrohsje** [comment]
Let me add @smrenna. @mkirsano @SiewYan Is anyone of you available to further check? 
This is the corresponding fragment:
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SMS-T1tttt_mGl-1500_mLSP-100_13TeV-pythia8_cfi.py

**Comment by smrenna** [comment]
Hi, yes, I can get to this.

I have been in behavorial interview training for the past two days (just finished), and I am trying to catch up on my email.

Steve

**Comment by smrenna** [comment]
I didn't reproduce a crash in Pythia8 stand-alone, but I didn't use all of the CMS settings.
Do you know if this was in a long run, or the first event caused the crash?

**Comment by makortel** [comment]
The job was run with 4 threads and concurrent events, and it crashed during processing one of them (so close to "first event"). 

This is the first crash of this kind I've seen, and I did not spot any relevant PRs or external updates between the IB of the crash and the previous IB we ran cc8 tests. It did not crash in slc7, and in the next IB with cc8 (CMSSW_11_2_X_2020-10-13-2300) it did not crash either. So I'm not sure how reproducible the problem is.

**Comment by smrenna** [comment]
That makes it hard.  The core dump looks like the problem was in the qqbar -> gluino gluino subprocess.

**Comment by smrenna** [comment]
Matti, can we infer that it has something to do with threading?

**Comment by smrenna** [comment]
Workflow 2018.11 step 1 crashes (or gets stuck/slow and gets killed by timeout) in CMSSW_11_2_X_2020-10-12-2300 for cc8_amd64_gcc8

OR TIMES OUT!    So, this could just be the loop problem we saw before.

**Comment by makortel** [comment]
Yeah, it's hard to say from that stack trace alone. Perhaps it's best to wait for a next one to appear.

**Comment by makortel** [comment]
We have not seen this for a while, so I suppose we can close the issue.
