### ISSUE TITLE
[PPC] Unit test failing in Validation/Geometry

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32094]
Two unit tests are failing in Validation/Geometry

materialBudgetHGCalPlots
and
materialBudgetTrackerPlots

when run by hand 

`
python /scratch/mrodozov/units/CMSSW_11_2_X_2020-11-05-2300/src/Validation/Geometry/test/runP_HGCal_cfg.py geom=Extended2026D71 label=HGCal`

a (yet another) floating point exception followed:

```

=== booking user histos ===
=== booking user histos done ===
*** WARNING This event is out of the acceptance *** 
eta = 3.87687	 phi = -2.37745	 x/X0 = 0	 l/l0 = 0	 steps = 0
***
=== save user histos ===
11-Nov-2020 00:01:46 CET  Closed file file:single_neutrino_random.root
 *** Break *** floating point exception



===========================================================
There was a crash (#7 0x00003fff9f74ce04 in SigHandler(ESignals) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libCore.so).
This is the entire stack trace of all threads:
===========================================================

Thread 2 (Thread 0x3ffe89e3f1b0 (LWP 123858)):
#0  0x00003fffa8d83438 in read () from /lib64/libpthread.so.0
#1  0x00003fff8bbd259c in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/pluginFWCoreServicesPlugins.so
#2  0x00003fff8bbd2f60 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/pluginFWCoreServicesPlugins.so
#3  0x00003fff8bbd7c14 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/pluginFWCoreServicesPlugins.so
#4  0x00003fff9ef22354 in std::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#5  0x00003fffa8d78cd4 in start_thread () from /lib64/libpthread.so.0
#6  0x00003fffa8b57e14 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x3fffa9105ab0 (LWP 123825)):
#0  0x00003fffa8b0e4e8 in waitpid () from /lib64/libc.so.6
#1  0x00003fffa8a7fd3c in do_system () from /lib64/libc.so.6
#2  0x00003fffa8a80424 in system () from /lib64/libc.so.6
#3  0x00003fffa8d85348 in system () from /lib64/libpthread.so.0
#4  0x00003fff9f749714 in TUnixSystem::StackTrace() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libCore.so
#5  0x00003fff9df8f9f8 in (anonymous namespace)::TExceptionHandlerImp::HandleException(int) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libcppyy_backend2_7.so
#6  0x00003fff9f74cbec in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libCore.so
#7  0x00003fff9f74ce04 in SigHandler(ESignals) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libCore.so
#8  0x00003fff9f744444 in sighandler(int) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/external/slc7_ppc64le_gcc820/lib/libCore.so
#9  <signal handler called>
#10 0x00003fffa8c29fd0 in fesetenv

GLIBC_2.17 () from /lib64/libm.so.6
#11 0x00003fff9f26b6a0 in tbb::internal::cpu_ctl_env::set_env (this=<optimized out>) at ../../src/tbb/scheduler_common.h:446
#12 tbb::internal::context_guard_helper<false>::set_ctx (ctx=<optimized out>, this=0x3ffffd052bb0) at ../../src/tbb/scheduler.h:993
#13 tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=0x3fff9e2db200, context_guard=..., t=0x3fff9e2dfa40, isolation=0) at ../../src/tbb/custom_scheduler.h:462
#14 0x00003fff9f26baa4 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x3fff9e2db200, parent=..., child=<optimized out>) at ../../include/tbb/task.h:1003
#15 0x00003fff9f26c4b0 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::wait_for_all (this=<optimized out>, parent=..., child=0x0) at ../../src/tbb/governor.h:123
#16 0x00003fffa0ed71b4 in edm::eventsetup::EventSetupRecordIOVQueue::~EventSetupRecordIOVQueue() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/libFWCoreFramework.so
#17 0x00003fffa0e6fa14 in edm::EventProcessor::~EventProcessor() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/libFWCoreFramework.so
#18 0x00003fffa1149c90 in PythonEventProcessor::~PythonEventProcessor() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/libFWCorePythonFramework.so
#19 0x00003fffa114f9a4 in pybind11::class_<PythonEventProcessor>::dealloc(pybind11::detail::value_and_holder&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/libFWCorePythonFramework.so
#20 0x00003fffa1163b5c in pybind11_object_dealloc () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-05-2300/lib/slc7_ppc64le_gcc820/libFWCorePythonFramework.so
#21 0x00003fffa8e92698 in dict_dealloc (mp=0x3fff8c391d70) at Objects/dictobject.c:1086
#22 0x00003fffa8ec4d18 in subtype_dealloc (self=0x3fff8c38e6d0) at Objects/typeobject.c:1035
#23 0x00003fffa8e91124 in insertdict_by_entry (mp=0x3fffa89c7168, key=0x3fffa88a2600, hash=<optimized out>, ep=<optimized out>, value=<optimized out>) at Objects/dictobject.c:519
#24 0x00003fffa8e9607c in insertdict (value=0x3fffa9055f28 <_Py_NoneStruct>, hash=768398212998346496, key=0x3fffa88a2600, mp=0x3fffa89c7168) at Objects/dictobject.c:556
#25 dict_set_item_by_hash_or_entry (value=0x3fffa9055f28 <_Py_NoneStruct>, ep=0x0, hash=768398212998346496, key=0x3fffa88a2600, op=0x3fffa89c7168) at Objects/dictobject.c:795
#26 PyDict_SetItem (op=0x3fffa89c7168, key=0x3fffa88a2600, value=0x3fffa9055f28 <_Py_NoneStruct>) at Objects/dictobject.c:848
#27 0x00003fffa8e9d2b4 in _PyModule_Clear (m=<optimized out>) at Objects/moduleobject.c:139
#28 0x00003fffa8f61cdc in PyImport_Cleanup () at Python/import.c:483
#29 0x00003fffa8f7b41c in Py_Finalize () at Python/pythonrun.c:465
#30 Py_Finalize () at Python/pythonrun.c:411
#31 0x00003fffa8f96ff4 in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:670
#32 0x0000000010000718 in main (argc=<optimized out>, argv=<optimized out>) at ./Modules/python.c:20
===========================================================
```

**Comment by makortel** [comment]
assign core

FYI @cms-sw/geometry-l2 @cms-sw/dqm-l2

**Comment by makortel** [comment]
There is clearly something very fishy going on with floating points on PPC

**Comment by mrodozov** [comment]
this is fixed I'm guessing by this https://github.com/cms-sw/cmssw/pull/32117. It's only DB and Geometry failures now, none of which with floating point exception
