### ISSUE TITLE
Workflow failures caused by Phase2C11T2{2,3}M9

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32986]
In CMSSW_11_3 2021-02-23-2300 the workflow 35434.0 is fails with
```
GEN,SIM,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/bin/slc7_amd64_gcc900/cmsDriver.py", line 12, in run
    options = OptionsFromCommandLine()
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/python/Configuration/Applications/cmsDriverOptions.py", line 37, in OptionsFromCommandLine
    options=OptionsFromItems(sys.argv[1:])
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/python/Configuration/Applications/cmsDriverOptions.py", line 269, in OptionsFromItems
    raise Exception( "'%s' is not a valid option for '--era'. Valid options are %s." % (eraName, validOptions) )
Exception: 'Phase2C11T22M9' is not a valid option for '--era'. Valid options are 'tracker_apv_vfp30_2016', 'Run2_25ns', 'trackingPhase2PU140', 'Run2_2016_trackingLowPU', 'run2_HLTconditions_2016', 'run2_HF_2017', 'stage2L1Trigger_2021', 'phase2_trigger', 'Run1_pA', 'peripheralPbPb', 'Run1_peripheralPbPb', 'Phase2', 'run3_GEM', 'Run2_HI', 'Phase2C10_dd4hep', 'run2_HCAL_2017', 'run2_nanoAOD_94XMiniAODv1', 'run2_nanoAOD_94XMiniAODv2', 'Run2_25ns_HIPM', 'run2_nanoAOD_92X', 'phase2_GE0', 'fastSim', 'Run2_2017_FastSim', 'run2_HEPlan1_2017', 'Run2_2016_pA', 'phase2_squarePixels', 'run2_nanoAOD_106Xv1', 'run2_GEM_2017', 'Phase2C12', 'Phase2C10', 'Phase2C11', 'run2_miniAOD_devel', 'Run2_50ns_HIPM', 'phase2_ecal', 'run2_nanoAOD_94X2016', 'run2_HLTconditions_2018', 'phase2_tracker', 'Phase2C11_etlV4', 'run2_HLTconditions_2017', 'Run2_2018_pp_on_AA', 'Run2_2017_trackingLowPU', 'Run2_2018_highBetaStar', 'phase2_ecal_devel', 'run2_CSC_2018', 'run2_nanoAOD_106Xv2', 'Run2_2018_FastSim', 'highBetaStar_2018', 'phase2_GEM', 'trackingLowPU', 'run2_miniAOD_94XFall17', 'run2_HE_2018', 'run2_HI_specific', 'Run2_2018_pp_on_AA_noHCALmitigation', 'run2_HE_2017', 'phase2_3DPixels', 'Phase2C9_dd4hep', 'phase2_hfnose', 'phase1Pixel', 'run2_nanoAOD_102Xv1', 'run3_RPC', 'Run3_pp_on_PbPb', 'Run2_2017_pp_on_XeXe', 'phase2_hgcalV10', 'stage2L1Trigger', 'Run2_2017_ppRef', 'trackingPhase1', 'run2_50ns_specific', 'stage2L1Trigger_2018', 'hcalSkipPacker', 'phase2_timing_layer', 'Run2_2017_trackingRun2', 'ctpps_2017', 'pA_2016', 'Phase2C11_dd4hep', 'run2_25ns_specific', 'phase2_muon', 'run3_common', 'Phase2C11T22', 'Phase2C11T23', 'phase2_common', 'Run2_2018', 'Run2_2016', 'Run2_2017', 'Run3', 'Phase2C12_dd4hep', 'stage1L1Trigger', 'ctpps_2021', 'pf_badHcalMitigation', 'run3_HB', 'Run2_25ns_peripheralPbPb', 'bParking', 'phase2_hgcal', 'run2_HB_2018', 'Phase2C11M9', 'Run2_50ns', 'stage2L1Trigger_2017', 'Phase2C9', 'phase2_hgcalV11', 'Run3_dd4hep', 'phase2_hgcalV12', 'hcalHardcodeConditions', 'ctpps_2016', 'phase2_timing', 'Run2_2016_HIPM', 'phase2_hcal', 'ctpps_2018', 'run2_miniAOD_80XLegacy', 'run2_2017_noTrackingModifier', 'run2_common'.
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-23-2300/pyRelValMatrixLogs/run/35434.0_TTbar_14TeV+2026D78+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D78+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/

and 35834.0 with
```
GEN,SIM,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/bin/slc7_amd64_gcc900/cmsDriver.py", line 12, in run
    options = OptionsFromCommandLine()
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/python/Configuration/Applications/cmsDriverOptions.py", line 37, in OptionsFromCommandLine
    options=OptionsFromItems(sys.argv[1:])
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2021-02-23-2300/python/Configuration/Applications/cmsDriverOptions.py", line 269, in OptionsFromItems
    raise Exception( "'%s' is not a valid option for '--era'. Valid options are %s." % (eraName, validOptions) )
Exception: 'Phase2C11T23M9' is not a valid option for '--era'. Valid options are 'tracker_apv_vfp30_2016', 'Run2_25ns', 'trackingPhase2PU140', 'Run2_2016_trackingLowPU', 'run2_HLTconditions_2016', 'run2_HF_2017', 'stage2L1Trigger_2021', 'phase2_trigger', 'Run1_pA', 'peripheralPbPb', 'Run1_peripheralPbPb', 'Phase2', 'run3_GEM', 'Run2_HI', 'Phase2C10_dd4hep', 'run2_HCAL_2017', 'run2_nanoAOD_94XMiniAODv1', 'run2_nanoAOD_94XMiniAODv2', 'Run2_25ns_HIPM', 'run2_nanoAOD_92X', 'phase2_GE0', 'fastSim', 'Run2_2017_FastSim', 'run2_HEPlan1_2017', 'Run2_2016_pA', 'phase2_squarePixels', 'run2_nanoAOD_106Xv1', 'run2_GEM_2017', 'Phase2C12', 'Phase2C10', 'Phase2C11', 'run2_miniAOD_devel', 'Run2_50ns_HIPM', 'phase2_ecal', 'run2_nanoAOD_94X2016', 'run2_HLTconditions_2018', 'phase2_tracker', 'Phase2C11_etlV4', 'run2_HLTconditions_2017', 'Run2_2018_pp_on_AA', 'Run2_2017_trackingLowPU', 'Run2_2018_highBetaStar', 'phase2_ecal_devel', 'run2_CSC_2018', 'run2_nanoAOD_106Xv2', 'Run2_2018_FastSim', 'highBetaStar_2018', 'phase2_GEM', 'trackingLowPU', 'run2_miniAOD_94XFall17', 'run2_HE_2018', 'run2_HI_specific', 'Run2_2018_pp_on_AA_noHCALmitigation', 'run2_HE_2017', 'phase2_3DPixels', 'Phase2C9_dd4hep', 'phase2_hfnose', 'phase1Pixel', 'run2_nanoAOD_102Xv1', 'run3_RPC', 'Run3_pp_on_PbPb', 'Run2_2017_pp_on_XeXe', 'phase2_hgcalV10', 'stage2L1Trigger', 'Run2_2017_ppRef', 'trackingPhase1', 'run2_50ns_specific', 'stage2L1Trigger_2018', 'hcalSkipPacker', 'phase2_timing_layer', 'Run2_2017_trackingRun2', 'ctpps_2017', 'pA_2016', 'Phase2C11_dd4hep', 'run2_25ns_specific', 'phase2_muon', 'run3_common', 'Phase2C11T22', 'Phase2C11T23', 'phase2_common', 'Run2_2018', 'Run2_2016', 'Run2_2017', 'Run3', 'Phase2C12_dd4hep', 'stage1L1Trigger', 'ctpps_2021', 'pf_badHcalMitigation', 'run3_HB', 'Run2_25ns_peripheralPbPb', 'bParking', 'phase2_hgcal', 'run2_HB_2018', 'Phase2C11M9', 'Run2_50ns', 'stage2L1Trigger_2017', 'Phase2C9', 'phase2_hgcalV11', 'Run3_dd4hep', 'phase2_hgcalV12', 'hcalHardcodeConditions', 'ctpps_2016', 'phase2_timing', 'Run2_2016_HIPM', 'phase2_hcal', 'ctpps_2018', 'run2_miniAOD_80XLegacy', 'run2_2017_noTrackingModifier', 'run2_common'.
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-23-2300/pyRelValMatrixLogs/run/35834.0_TTbar_14TeV+2026D79+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D79+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/

**Comment by makortel** [comment]
assign upgrade

**Comment by makortel** [comment]
Likely caused by https://github.com/cms-sw/cmssw/pull/32952 that added these `ModifierChain`s.

**Comment by makortel** [comment]
The `DQMOffline/Configuration` unit test failures seem to have the same cause
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-23-2300/unitTestLogs/DQMOffline/Configuration#/

FYI @cms-sw/dqm-l2

**Comment by srimanob** [comment]
@makortel 
Thanks, will make PR to fix the issue. I've missed a file.

**Comment by srimanob** [comment]
Solve in https://github.com/cms-sw/cmssw/pull/32987
thanks @mmusich

**Comment by srimanob** [comment]
+1
