### ISSUE TITLE
'Process' object has no attribute 'lumiProducer'

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#33058]
A unit test is failing in `Configuration/DataProcessing` after having merged #33024 .
@jpata could you have a look?

```
===== Test "TestConfigDP" ====
argument 0: TestConfigDP
argument 1: /bin/bash
argument 2: Configuration/DataProcessing/test
argument 3: run_CfgTest.sh
shell is: /bin/bash
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100
topdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100
testdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test
tmpdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/tmp/slc7_amd64_gcc900
testbin is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/test/slc7_amd64_gcc900
Running script: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/run_CfgTest.sh
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunRepack.py --select-events HLT:path1,HLT:path2 --lfn /store/whatever
Now do:
cmsRun -e RunRepackCfg.py
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunExpressProcessing.py --scenario cosmicsEra_Run2_2017 --global-tag GLOBALTAG --lfn /store/whatever --fevt --dqmio --alcareco TkAlMinBias+SiStripCalMinBias
Retrieved Scenario: cosmicsEra_Run2_2017
Using Global Tag: GLOBALTAG
Configuring to Write out FEVT
Configuring to Write out DQMIO
Configuring to Write out ALCARECO
removing ENDJOB from steps since not compatible with DQMIO dataTier
entry tobeoverwritten.xyz
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: ALCAPRODUCER Spec: ['TkAlMinBias', 'SiStripCalMinBias']
Step: DQM Spec: 
customising the process with customiseCosmicData from Configuration/DataProcessing/RecoTLR
Now do:
cmsRun -e RunExpressProcessingCfg.py
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunVisualizationProcessing.py --scenario cosmicsEra_Run2_2017 --lfn /store/whatever --global-tag GLOBALTAG --fevt
Retrieved Scenario: cosmicsEra_Run2_2017
Using Global Tag: GLOBALTAG
Configuring to Write out Fevt...
Using EDM source
entry tobeoverwritten.xyz
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: ENDJOB Spec: 
customising the process with customiseCosmicData from Configuration/DataProcessing/RecoTLR
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunVisualizationProcessing.py", line 182, in <module>
    visualizator()
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunVisualizationProcessing.py", line 104, in __call__
    raise RuntimeError(msg)
RuntimeError: Error creating Visualization Processing config:
'Process' object has no attribute 'lumiProducer'
Failure for configuration: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/Configuration/DataProcessing/test/RunVisualizationProcessing.py --scenario cosmicsEra_Run2_2017 --lfn /store/whatever --global-tag GLOBALTAG --fevt: status 1

```

**Comment by silviodonato** [comment]
assign reconstruction

**Comment by silviodonato** [comment]
fixed by  #33069

**Comment by jpata** [comment]
Sorry, I missed the notification somehow.
For my education, how come the unit test didn't fail in the bot tests of the original PR ([link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6780aa/13188/unitTests/failed.html))? Is it because checkdeps didn't pick up Configuration/DataProcessing, and it only came up in the build process?

**Comment by makortel** [comment]
> Is it because checkdeps didn't pick up Configuration/DataProcessing, and it only came up in the build process?

Correct. `Configuration/DataProcessing` appears to have no direct dependence on the files changed in #33069 and therefore the machinery behind `git cms-checkdeps -a` was unaware of the impact. (this is similar to other deficiencies in the testing system that have been discussed earlier, but this would be hard to fix in general without lot's of manual maintenance or running all unit tests; so far the problems appear to be infrequent-enough for catching them in IBs to be sufficient)
