### ISSUE TITLE
Failure of step 1 in 280.0

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#33452]
In the IB, workflow 280.0 step 2 is failing because the ROOT file generated by step 1 is missing TTrees. Looking at step 1 it appears to job just stopped. Why does runTheMatrix.py think that step 1 succeeded?

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
The log from step 1 shows
```
GEN,SIM,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Step: GEN Spec: 
Loading generator fragment from Configuration.Generator.AMPT_PPb_5020GeV_MinimumBias_cfi
Step: SIM Spec: 
Step: ENDJOB Spec: 
customising the process with customiseWithTimeMemorySummary from Validation/Performance/TimeMemorySummary
Starting /home/cmsbuild/jenkins_b/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 14400  cmsRun -j JobReport1.xml  AMPT_PPb_5020GeV_MinimumBias_cfi_GEN_SIM.py
%MSG-i ThreadStreamSetup:  (NoModuleName) 16-Apr-2021 15:22:22 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
%MSG-s ModulesSynchingOnLumis:  AfterModConstruction 16-Apr-2021 15:22:35 CEST  pre-events
The following modules require synchronizing on LuminosityBlock boundaries:
  AMPTGeneratorFilter generator
%MSG
 
           ##################################################
           #      AMPT (A Multi-Phase Transport) model      #
           #          Version 1.26t5 (Default)              #
           #                4/06/2015                       #
           ##################################################
            


          **************************************************
          *     |      |       _______      /  ------/     *
          *   ----- ------     |_____|     /_/     /       *
          *    |||    /        |_____|      /    / |       *
          *    /| |  /_/       /_______    /_  /    |      *
          *   / |     / /     /  /  / |        -------     *
          *     |    / /|       /  /  |     /     |        *
          *     |   / /  |     /  /  _|    /   -------     *
          *                                                *
          **************************************************
                                HIJING                      
                 Heavy Ion Jet INteraction Generator        
                                  by                        
                      X. N. Wang  and  M. Gyulassy           
                       Lawrence Berkeley Laboratory           


 A��Fwrong or unavailable proj name
```

**Comment by makortel** [comment]
Which IB did this happen?

**Comment by Dr15Jones** [comment]
CMSSW_12_0 2021-04-16-1100

**Comment by makortel** [comment]
Ah, on ARM (slc7_aarch64_gcc9)

**Comment by dan131riley** [comment]
It's calling FORTRAN exit with a success code I guess.  We also see occasional segfaults in TBB while exiting, but the relevant bit is why it's exiting--AMPT is printing the message:
```
 A��Fwrong or unavailable proj name
```
and calling exit:
```
#14 0x0000ffff870b8914 in exit () from /lib64/libc.so.6
#15 0x0000ffff82cae5a4 in _gfortran_stop_string (string=<optimized out>, len=<optimized out>, quiet=<optimized out>) at ../../../libgfortran/runtime/stop.c:150
#16 0x0000fffefe46ce58 in hijset_ () from /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-05-07-2300/lib/slc7_aarch64_gcc9/libGeneratorInterfaceAMPTInterface.so
#17 0x0000fffefe4b787c in amptset_ () from /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-05-07-2300/lib/slc7_aarch64_gcc9/libGeneratorInterfaceAMPTInterface.so
#18 0x0000fffefe40f940 in gen::AMPTHadronizer::call_amptset(double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int) () from /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-05-07-2300/lib/slc7_aarch64_gcc9/libGeneratorInterfaceAMPTInterface.so
```
Looking at the code for `AMPTHadronizer::call_amptset()` there are a couple of obvious problems:
https://github.com/cms-sw/cmssw/blob/4252a8a664ef8178526a5924c8bf0a2bbb625f21/GeneratorInterface/AMPTInterface/src/AMPTHadronizer.cc#L230-L245
There's a minor efficiency issue that strings are being passed by value, not by reference, but the main problem is the calls to `strlen(frame.data())`.  `std::string::data()` is not guaranteed to return a null-terminated string, so it isn't safe to use `strlen()` there.  It's also unnecessary, better to just call `frame.length()`
