### ISSUE TITLE
[ARM] Segfault in TestFWCoreFrameworkeventprocessor

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#33535]
The `TestFWCoreFrameworkeventprocessor` unit test failed in slc7_aarch64_gcc9 CMSSW_12_0_X_2021-04-25-0000
```
===== Test "TestFWCoreFrameworkeventprocessor" ====
Running .>>> processing event # run: 1 lumi: 1 event: 1 time 5000001
>>> processing event # run: 1 lumi: 1 event: 2 time 10000001
>>> processing event # run: 1 lumi: 1 event: 3 time 15000001
>>> processing event # run: 1 lumi: 1 event: 4 time 20000001
>>> processing event # run: 1 lumi: 1 event: 5 time 25000001
>>> processed 5 events
.
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 187 (Thread 0xfffe28b29c40 (LWP 132548)):
#0  0x0000ffffb297a780 in syscall () from /lib64/libc.so.6
#1  0x0000ffffb2f544f0 in tbb::internal::futex_wait (comparand=2, futex=0xffffb14ab82c) at ../../include/tbb/machine/linux_common.h:81
#2  tbb::internal::binary_semaphore::P (this=0xffffb14ab82c) at ../../src/tbb/semaphore.h:205
#3  rml::internal::thread_monitor::commit_wait (c=..., this=0xffffb14ab820) at ../../src/tbb/../rml/server/thread_monitor.h:255
#4  tbb::internal::rml::private_worker::run (this=0xffffb14ab800) at ../../src/tbb/private_server.cpp:273
#5  0x0000ffffb2f54514 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:219
#6  0x0000ffffb2a37d38 in start_thread () from /lib64/libpthread.so.0
#7  0x0000ffffb297f690 in thread_start () from /lib64/libc.so.6

Thread 186 (Thread 0xfffe39f79c40 (LWP 132547)):
#0  0x0000ffffb297a780 in syscall () from /lib64/libc.so.6
#1  0x0000ffffb2f544f0 in tbb::internal::futex_wait (comparand=2, futex=0xffffb14abc2c) at ../../include/tbb/machine/linux_common.h:81
#2  tbb::internal::binary_semaphore::P (this=0xffffb14abc2c) at ../../src/tbb/semaphore.h:205
#3  rml::internal::thread_monitor::commit_wait (c=..., this=0xffffb14abc20) at ../../src/tbb/../rml/server/thread_monitor.h:255
#4  tbb::internal::rml::private_worker::run (this=0xffffb14abc00) at ../../src/tbb/private_server.cpp:273
#5  0x0000ffffb2f54514 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:219
#6  0x0000ffffb2a37d38 in start_thread () from /lib64/libpthread.so.0
#7  0x0000ffffb297f690 in thread_start () from /lib64/libc.so.6

<snip>


Thread 1 (Thread 0xffffb21b0000 (LWP 130891)):
#0  0x0000ffffb294a37c in waitpid () from /lib64/libc.so.6
#1  0x0000ffffb28e1f54 in do_system () from /lib64/libc.so.6
#2  0x0000ffffb28e236c in system () from /lib64/libc.so.6
#3  0x0000ffffb35da8c8 in TUnixSystem::StackTrace() () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_aarch64_gcc9/lib/libCore.so
#4  0x0000ffffb35d79b0 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_aarch64_gcc9/lib/libCore.so
#5  <signal handler called>
#6  0x0000ffffb2966908 in sched_yield () from /lib64/libc.so.6
#7  0x0000ffffb2f60be8 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0xffffb20b1600, completion_ref_count=
0xffffb20b7d28: 1, isolation=0) at ../../src/tbb/mailbox.h:225
#8  0x0000ffffb2f62060 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0xffffb20b1600, parent=..., child=<optimized out>) at ../../include/tbb/task.h:1003
#9  0x0000ffffb479b1e8 in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_aarch64_gcc9/libFWCoreFramework.so
#10 0x0000ffffb47a4e40 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_aarch64_gcc9/libFWCoreFramework.so
#11 0x00000000004121ec in testeventprocessor::parseTest() ()
#12 0x0000ffffb3202d78 in CppUnit::TestCaseMethodFunctor::operator() (this=<optimized out>) at TestCase.cpp:32
#13 0x0000ffffb31fae5c in CppUnit::DefaultProtector::protect (this=0x357b1a50, functor=..., context=...) at DefaultProtector.cpp:15
#14 0x0000ffffb32008dc in CppUnit::ProtectorChain::ProtectFunctor::operator() (this=<optimized out>) at ProtectorChain.cpp:20
#15 CppUnit::ProtectorChain::protect (this=0x357b1790, functor=..., context=...) at ProtectorChain.cpp:86
#16 0x0000ffffb3207b70 in CppUnit::TestResult::protect (this=0xffffc7a8de08, functor=..., test=<optimized out>, shortDescription=...) at TestResult.cpp:182
#17 0x0000ffffb3202b40 in CppUnit::TestCase::run (this=0x357b22f0, result=0xffffc7a8de08) at /home/cmsbld/x/w/slc7_aarch64_gcc9/external/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:300
#18 0x0000ffffb32030e4 in CppUnit::TestComposite::doRunChildTests (this=0x357b2280, controller=0xffffc7a8de08) at TestComposite.cpp:59
#19 0x0000ffffb3202fb4 in CppUnit::TestComposite::run (this=0x357b2280, result=0xffffc7a8de08) at TestComposite.cpp:23
#20 0x0000ffffb32030e4 in CppUnit::TestComposite::doRunChildTests (this=0x357b1fa0, controller=0xffffc7a8de08) at TestComposite.cpp:59
#21 0x0000ffffb3202fb4 in CppUnit::TestComposite::run (this=0x357b1fa0, result=0xffffc7a8de08) at TestComposite.cpp:23
#22 0x0000ffffb3207abc in CppUnit::TestResult::runTest (this=0xffffc7a8de08, test=0x357b1f50) at TestResult.cpp:149
#23 0x0000ffffb320a2b0 in CppUnit::TestRunner::run (this=<optimized out>, controller=..., testPath=...) at TestRunner.cpp:96
#24 0x000000000040fed4 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x0000ffffb2966908 in sched_yield () from /lib64/libc.so.6
#7  0x0000ffffb2f60be8 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0xffffb20b1600, completion_ref_count=
0xffffb20b7d28: 1, isolation=0) at ../../src/tbb/mailbox.h:225
#8  0x0000ffffb2f62060 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0xffffb20b1600, parent=..., child=<optimized out>) at ../../include/tbb/task.h:1003
#9  0x0000ffffb479b1e8 in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_aarch64_gcc9/libFWCoreFramework.so
#10 0x0000ffffb47a4e40 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/week0/slc7_aarch64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_aarch64_gcc9/libFWCoreFramework.so
#11 0x00000000004121ec in testeventprocessor::parseTest() ()
#12 0x0000ffffb3202d78 in CppUnit::TestCaseMethodFunctor::operator() (this=<optimized out>) at TestCase.cpp:32
#13 0x0000ffffb31fae5c in CppUnit::DefaultProtector::protect (this=0x357b1a50, functor=..., context=...) at DefaultProtector.cpp:15
#14 0x0000ffffb32008dc in CppUnit::ProtectorChain::ProtectFunctor::operator() (this=<optimized out>) at ProtectorChain.cpp:20
#15 CppUnit::ProtectorChain::protect (this=0x357b1790, functor=..., context=...) at ProtectorChain.cpp:86
#16 0x0000ffffb3207b70 in CppUnit::TestResult::protect (this=0xffffc7a8de08, functor=..., test=<optimized out>, shortDescription=...) at TestResult.cpp:182
#17 0x0000ffffb3202b40 in CppUnit::TestCase::run (this=0x357b22f0, result=0xffffc7a8de08) at /home/cmsbld/x/w/slc7_aarch64_gcc9/external/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:300
#18 0x0000ffffb32030e4 in CppUnit::TestComposite::doRunChildTests (this=0x357b2280, controller=0xffffc7a8de08) at TestComposite.cpp:59
#19 0x0000ffffb3202fb4 in CppUnit::TestComposite::run (this=0x357b2280, result=0xffffc7a8de08) at TestComposite.cpp:23
#20 0x0000ffffb32030e4 in CppUnit::TestComposite::doRunChildTests (this=0x357b1fa0, controller=0xffffc7a8de08) at TestComposite.cpp:59
#21 0x0000ffffb3202fb4 in CppUnit::TestComposite::run (this=0x357b1fa0, result=0xffffc7a8de08) at TestComposite.cpp:23
#22 0x0000ffffb3207abc in CppUnit::TestResult::runTest (this=0xffffc7a8de08, test=0x357b1f50) at TestResult.cpp:149
#23 0x0000ffffb320a2b0 in CppUnit::TestRunner::run (this=<optimized out>, controller=..., testPath=...) at TestRunner.cpp:96
#24 0x000000000040fed4 in main ()
===========================================================



---> test TestFWCoreFrameworkeventprocessor had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_aarch64_gcc9/CMSSW_12_0_X_2021-04-25-0000/unitTestLogs/FWCore/Framework#/28403-28403

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
My first question is how did it end up spawning 187 threads...

**Comment by dan131riley** [comment]
The test doesn't set a thread limit, so TBB spawns as many threads as there are cores

**Comment by Dr15Jones** [comment]
If no one is doing it yet, I will change that test to limit the cores (probably to 1).

**Comment by makortel** [comment]
I think this issue can be closed now
