### ISSUE TITLE
scram build problems on afs with tmp softlinked to local dir

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#33698]
The following problem started happening in my build setup (here #33645 is tested, but it probably doesn't matter)

```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/share/lcg/SCRAMV1/V3_00_23/bin/scram.py", line 114, in <module>
    main()
  File "/cvmfs/cms-ib.cern.ch/week0/share/lcg/SCRAMV1/V3_00_23/bin/scram.py", line 109, in main
    if not execcommand(args, opts):
  File "/cvmfs/cms-ib.cern.ch/week0/share/lcg/SCRAMV1/V3_00_23/bin/scram.py", line 103, in execcommand
    return eval('scram_commands.cmd_%s' % cmds[0])(args, opts)
  File "/cvmfs/cms-ib.cern.ch/nweek-02680/share/lcg/SCRAMV1/V3_00_23/SCRAM/Core/CMD.py", line 28, in cmd_build
    return process(args, opts)
  File "/cvmfs/cms-ib.cern.ch/nweek-02680/share/lcg/SCRAMV1/V3_00_23/SCRAM/Core/Commands/build.py", line 402, in process
    dircache.write_gmake()
  File "/cvmfs/cms-ib.cern.ch/nweek-02680/share/lcg/SCRAMV1/V3_00_23/SCRAM/Core/Commands/build.py", line 337, in write_gmake
    self.dir_make()
  File "/cvmfs/cms-ib.cern.ch/nweek-02680/share/lcg/SCRAMV1/V3_00_23/SCRAM/Core/Commands/build.py", line 269, in dir_make
    self.buildrules.process(pkgclass.branch["template"], pkgclass, self.cache['DIRCACHE'])
  File "/myafspath/CMSSW_12_0_X_2021-05-11-1100-test33645/config/SCRAM/Plugins/BuildRules.py", line 70, in process
    rename(ofile, nfile)
OSError: [Errno 18] Invalid cross-device link: '/myafspath/CMSSW_12_0_X_2021-05-11-1100-test33645/.SCRAM/slc7_amd64_gcc900/MakeData/DirCache/src_RecoHGCal.mk' -> '/myafspath/CMSSW_12_0_X_2021-05-11-1100-test33645/tmp/slc7_amd64_gcc900/MakeData/DirCache/src_RecoHGCal.mk'
```

here `/myafspath/CMSSW_12_0_X_2021-05-11-1100-test33645/tmp` is a softlink to a local filesystem 

I think that this is related to scram v3

**Comment by slava77** [comment]
assign core

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/7033 shoudl fix this issue

**Comment by smuzaffar** [comment]
yes it is related to SCRAMV3. python `os.rename(src, des)` does not work if `src` and `des` are on different devices. I have updated scram to use `shutils.move` which works cross-devices
