### ISSUE TITLE
Memory overread in RealisticSimClusterMapper

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#34803]
The RelVal from CMSSW_12_1_ASAN_X_2021-08-04-2300 shows a memory overhead in RealisticSimClusterMapper

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_1_ASAN_X_2021-08-04-2300/pyRelValMatrixLogs/run/34834.9921_TTbar_14TeV+2026D76PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU/step4_TTbar_14TeV+2026D76PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU.log#/

The relevant info is
```
=================================================================
==10356==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x606000d8dc80 at pc 0x2b3683cbdbce bp 0x7fff46533b90 sp 0x7fff46533b88
READ of size 8 at 0x606000d8dc80 thread T0
%MSG-w MemoryCheck:  PFECALSuperClusterProducer:particleFlowSuperClusterHGCal  05-Aug-2021 14:26:21 CEST Run: 1 Event: 4004
MemoryCheck: module PFECALSuperClusterProducer:particleFlowSuperClusterHGCal VSIZE 2.09764e+07 16.6445 RSS 9599.31 -135.461
%MSG
    #0 0x2b3683cbdbcd in RealisticSimClusterMapper::buildClusters(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<reco::PFCluster, std::allocator<reco::PFCluster> >&) (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/pluginRecoParticleFlowPFClusterProducerPlugins_simmappers.so+0x28bcd)
    #1 0x2b36837b50a8 in PFClusterProducer::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/pluginRecoParticleFlowPFClusterProducerPlugins.so+0x1a60a8)

0x606000d8dc80 is located 0 bytes to the right of 64-byte region [0x606000d8dc40,0x606000d8dc80)
allocated by thread T0 here:
    #0 0x2b36088973d7 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x2b3609fec772 in void std::vector<double, std::allocator<double> >::_M_realloc_insert<double const&>(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double const&) (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/libFWCoreParameterSet.so+0x228772)
    #2 0x2b3609fe7a87 in edm::decode(std::vector<double, std::allocator<double> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/libFWCoreParameterSet.so+0x223a87)
    #3 0x2b3609e6268c in edm::Entry::getVDouble() const (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/libFWCoreParameterSet.so+0x9e68c)
    #4 0x2b3609f1ae72 in std::vector<double, std::allocator<double> > edm::ParameterSet::getParameter<std::vector<double, std::allocator<double> > >(char const*) const (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/libFWCoreParameterSet.so+0x156e72)
    #5 0x2b3683cd23eb in RealisticSimClusterMapper::RealisticSimClusterMapper(edm::ParameterSet const&, edm::ConsumesCollector&) (/cvmfs/cms-ib.cern.ch/nweek-02692/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_ASAN_X_2021-08-04-2300/lib/slc7_amd64_gcc10/pluginRecoParticleFlowPFClusterProducerPlugins_simmappers.so+0x3d3eb)

```

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by Dr15Jones** [comment]
The problem seems likely to be either
https://github.com/cms-sw/cmssw/blob/2508ef2a29415a54c354b5330ab4726548b1c12b/RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc#L170
or
https://github.com/cms-sw/cmssw/blob/2508ef2a29415a54c354b5330ab4726548b1c12b/RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc#L176

as they both come from the ParameterSet and both are reading from the vector without a cross-check about index out of range.

**Comment by Dr15Jones** [comment]
So there was this attempt at protection here
https://github.com/cms-sw/cmssw/blob/2508ef2a29415a54c354b5330ab4726548b1c12b/RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc#L166

with the calculations

https://github.com/cms-sw/cmssw/blob/2508ef2a29415a54c354b5330ab4726548b1c12b/RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc#L153-L155

but if `abseta == calibMaxEta_` (which is allowed by the check) then we get `etabin== size of container`

**Comment by slava77** [comment]
@laurenhay @marksan87

**Comment by slava77** [comment]
> @laurenhay @marksan87

please clarify when you are available to take a look at the issue (or redirect to relevant developers).
Thank you.

**Comment by marksan87** [comment]
> > @laurenhay @marksan87
> 
> please clarify when you are available to take a look at the issue (or redirect to relevant developers).
> Thank you.

I'm looking into this now

**Comment by marksan87** [comment]
If `abseta == calibMaxEta_` is the source of the overflow, then `etabin` could be capped to `(container_size-1)` with `std::min`. I'm not able to reproduce the error by running the `34834.9921` workflow though. How can I reproduce this?

**Comment by slava77** [comment]
> If `abseta == calibMaxEta_` is the source of the overflow, then `etabin` could be capped to `(container_size-1)` with `std::min`. I'm not able to reproduce the error by running the `34834.9921` workflow though. How can I reproduce this?

did you use CMSSW_12_1_ASAN_X_2021-08-04-2300 release?

**Comment by marksan87** [comment]
> > If `abseta == calibMaxEta_` is the source of the overflow, then `etabin` could be capped to `(container_size-1)` with `std::min`. I'm not able to reproduce the error by running the `34834.9921` workflow though. How can I reproduce this?
> 
> did you use CMSSW_12_1_ASAN_X_2021-08-04-2300 release?

Yes I am using `CMSSW_12_1_ASAN_X_2021-08-04-2300` and running the test with `runTheMatrix.py -l 34834.9921`. One difference I notice from inspecting the log is that the overflow occurs on event 4004. When I run the test locally it only processes 10 events, so it doesn't appear to be running the event that is causing this crash.

**Comment by slava77** [comment]
@Dr15Jones 
please provide a command to rerun the workflow.
It looks like a simple `-l #` is not enough.

**Comment by slava77** [comment]
I see that the cmsDriver commands are available via
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_1/2021-08-04-2300?selectedArchs=slc7_amd64_gcc10&selectedFlavors=ASAN_X&selectedStatus=failed

@smuzaffar is there a single `runTheMatrix.py -l 34834.9921 someOtherArguments` that can be started?
To avoid the digi randomness, it may be useful to start from step4: are the root files available somewhere?

**Comment by Dr15Jones** [comment]
@slava77 
>please provide a command to rerun the workflow.

I didn't run the tests, I just read the logs from the IB.

**Comment by smuzaffar** [comment]
`runTheMatrix.py -l 34834.9921 someOtherArguments` should work. you want want to add `-i all --ibeos` too

**Comment by slava77** [comment]
> `runTheMatrix.py -l 34834.9921 someOtherArguments` should work. you want want to add `-i all --ibeos` too.

Thank you for clarifying on this.
I noticed in the logs that the number of threads is 4; not sure if this will be more likely to trigger the error.

Still, do we have the job outputs available? I think that it would be more useful to start from step3.root file and run only the reco step, because all the preceding steps are at least known to use random numbers in digitization and pileup selection.

**Comment by Dr15Jones** [comment]
@slava77 
> I noticed in the logs that the number of threads is 4; not sure if this will be more likely to trigger the error.

When using 4 threads (really 4 streams) each stream gets a modified random number seed. So to get random number reply properly, you need to set the same number of threads/streams as the original job. I'd also suggest running a few more events than the original job just to be sure each stream gets as least as many events as the original job.

**Comment by marksan87** [comment]
I ran `runTheMatrix.py -l 34834.9921 -t 4 --nStreams 4 -i all --ibeos` using 4 threads and 4 streams as seen in the logs. This processed the correct events but didn't reproduce the error. The original step3.root file would be helpful to debug further. 

What is the argument to process additional events?

**Comment by slava77** [comment]
> What is the argument to process additional events?

`--command="-n 100"`

**Comment by jpata** [comment]
type pf
