### ISSUE TITLE
Failure in 136.72413

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#35116]
Workflow 136.72413 step 2 fails in CMSSW_12_1_X_2021-09-01-1100
```
customising the process with miniAOD_customizeAllData from PhysicsTools/PatAlgos/slimming/miniAOD_tools
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/Configuration/Applications/ConfigBuilder.py", line 2314, in prepare
    self.pythonCfgCode += self.addCustomise(1)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/Configuration/Applications/ConfigBuilder.py", line 912, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/PhysicsTools/PatAlgos/slimming/miniAOD_tools.py", line 631, in miniAOD_customizeAllData
    miniAOD_customizeCommon(process)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/PhysicsTools/PatAlgos/slimming/miniAOD_tools.py", line 484, in miniAOD_customizeCommon
    (~pp_on_AA).toModify(process, _add_metPuppi)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/FWCore/ParameterSet/Config.py", line 1542, in toModify
    Modifier._toModify(obj,func,**kw)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/FWCore/ParameterSet/Config.py", line 1624, in _toModify
    func(obj)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/PhysicsTools/PatAlgos/slimming/miniAOD_tools.py", line 473, in _add_metPuppi
    process.load('RecoMET.METProducers.pfMetPuppi_cfi')
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/FWCore/ParameterSet/Config.py", line 685, in load
    self.extend(sys.modules[moduleName])
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/FWCore/ParameterSet/Config.py", line 708, in extend
    self.__setattr__(name,item)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/FWCore/ParameterSet/Config.py", line 448, in __setattr__
    raise ValueError(msg1+s.label_()+msg2)
ValueError: Trying to override definition of pfMetPuppi while it is used by the task patAlgosToolsTask
 new object defined in: /cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/cfipython/slc7_amd64_gcc900/RecoMET/METProducers/pfMetPuppi_cfi.py
 existing object defined in: /cvmfs/cms-ib.cern.ch/nweek-02696/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-09-01-1100/python/PhysicsTools/PatUtils/tools/runMETCorrectionsAndUncertainties.py
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-01-1100/pyRelValMatrixLogs/run/136.72413_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMININANO_data2016UL_HIPM_met+HARVESTDR2_REMININANO_data2016UL_HIPM_met/step2_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMININANO_data2016UL_HIPM_met+HARVESTDR2_REMININANO_data2016UL_HIPM_met.log#/

**Comment by makortel** [comment]
Ah, realized now from the description of https://github.com/cms-sw/cmssw/pull/34714 that this workflow is supposed to fail for now. Probably we don't need an issue for that.
