### ISSUE TITLE
makeTrackValidationPlots.py crashes in CMSSW_12_1_0_pre2

### ISSUE THREAD

**Issue by ChuyuanLiu** [cms-sw/cmssw#35225]
Hi,

I encountered a crash when running the command `makeTrackValidationPlots.py DQM_RelValTTbar_D76PU200_14TeV_12_0_0_pre6.root DQM_RelValTTbar_D76PU200_14TeV_12_1_0_pre2.root --ptcut --extended --html-sample TTbar_D76PU200_12_0_0_pre6_vs_12_1_0_pre2 --html-validation-name TTbar_D76PU200_12_0_0_pre6_vs_12_1_0_pre2
` in CMSSW_12_1_0_pre2, which works properly in CMSSW_12_0_0_pre6.

The complete log is attached here [makeTrackValidationPlots.log](https://github.com/cms-sw/cmssw/files/7140180/makeTrackValidationPlots.log)

I also noticed with #34954, ` Validation/RecoTrack/python/plotting/validation.py` will start a large number of subprocesses simultaneously. Will it be better to add some args to limit the max number of the subprocesses?

**Comment by makortel** [comment]
assign dqm

FYI @vmariani @mmusich @lecriste

**Comment by lecriste** [comment]
@ChuyuanLiu the error seems to come from a line (1283, in `_doPlotsForPlotter`) introduced by [my PR](https://github.com/cms-sw/cmssw/pull/34954) [*], although I do not understand it.
I tested the code with `makeHGCalValidationPlots.py` and the number of forked subprocesses was always O(10).
Yes, we may limit the number of subprocesses forked simultaneously. Any recommendation from the expert?

[*]
```
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_0_pre2/bin/slc7_amd64_gcc900/makeTrackValidationPlots.py", line 146, in <module>
    main(opts)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_0_pre2/bin/slc7_amd64_gcc900/makeTrackValidationPlots.py", line 76, in main
    val.doPlots(trk, plotterDrawArgs=drawArgs, **kwargs_tracking)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_0_pre2/python/Validation/RecoTrack/plotting/validation.py", line 1261, in doPlots
    self._doPlotsForPlotter(plotter, sample, **kwargs)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_0_pre2/python/Validation/RecoTrack/plotting/validation.py", line 1283, in _doPlotsForPlotter
    if len(return_dict[i]) > 0:
  File "<string>", line 2, in __getitem__
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python3/3.9.6/lib/python3.9/multiprocessing/managers.py", line 824, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 109

```

**Comment by lecriste** [comment]
@ChuyuanLiu can you please test [this branch](#35319)?
