### ISSUE TITLE
[UBSAN] uninitiaized data member 

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#35538]
I am trying to debug the UBSAN errors [a] and I noticed that `EcalEBTrigPrimTestAlgo::theMapping_` is not initialized any where ( at least I can not find its ref any where in the cc file). @cms-sw/l1-l2 @cms-sw/upgrade-l2  any idea how this data member is suppose to initialize?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_12_1_X_2021-10-01-2300/
```
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:329:20: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:330:25: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:335:20: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:341:33: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:393:56: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
24 Geometry/EcalMapping/src/EcalElectronicsMapping.cc:394:67: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
```

**Comment by smuzaffar** [comment]
assign l1,upgrade

**Comment by smuzaffar** [comment]
here is stacktrace for these errors
```
/build/muz/ub/CMSSW_12_1_UBSAN_X_2021-10-01-2300/src/Geometry/EcalMapping/src/EcalElectronicsMapping.cc:329:20: runtime error: member call on misaligned address 0x3d4ccccd3d4ccccd for type 'const struct EcalElectronicsMapping', which requires 8 byte alignment
0x3d4ccccd3d4ccccd: note: pointer points here
<memory cannot be printed>
    #0 0x7ff7658c683e in EcalElectronicsMapping::getElectronicsId(DetId const&) const (/build/muz/ub/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libGeometryEcalMapping.so+0x9c83e)
    #1 0x7ff7658c6f9f in EcalElectronicsMapping::getTriggerElectronicsId(DetId const&) const (/build/muz/ub/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libGeometryEcalMapping.so+0x9cf9f)
    #2 0x7ff6640d7570 in EcalEBTrigPrimTestAlgo::run(EBDigiCollection const*, edm::SortedCollection<EcalEBTriggerPrimitiveDigi, edm::StrictWeakOrdering<EcalEBTriggerPrimitiveDigi> >&, edm::SortedCollection<EcalEBTriggerPrimitiveDigi, edm::StrictWeakOrdering<EcalEBTriggerPrimitiveDigi> >&) (/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libSimCalorimetryEcalEBTrigPrimAlgos.so+0x8f570)
    #3 0x7ff664301a2e in EcalEBTrigPrimProducer::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/pluginSimCalorimetryEcalEBTrigPrimProducersPlugins.so+0x1a4a2e)
    #4 0x7ff7ab34ab98 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libFWCoreFramework.so+0x2820b98)
    #5 0x7ff7ab1c0de3 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libFWCoreFramework.so+0x2696de3)
    #6 0x7ff7aa9c44de in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-10-01-2300/lib/slc7_amd64_gcc10/libFWCoreFramework.so+0x1e9a4de)
```

**Comment by Dr15Jones** [comment]
So the value for `theMapping` is never actually set in the class. It is defined here

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBTrigPrimTestAlgo.h#L127

and used here

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBTrigPrimTestAlgo.cc#L162

but never actually set.

As far as I can tell checking the history of that code, it has NEVER been set.

**Comment by Dr15Jones** [comment]
So this appears to work at all (at least some of the times) becuase for barrel IDs, the function being called does not use any member data of the class.

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/Geometry/EcalMapping/src/EcalElectronicsMapping.cc#L532-L559

**Comment by smuzaffar** [comment]
hopefully https://github.com/cms-sw/cmssw/pull/35544 should fix this. I just initialized the `theMapping_` data member ( just like the one done here https://cmssdt.cern.ch/lxr/source/L1TriggerConfig/L1ScalesProducers/src/L1CaloEcalScaleConfigOnlineProd.cc#0052 )

**Comment by thomreis** [comment]
Just initialising the member may make the UBSAN error go away but it will not give correct results neither. EcalElectronicsMapping should come from ES usually.

**Comment by smuzaffar** [comment]
thanks @thomreis for looking in to this. 
As @Dr15Jones mentioned https://github.com/cms-sw/cmssw/issues/35538#issuecomment-934483643 that none of the EcalElectronicsMapping data members are accessed during the call to `theMapping_->getTriggerElectronicsId(dataFrames[0].id());`  that is why simple  initialization of the member ( as done in  #35544) will not introduce any changes and will hide the UBSAN errors. Feel free to provide a proper fix with if simple initialization is not enough.

**Comment by thomreis** [comment]
Since this is a Phase 2 algo and there will be no endcap I guess this can stay with just a simple initialisation. The algo will be retired anyway once we have a proper TP emulation.
