### ISSUE TITLE
[ASAN] heap-buffer-overflow in ClusterGenerator::operator()

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#36057]
Log file: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_2_ASAN_X_2021-11-08-2300/unitTestLogs/RecoPixelVertexing/PixelVertexFinding#/

Error message:
```
==21053==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x606000036ef4 at pc 0x000000411d5d bp 0x7fff9ba811b0 sp 0x7fff9ba811a8
WRITE of size 2 at 0x606000036ef4 thread T0
    #0 0x411d5c in ClusterGenerator::operator()(Event&) .../src/RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h:72
    #1 0x405177 in main .../src/RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h:134
    #2 0x2acee6090554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    #3 0x40be68  (/cvmfs/cms-ib.cern.ch/nweek-02706/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_2_ASAN_X_2021-11-08-2300/test/slc7_amd64_gcc10/cpuVertexFinderByDensity_t+0x40be68)

0x606000036ef4 is located 0 bytes to the right of 52-byte region [0x606000036ec0,0x606000036ef4)
allocated by thread T0 here:
    #0 0x2acedc4383d7 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x40d39f in __gnu_cxx::new_allocator<unsigned short>::allocate(unsigned long, void const*) .../gcc/10.3.0/include/c++/10.3.0/ext/new_allocator.h:115
    #2 0x40d39f in std::allocator_traits<std::allocator<unsigned short> >::allocate(std::allocator<unsigned short>&, unsigned long) .../gcc/10.3.0/include/c++/10.3.0/bits/alloc_traits.h:460
    #3 0x40d39f in std::_Vector_base<unsigned short, std::allocator<unsigned short> >::_M_allocate(unsigned long) .../gcc/10.3.0/include/c++/10.3.0/bits/stl_vector.h:346
    #4 0x40d39f in std::vector<unsigned short, std::allocator<unsigned short> >::_M_default_append(unsigned long) .../gcc/10.3.0/include/c++/10.3.0/bits/vector.tcc:635
    #5 0x410b4d in std::vector<unsigned short, std::allocator<unsigned short> >::resize(unsigned long) .../gcc/10.3.0/include/c++/10.3.0/bits/stl_vector.h:940
    #6 0x410b4d in ClusterGenerator::operator()(Event&) .../src/RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h:62
    #7 0x405177 in main .../src/RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h:134
    #8 0x2acee6090554 in __libc_start_main (/lib64/libc.so.6+0x22554)

```

**Comment by iarspider** [comment]
assign reconstruction

**Comment by VinInn** [comment]
oops a "bug"
``` ev.itrack[nclus] = nt;```
should read 
``` ev.itrack[iv] = nt;```

**Comment by VinInn** [comment]
see above
