### ISSUE TITLE
[ASAN] new-delete-type-mismatch in FWModelChangeManager::newItemSlot

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#36056]
Log file: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_2_ASAN_X_2021-11-08-2300/unitTestLogs/Fireworks/Core#/4

Error message:
```
ERROR: AddressSanitizer: new-delete-type-mismatch on 0x6060004189a0 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   64 bytes;
  size of the deallocated type: 48 bytes.
    #0 0x2b17f59c61f7 in operator delete(void*, unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x2b17f68c45e2 in FWModelChangeManager::newItemSlot(FWEventItem*) (...lib/slc7_amd64_gcc10/libFireworksCore.so+0x5e25e2)
    #2 0x419a40 in changemanager::test_method() (...test/slc7_amd64_gcc10/TestFireworksCore+0x419a40)
    #3 0x423016 in changemanager_invoker() (...test/slc7_amd64_gcc10/TestFireworksCore+0x423016)
    #4 0x2b17fa66381d in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x3181d)
    #5 0x2b17fa662114 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x30114)
    #6 0x2b17fa662183 in boost::execution_monitor::execute(boost::function<int ()> const&) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x30183)
    #7 0x2b17fa662200 in boost::execution_monitor::vexecute(boost::function<void ()> const&) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x30200)
    #8 0x2b17fa68ef83 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x5cf83)
    #9 0x2b17fa669217 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) [clone .isra.0] (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x37217)
    #10 0x2b17fa6694e8 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) [clone .isra.0] (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x374e8)
    #11 0x2b17fa66d36f in boost::unit_test::framework::run(unsigned long, bool) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x3b36f)
    #12 0x2b17fa68dbe5 in boost::unit_test::unit_test_main(bool (*)(), int, char**) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x5bbe5)
    #13 0x2b17fd2ae554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    #14 0x416148  (...test/slc7_amd64_gcc10/TestFireworksCore+0x416148)

0x6060004189a0 is located 0 bytes inside of 64-byte region [0x6060004189a0,0x6060004189e0)
allocated by thread T0 here:
    #0 0x2b17f59c53d7 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x2b17f68c4396 in FWModelChangeManager::newItemSlot(FWEventItem*) (...lib/slc7_amd64_gcc10/libFireworksCore.so+0x5e2396)
    #2 0x419a40 in changemanager::test_method() (...test/slc7_amd64_gcc10/TestFireworksCore+0x419a40)
    #3 0x423016 in changemanager_invoker() (...test/slc7_amd64_gcc10/TestFireworksCore+0x423016)
    #4 0x2b17fa66381d in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (...external/slc7_amd64_gcc10/lib/libboost_unit_test_framework.so.1.75.0+0x3181d)
```

**Comment by iarspider** [comment]
assign visualization

**Comment by alja** [comment]
I'm looking into this.

**Comment by alja** [comment]
Do I need to have any special fags when running the test? 

I have project CMSSW_12_2_ASAN_X_2021-11-08-2300 build with SCRAM_ARCH slc7_amd64_gcc10. The 'scram b test` does not report anything in Fireworks/Core module.

**Comment by smuzaffar** [comment]
no special flags needed, just running it on  `CMSSW_12_2_ASAN_X_2021-11-08-2300` should be good

**Comment by alja** [comment]
@smuzaffar Thanks, I can see the error now. I had run scram runtests.

**Comment by alja** [comment]
@smuzaffar @Dr15Jones 
I debugged https://github.com/cms-sw/cmssw/blob/master/Fireworks/Core/test/unittest_changemanager.cc where the error comes from and later found out even a simple sigc::signal produces the same error. Here is a much simpler case: https://github.com/cms-sw/cmssw/blob/master/Fireworks/Core/test/unittest_changemanager.cc

I googled sigc new-delete-type-mismatch  and got this as the first hit:
https://github.com/libsigcplusplus/libsigcplusplus/issues/10

It is suggested to use sigc++-3.0 if I understand correctly.

**Comment by smuzaffar** [comment]
Thanks @alja. @ddaina can you please update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_2_X/master/sigcpp.spec to use latest 3.0.7 version.

**Comment by smuzaffar** [comment]
@alja , looks like fireworks needs changes for `sigc++-3.0 ` , see the build errors https://github.com/cms-sw/cmsdist/pull/7441#issuecomment-966174507

**Comment by alja** [comment]
@smuzaffar Thank you! I will look into it.
