### ISSUE TITLE
[ASAN] Possible stack-buffer-overflow in cms::Exception constructor

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#36072]
Command: `$ cmsRun src/FWCore/Integration/test/CatchStdExceptiontest_cfg.py` (part of FWCore/Integration unit tests)

Log :
```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 10-Nov-2021 12:20:12.880 CET
==25975==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
==25975==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7ffef4063000; bottom 0x7f2cedf4d000; size: 0x00d206116000 (902044934144)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
=================================================================
==25975==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f2cedf4e8d8 at pc 0x7f2d0e11e650 bp 0x7f2cedf4e710 sp 0x7f2cedf4e708
WRITE of size 8 at 0x7f2cedf4e8d8 thread T0
    #0 0x7f2d0e11e64f in cms::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (.../lib/slc7_amd64_gcc10/libFWCoreUtilities.so+0x4264f)
    #1 0x7f2d0e11515d in edm::Exception::Exception(edm::errors::ErrorCodes) (.../lib/slc7_amd64_gcc10/libFWCoreUtilities.so+0x3915d)
    #2 0x7f2d0e112d02 in edm::convertException::stdToEDM(std::exception const&) (.../lib/slc7_amd64_gcc10/libFWCoreUtilities.so+0x36d02)
    #3 0x7f2cee3e8fc0 in decltype ({parm#1}()) edm::convertException::wrap<edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}>(edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}) .../src/FWCore/Utilities/interface/ConvertException.h:26
    #4 0x7f2cee3e9292 in edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const /build/razumov/CMSSW_12_2_ASAN_X_2021-11-08-2300/src/FWCore/Framework/interface/Callback.h:190
    #5 0x7f2cee3ef6bc in void edm::SerialTaskQueueChain::actionToRun<edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&>(edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&) .../src/FWCore/Concurrency/interface/SerialTaskQueueChain.h:113
    #6 0x7f2cee3efc04 in edm::SerialTaskQueueChain::push<edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}>(tbb::detail::d1::task_group&, edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&&)::{lambda()#1}::operator()() .../src/FWCore/Concurrency/interface/SerialTaskQueueChain.h:78
    #7 0x7f2cee3efc04 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}>(tbb::detail::d1::task_group&, edm::eventsetup::Callback<edmtest::DoodadESProducer, std::unique_ptr<edmtest::Doodad, std::default_delete<edmtest::Doodad> >, GadgetRcd, edm::eventsetup::CallbackSimpleDecorator<GadgetRcd> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&&)::{lambda()#1}>::execute() .../src/FWCore/Concurrency/interface/SerialTaskQueue.h:175
    #8 0x7f2d0e261344 in tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (.../lib/slc7_amd64_gcc10/libFWCoreConcurrency.so+0xa344)
    #9 0x7f2d0cc237da in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::coroutine_waiter>(tbb::detail::d1::task*, tbb::detail::r1::coroutine_waiter&) .../external/tbb/v2021.4.0-544b7b2b990e0660abde669a014ec673/tbb-v2021.4.0/src/tbb/task_dispatcher.h:322
    #10 0x7f2d0cc237da in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::coroutine_waiter>(tbb::detail::d1::task*, tbb::detail::r1::coroutine_waiter&) .../external/tbb/v2021.4.0-544b7b2b990e0660abde669a014ec673/tbb-v2021.4.0/src/tbb/task_dispatcher.h:463
    #11 0x7f2d0cc237da in tbb::detail::r1::task_dispatcher::co_local_wait_for_all() .../external/tbb/v2021.4.0-544b7b2b990e0660abde669a014ec673/tbb-v2021.4.0/src/tbb/task_dispatcher.cpp:216
    #12 0x7f2d0cc237da in tbb::detail::r1::co_local_wait_for_all(unsigned int, unsigned int) .../external/tbb/v2021.4.0-544b7b2b990e0660abde669a014ec673/tbb-v2021.4.0/src/tbb/task_dispatcher.cpp:200
    #13 0x7f2d0ba8d18f  (/lib64/libc.so.6+0x4818f)

Address 0x7f2cedf4e8d8 is a wild pointer.
SUMMARY: AddressSanitizer: stack-buffer-overflow (.../lib/slc7_amd64_gcc10/libFWCoreUtilities.so+0x4264f) in cms::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Shadow bytes around the buggy address:
  0x0fe61dbe1cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe61dbe1cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe61dbe1ce0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x0fe61dbe1cf0: f1 f1 01 f2 01 f2 01 f2 01 f3 f3 f3 00 00 f8 f2
  0x0fe61dbe1d00: 00 00 f8 f2 00 00 f8 f2 f1 f1 f1 f1 00 00 f8 f2
=>0x0fe61dbe1d10: 00 00 f8 f2 00 00 f8 f2 00 00 f8[f2]00 00 f8 f2
  0x0fe61dbe1d20: 00 00 f8 f2 00 00 f8 f2 00 00 f8 f2 00 00 f8 f2
  0x0fe61dbe1d30: 00 00 f8 f2 f2 f2 00 00 f2 f2 00 00 f2 f2 f8 f8
  0x0fe61dbe1d40: f2 f2 00 00 f2 f2 f8 f8 00 00 00 f3 f3 f3 f3 f3
  0x0fe61dbe1d50: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe61dbe1d60: 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 f2 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==25975==ABORTING
```

**Comment by iarspider** [comment]
assign core

**Comment by akritkbehera** [comment]
We can close this
