### ISSUE TITLE
segfaults in RPCDcsInfoClient::dqmEndJob()

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#36190]
Several IBs have segfaults in `RPCDcsInfoClient::dqmEndJob()`, for example

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/cc8_amd64_gcc9/CMSSW_12_2_X_2021-11-19-2300/pyRelValMatrixLogs/run/136.829_RunDoubleEG2017F+RunDoubleEG2017F+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017/step4_RunDoubleEG2017F+RunDoubleEG2017F+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017.log

```
A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Sat Nov 20 06:23:26 CET 2021
Thread 1 (Thread 0x2b6dcc8167c0 (LWP 3741) "cmsRun"):
#3  0x00002b6dd061f79b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02707/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_2_X_2021-11-17-2300/lib/cc8_amd64_gcc9/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b6e4ef1bac7 in RPCDcsInfoClient::dqmEndJob(dqm::implementation::IBooker&, dqm::implementation::IGetter&) () from /cvmfs/cms-ib.cern.ch/nweek-02707/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_2_X_2021-11-17-2300/lib/cc8_amd64_gcc9/pluginDQMRPCMonitorClient_plugins.so
#6  0x00002b6e4ef0a884 in non-virtual thunk to DQMEDHarvester::endProcessBlockProduce(edm::ProcessBlock&) () from /cvmfs/cms-ib.cern.ch/nweek-02707/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_2_X_2021-11-17-2300/lib/cc8_amd64_gcc9/pluginDQMRPCMonitorClient_plugins.so
#7  0x00002b6dc93d71d8 in edm::one::EDProducerBase::doEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02707/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_2_X_2021-11-17-2300/lib/cc8_amd64_gcc9/libFWCoreFramework.so

Current Modules:

Module: RPCDcsInfoClient:rpcDcsInfoClient (crashed)

A fatal system signal has occurred: segmentation violation
```

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by perrotta** [comment]
See also https://github.com/cms-sw/cmssw/issues/36188#issuecomment-974610181

**Comment by jfernan2** [comment]
related to https://github.com/cms-sw/cmssw/pull/35678
@kskovpen

**Comment by jfernan2** [comment]
+1
