### ISSUE TITLE
CMSSW profiling jobs failing for 12.3.X

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#36504]
cmssw profiling jobs [a] is failing for 12.3.X IBs.  Any idea whats changed for 12.3.X which causes this error?
@gartung , can you please look in to it?

[a] https://cmssdt.cern.ch/jenkins/job/ib-run-profiling
```
+ runTheMatrix.py -w upgrade -l 23434.21 '--command=--number=20 --nThreads=1 --no_exec --dirin=/data/cmsbld/jenkins/workspace/ib-run-profiling --dirout=/data/cmsbld/jenkins/workspace/ib-run-profiling'
ignoring non-requested file relval_standard
ignoring non-requested file relval_highstats
ignoring non-requested file relval_pileup
ignoring non-requested file relval_generator
ignoring non-requested file relval_extendedgen
ignoring non-requested file relval_production
ignoring non-requested file relval_ged
processing relval_upgrade
ERROR reading file: relval_upgrade 'HARVESTFakeHLT_trackingMkFit_2017'
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-profiling/CMSSW_12_3_X_2021-12-14-2300/bin/slc7_amd64_gcc900/runTheMatrix.py", line 598, in <module>
    ret = runSelected(opt)
  File "/data/cmsbld/jenkins/workspace/ib-run-profiling/CMSSW_12_3_X_2021-12-14-2300/bin/slc7_amd64_gcc900/runTheMatrix.py", line 23, in runSelected
    mrd.prepare(opt.useInput, opt.refRel, opt.fromScratch)
  File "/data/cmsbld/jenkins/workspace/ib-run-profiling/CMSSW_12_3_X_2021-12-14-2300/python/Configuration/PyReleaseValidation/MatrixReader.py", line 506, in prepare
    self.readMatrix(matrixFile, useInput, refRel, fromScratch)
  File "/data/cmsbld/jenkins/workspace/ib-run-profiling/CMSSW_12_3_X_2021-12-14-2300/python/Configuration/PyReleaseValidation/MatrixReader.py", line 251, in readMatrix
    if self.relvalModule.steps[stepName] is None:
KeyError: 'HARVESTFakeHLT_trackingMkFit_2017'
```

**Comment by mmusich** [comment]
to solve this, PR #36477 is needed (see also #36347 (comment))

**Comment by smuzaffar** [comment]
closing it as it is kind of duplicate of #36347.   #36477 should fix this
