### ISSUE TITLE
int overrun in L1GctJetFinderBase

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#36647]
The undefined behavior santizer found a large number of int overruns similar to 

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/6e279b6b366a3ea3c208a11ba8482b41/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/src/L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc:580:19: runtime error: signed integer overflow: 268432611 * 157 cannot be represented in type 'int'
    #0 0x2b9ac5d55dab in L1GctTwosComplement<17> L1GctJetFinderBase::etComponentForJetFinder<12, 17>(L1GctUnsignedInt<12> const&, unsigned int const&, L1GctUnsignedInt<12> const&, unsigned int const&) (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x451dab)
    #1 0x2b9ac5d23d74 in L1GctJetFinderBase::doEtSums() (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x41fd74)
    #2 0x2b9ac5d3fc19 in L1GctJetFinderBase::doEnergySums() (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x43bc19)
    #3 0x2b9ac5d7bed4 in L1GctJetLeafCard::process() (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x477ed4)
    #4 0x2b9ac5e35b9c in L1GlobalCaloTrigger::bxProcess(int) (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x531b9c)
    #5 0x2b9ac5e925a4 in L1GlobalCaloTrigger::process() (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/libL1TriggerGlobalCaloTrigger.so+0x58e5a4)
    #6 0x2b9ac56b4fcf in L1GctEmulator::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/nweek-02713/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_UBSAN_X_2021-12-31-2300/lib/slc7_amd64_gcc11/pluginL1TriggerGlobalCaloTriggerPlugins.so+0x183fcf)

```

**Comment by makortel** [comment]
assign l1

**Comment by Dr15Jones** [comment]
The problematic line of code is

https://github.com/cms-sw/cmssw/blob/1dfba46f661289c7c316780ba0364dfba589502f/L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc#L570

where `myFactor` comes from

https://github.com/cms-sw/cmssw/blob/1dfba46f661289c7c316780ba0364dfba589502f/L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc#L563-L567

and `factors` is
https://github.com/cms-sw/cmssw/blob/1dfba46f661289c7c316780ba0364dfba589502f/L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc#L533-L551

with maxFactor being calculated from the first template argument (kBitsInput == 12) 
https://github.com/cms-sw/cmssw/blob/1dfba46f661289c7c316780ba0364dfba589502f/L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc#L521-L525

so maxFactor == 2^ (15+1+12) == 2^(28)

Given that on the platforms we use `int` can hold at most a value of size 2^31 means you can't multiple a value about the size of `maxFactor` by a value larger than 8. In the example above, we are multiplying it by 157.

This behavior is bad since overflowing an int value (in contrast to overflowing an unsigned int) is declared as 'undefined behavior' in the C++ standard. That means the value is allowed to change between compiles, between compiler versions, between different compile time options of the compiler or even run to run of the function.

What is the actual behavior this function is supposed to do?

**Comment by qliphy** [comment]
@Dr15Jones  Any comment on the fix in #37487 ?

@cecilecaillol   Do you have answers to "What is the actual behavior this function is supposed to do?"  ?

**Comment by perrotta** [comment]
Addressed and fixed in #37487

**Comment by cecilecaillol** [comment]
+l1
