### ISSUE TITLE
Check that RefCore works well with RepeatingCachedRootSource

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#36670]
From tests by @gartung we have some evidence that `RefCore` might not (always?) work well with `RepeatingCachedRootSource`. We should add tests to make sure that this works.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
For future reference here is a stack trace from a crash
```
#3  0x00007fdeed9977ab in sig_dostack_then_abort () from .../cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007ffd4c9f6250 in ?? ()
#6  0x00007fdef8d334b8 in edm::RefCore::tryToGetProductPtr(std::type_info const&, edm::EDProductGetter const*) const () from .../cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/lib/slc7_amd64_gcc900/libDataFormatsCommon.so
#7  0x00007fde5b2f6a01 in MuonAssociatorByHitsHelper::associateRecoToSimIndices(std::vector<std::pair<__gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > >, __gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > > >, std::allocator<std::pair<__gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > >, __gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > > > > > const&, edm::RefVector<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > const&, MuonAssociatorByHitsHelper::Resources const&) const () from /global/homes/g/gartung/m3897/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/lib/slc7_amd64_gcc900/libSimMuonMCTruth.so\
#8  0x00007fde5b385a43 in MuonToTrackingParticleAssociatorByHitsImpl::associateMuons(std::map<edm::RefToBase<reco::Muon>, std::vector<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double>, std::allocator<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double> > >, reco::RefToBaseSort, std::allocator<std::pair<edm::RefToBase<reco::Muon> const, std::vector<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double>, std::allocator<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double> > > > > >&, std::map<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, std::vector<std::pair<edm::RefToBase<reco::Muon>, double>, std::allocator<std::pair<edm::RefToBase<reco::Muon>, double> > >, std::less<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > >, std::allocator<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > const, std::vector<std::pair<edm::RefToBase<reco::Muon>, double>, std::allocator<std::pair<edm::RefToBase<reco::Muon>, double> > > > > >&, edm::RefToBaseVector<reco::Muon> const&, reco::MuonTrackType, edm::RefVector<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > const&) const () from .../cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/lib/slc7_amd64_gcc900/pluginSimMuonMCTruthPlugins.so
#9  0x00007fde5b37656e in MuonSimClassifier::produce(edm::Event&, edm::EventSetup const&) () from .../cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/lib/slc7_amd64_gcc900/pluginSimMuonMCTruthPlugins.so
```

**Comment by makortel** [comment]
Addressed in https://github.com/cms-sw/cmssw/pull/36864

**Comment by makortel** [comment]
+1
