### ISSUE TITLE
crash in edm::checkForModuleDependencyCorrectness

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#36726]
Instantiating a `TriggerResultsFilter` in `HLT_SomePath` that depends on the status (as in `HLTPathStatus`) of the path `HLT_SomePath` itself, causes a segmentation fault in `edm::checkForModuleDependencyCorrectness` instead of the usual nice error message about cyclic dependencies:
```
...
#4  <signal handler called>
#5  0x00002ad6ce71bf44 in void std::vector<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo, std::allocator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo> >::_M_realloc_insert<unsigned int&, unsigned int&>(__gnu_cxx::__normal_iterator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo*, std::vector<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo, std::allocator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo> > >, unsigned int&, unsigned int&) [clone .constprop.0] () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#6  0x00002ad6ce720a8c in edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#7  0x00002ad6ce68c1a0 in edm::EventProcessor::beginJob() () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
...
```

To reproduce, use the PR at https://github.com/cms-sw/cmssw/pull/36725 .

**Comment by fwyzard** [comment]
assign core

**Comment by makortel** [comment]
assign core

**Comment by Dr15Jones** [comment]
I was able to reproduce the problem with the pull request. I have determined the underlying problem and have made a unit test that replicates the problem. A pull request with a fix is coming soon.
