### ISSUE TITLE
ibmminsky-3 cvmfs problem

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#36993]
We're getting a lot of ppc IB failures of the form
```
#3  0x000010000a0702ec in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02720/slc7_ppc64le_gcc11/cms/cmssw/CMSSW_12_3_X_2022-02-15-2300/lib/slc7_ppc64le_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000100833b78440 in CovarianceParameterization::load(int) () from /cvmfs/cms-ib.cern.ch/nweek-02720/slc7_ppc64le_gcc11/cms/cmssw/CMSSW_12_3_X_2022-02-15-2300/lib/slc7_ppc64le_gcc11/libDataFormatsPatCandidates.so
#6  0x0000100833bf9ff0 in std::once_flag::_Prepare_execution::_Prepare_execution<std::call_once<pat::PackedCandidate::covarianceParameterization() const::{lambda(int)#1}, unsigned short const&>(std::once_flag&, pat::PackedCandidate::covarianceParameterization() const::{lambda(int)#1}&&, unsigned short const&)::{lambda()#1}>(pat::PackedCandidate::covarianceParameterization() const::{lambda(int)#1}&)::{lambda()#1}::_FUN() () from /cvmfs/cms-ib.cern.ch/nweek-02720/slc7_ppc64le_gcc11/cms/cmssw/CMSSW_12_3_X_2022-02-15-2300/lib/slc7_ppc64le_gcc11/libDataFormatsPatCandidates.so
#7  0x0000100002862f14 in std::__once_proxy () at ../../../../../libstdc++-v3/src/c++11/mutex.cc:41
#8  0x0000100002b560cc in __pthread_once_slow () from /lib64/libpthread.so.0
#9  0x0000100833bf5154 in pat::PackedCandidate::unpackCovariance() const () from /cvmfs/cms-ib.cern.ch/nweek-02720/slc7_ppc64le_gcc11/cms/cmssw/CMSSW_12_3_X_2022-02-15-2300/lib/slc7_ppc64le_gcc11/libDataFormatsPatCandidates.so
```
The problem seems to be cvmfs corruption on ibmminsky-3 with a ROOT input file on cvmfs appearing to be empty--compare:
```
[cmsbuild@ibmminsky-3 data]$ file /cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root 
/cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root: data
```
vs
```
[cmsbuild@ibmminsky-1 data]$ file /cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root
/cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root: ROOT file Version 60601 (Compression: 1)
```

**Comment by smuzaffar** [comment]
this machine has cvmfs issue which are fixed now. Next set of tests should not have this problem.

**Comment by dan131riley** [comment]
> this machine had cvmfs issue which are fixed now. Next set of tests should not have this problem.

That file still looks bad, and seems to be inconsistently bad, sometimes it's full of NUL characters, and sometimes it's completely empty:
```
[cmsbuild@ibmminsky-3 ~]$ file /cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root
/cvmfs/cms-ib.cern.ch/nweek-02720/share/cms/data-DataFormats-PatCandidates/V01-01-00-0c66824c8ee167448600b94b9abe533a/DataFormats/PatCandidates/data/CovarianceParameterization_version1.root: empty
```

**Comment by smuzaffar** [comment]
ah right, yes look like cvmfs cache is really corrupt. I a,m disabling this node in jenkins and ask openlab to fix the issue. Thanks for reporting

**Comment by smuzaffar** [comment]
cvmfs cache is wiped out on this node and it looks good now.

**Comment by smuzaffar** [comment]
clsoing this issue as cvmfs cache was fixed for ibmminsky-3
