### ISSUE TITLE
heap-buffer-overflow in l1t::stage2::CaloLayer1Packer::makeHCalTPGs()

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#37012]
We're getting heap-buffer-overflows in the ASAN builds for `l1t::stage2::CaloLayer1Packer::makeHCalTPGs()`, probably related to #36919 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc11/CMSSW_12_3_ASAN_X_2022-02-18-1100/pyRelValMatrixLogs/run/39834.0_TTbar_14TeV+2026D89+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step2_TTbar_14TeV+2026D89+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log

```
=================================================================
==12552==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x633002580b08 at pc 0x2ac908dfa2c9 bp 0x2ac90170e880 sp 0x2ac90170e878
READ of size 4 at 0x633002580b08 thread T4
    #0 0x2ac908dfa2c8 in l1t::stage2::CaloLayer1Packer::makeHCalTPGs(unsigned int, UCTCTP7RawData&, edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginEventFilterL1TRawToDigiAuto.so+0x2ad2c8)
    #1 0x2ac908dfc6b6 in l1t::stage2::CaloLayer1Packer::pack(edm::Event const&, l1t::PackerTokens const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginEventFilterL1TRawToDigiAuto.so+0x2af6b6)
    #2 0x2ac908c33db5 in l1t::L1TDigiToRaw::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginEventFilterL1TRawToDigiAuto.so+0xe6db5)
    #3 0x2ac871ba6017 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x8cf017)
    #4 0x2ac871b3faa4 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x868aa4)
    #5 0x2ac8718342c4 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x55d2c4)
    #6 0x2ac871834e33 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x55de33)
    #7 0x2ac871840af9 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x569af9)
    #8 0x2ac8708e81f1 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreConcurrency.so+0x111f1)
    #9 0x2ac873b455bb in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/task_dispatcher.h:322
    #10 0x2ac873b455bb in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/task_dispatcher.h:463
    #11 0x2ac873b455bb in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/arena.cpp:138
    #12 0x2ac873b455bb in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/market.cpp:597
    #13 0x2ac873b476d3 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:267
    #14 0x2ac873b476d3 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:221
    #15 0x2ac87477fea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #16 0x2ac874a92b0c in clone (/lib64/libc.so.6+0xfeb0c)

0x633002580b08 is located 8 bytes to the right of 99072-byte region [0x633002568800,0x633002580b00)
allocated by thread T4 here:
    #0 0x2ac8709b5d07 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x2ac90667bc3c in edm::Wrapper<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > >::Wrapper(std::unique_ptr<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> >, std::default_delete<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > > >) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginHLTriggerspecialAuto.so+0x239c3c)
    #2 0x2ac90669b0f8 in edm::OrphanHandle<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > > edm::Event::putImpl<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > >(unsigned int, std::unique_ptr<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> >, std::default_delete<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > > >) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginHLTriggerspecialAuto.so+0x2590f8)
    #3 0x2ac9138a6249 in edm::OrphanHandle<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > > edm::Event::put<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > >(std::unique_ptr<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> >, std::default_delete<edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > > >) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginSimCalorimetryHcalTrigPrimProducersPlugins.so+0xaa249)
    #4 0x2ac9138661eb in HcalTrigPrimDigiProducer::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginSimCalorimetryHcalTrigPrimProducersPlugins.so+0x6a1eb)
    #5 0x2ac871ba6017 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x8cf017)
    #6 0x2ac871b3faa4 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x868aa4)
    #7 0x2ac8718342c4 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x55d2c4)
    #8 0x2ac871834e33 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x55de33)
    #9 0x2ac871840af9 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x569af9)
    #10 0x2ac8708e81f1 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/libFWCoreConcurrency.so+0x111f1)
    #11 0x2ac873b455bb in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/task_dispatcher.h:322
    #12 0x2ac873b455bb in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/task_dispatcher.h:463
    #13 0x2ac873b455bb in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/arena.cpp:138
    #14 0x2ac873b455bb in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/market.cpp:597
    #15 0x2ac873b476d3 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:267
    #16 0x2ac873b476d3 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:221

Thread T4 created by T2 here:
    #0 0x2ac87095c526 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x2ac873b46dfb in tbb::detail::r1::rml::internal::thread_monitor::launch(void* (*)(void*), void*, unsigned long) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/rml_thread_monitor.h:208
    #2 0x2ac873b46dfb in tbb::detail::r1::rml::private_worker::wake_or_launch() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:299
    #3 0x2ac873b46dfb in tbb::detail::r1::rml::private_server::wake_some(int) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:407

Thread T2 created by T0 here:
    #0 0x2ac87095c526 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x2ac873b46dfb in tbb::detail::r1::rml::internal::thread_monitor::launch(void* (*)(void*), void*, unsigned long) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/rml_thread_monitor.h:208
    #2 0x2ac873b46dfb in tbb::detail::r1::rml::private_worker::wake_or_launch() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:299
    #3 0x2ac873b46dfb in tbb::detail::r1::rml::private_server::wake_some(int) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/slc7_amd64_gcc11/external/tbb/v2021.4.0-a1ac0a4b6fb3ff931b4e97030094b2d8/tbb-v2021.4.0/src/tbb/private_server.cpp:407

SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/nweek-02720/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_3_ASAN_X_2022-02-18-1100/lib/slc7_amd64_gcc11/pluginEventFilterL1TRawToDigiAuto.so+0x2ad2c8) in l1t::stage2::CaloLayer1Packer::makeHCalTPGs(unsigned int, UCTCTP7RawData&, edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> > const*)
Shadow bytes around the buggy address:
  0x0c66804a8110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c66804a8120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c66804a8130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c66804a8140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c66804a8150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c66804a8160: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c66804a8170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c66804a8180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c66804a8190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c66804a81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c66804a81b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==12552==ABORTING
```

**Comment by makortel** [comment]
assign l1

**Comment by qliphy** [comment]
@gk199 @cms-sw/l1-l2  Any follow up on this?  Thanks!

https://github.com/cms-sw/cmssw/pull/36919#issuecomment-1047976919

**Comment by gk199** [comment]
(also updated on PR #36919) 
Neither the initial suggested fix, nor further modifications I tried, resolved the issue. Will continue looking at this, and guidance from L1 will be much appreciated.

**Comment by perrotta** [comment]
Fixed by https://github.com/cms-sw/cmssw/pull/37257, with backport to 12_3_X in https://github.com/cms-sw/cmssw/pull/37253
This issue can be closed then, pleae @dan131riley or anyone else comment if you want to let it open
