### ISSUE TITLE
`o2oRun_SiStripDAQ.py` not fully migrated to py3

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#37228]
Title say it all, blocks SiStrip DAQ O2Os in 12.2.X: 

Upon trial, results in:

```console
Traceback (most recent call last):
  File "/opt/offline/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_1/bin/slc7_amd64_gcc900/o2oRun_SiStripDAQ.py", line 135, in main
    is_ok, status = run(args)
  File "/opt/offline/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_1/bin/slc7_amd64_gcc900/o2oRun_SiStripDAQ.py", line 59, in run
    for line in log.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```
occurring here:

https://github.com/cms-sw/cmssw/blob/3005f891815094a28c4562ba49ac54bbeec46eb6/CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py#L59

cc:
@quinnanm @rgerosa

**Comment by mmusich** [comment]
assign db

**Comment by mmusich** [comment]
assign tracker-dpg

**Comment by tvami** [comment]
Hi Marco, how does one test this? I think the solution is simply what I put in https://github.com/cms-sw/cmssw/pull/37230

**Comment by tvami** [comment]
> Hi Marco, how does one test this? I think the solution is simply what I put in #37230

I'd need a config file for testing, is that available somewhere?

**Comment by francescobrivio** [comment]
@tvami since the issue reported by Marco is in a different line wrt your fix, maybe we could try what [this stacktracke issue](https://stackoverflow.com/questions/48169667/how-to-handle-subprocess-popen-output-in-both-python-2-and-python-3) suggests, i.e. to add `.decode()` after `communicate()[0]` in py3.
(But I'm also not sure how to test it...)

**Comment by tvami** [comment]
Yeah I think both direction could work, in mine you dont open the file in a bitwise manner, while in yours you decode it. 

For testing, for now I'd do
```
CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py --debug True --db dev CondTools/SiStrip/ 1 /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_1/src/CondTools/SiStrip/python/SiStripDCS_popcon.py
```

based on https://cms-conddb.cern.ch/cmsDbBrowser/logs/show_O2O_log/Prod/SiStripDetVOff_1hourDelay/2022-03-13%2022:05:21.285959

but it would be nice to have a confirmation from the Strips O2O experts.

**Comment by tvami** [comment]
Ok I can successfully reproduce the problem with 
```
CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py 1 /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_1/src/CondTools/SiStrip/python/SiStripDCS_popcon.py --debug --db sqlite:test.db
```

and then apparently I need both your suggestion @francescobrivio  and mine to move on. But I think it works now

**Comment by tvami** [comment]
+db

**Comment by mmusich** [comment]
thanks @tvami. Please notice that in order to move the SiStrip O2O node to use 12.2.X a patch production release with #37236 included will be needed (even if at this point one could keep running the O2O in 11.1.X)

**Comment by mmusich** [comment]
+1 
   * for the record
   * a series of successful SiStrip-DAQ O2O with the newly available CMSSW release [CMSSW_12_2_1_patch2](https://github.com/cms-sw/cmssw/releases/CMSSW_12_2_1_patch2) was [performed this afternoon](https://cms-conddb.cern.ch/cmsDbBrowser/logs/O2O_logs/Prod/2022-03-15/2022-03-16/SiStrip/None)
