### ISSUE TITLE
[SKYLAKE_X] Segmentation violation in MuonShowerInformationFiller::fillHitsByStation (Relval 136.844)

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#37234]
Stacktrace:

```
#3  0x00002af07155b9ea in sig_dostack_then_abort () from .../lib/slc7_amd64_gcc10/haswell/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002af116308fa7 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi> >(__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, __gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi>) () from .../lib/slc7_amd64_gcc10/haswell/libRecoMuonMuonIdentification.so
#6  0x00002af11630949e in void std::__merge_sort_with_buffer<__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, std::shared_ptr<MuonTransientTrackingRecHit>*, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi> >(__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, __gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, std::shared_ptr<MuonTransientTrackingRecHit>*, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi>) () from .../lib/slc7_amd64_gcc10/haswell/libRecoMuonMuonIdentification.so
#7  0x00002af11630f5b7 in void std::__stable_sort_adaptive<__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, std::shared_ptr<MuonTransientTrackingRecHit>*, long, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi> >(__gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, __gnu_cxx::__normal_iterator<std::shared_ptr<MuonTransientTrackingRecHit>*, std::vector<std::shared_ptr<MuonTransientTrackingRecHit>, std::allocator<std::shared_ptr<MuonTransientTrackingRecHit> > > >, std::shared_ptr<MuonTransientTrackingRecHit>*, long, __gnu_cxx::__ops::_Iter_comp_iter<MuonShowerInformationFiller::LessPhi>) () from .../lib/slc7_amd64_gcc10/haswell/libRecoMuonMuonIdentification.so
#8  0x00002af1162fe320 in MuonShowerInformationFiller::fillHitsByStation(reco::Muon const&) () from .../lib/slc7_amd64_gcc10/haswell/libRecoMuonMuonIdentification.so
#9  0x00002af116300abb in MuonShowerInformationFiller::fillShowerInformation(reco::Muon const&, edm::Event const&, edm::EventSetup const&) () from .../lib/slc7_amd64_gcc10/haswell/libRecoMuonMuonIdentification.so
#10 0x00002af11625d9f3 in MuonShowerInformationProducer::produce(edm::Event&, edm::EventSetup const&) () from .../lib/slc7_amd64_gcc10/haswell/pluginRecoMuonMuonIdentificationPlugins.so
```

Full log: [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_SKYLAKEAVX512_X_2022-03-10-2300/pyRelValMatrixLogs/run/136.844_RunCharmonium2017B+RunCharmonium2017B+HLTDR2_2017+RECODR2_2017reHLT_skimCharmonium_Prompt+HARVEST2017_skimCharmonium/step3_RunCharmonium2017B+RunCharmonium2017B+HLTDR2_2017+RECODR2_2017reHLT_skimCharmonium_Prompt+HARVEST2017_skimCharmonium.log#/999)

**Comment by iarspider** [comment]
assign reconstruction

**Comment by jpata** [comment]
are there any instructions to reproduce? does it only crash on SKYLAKE, or other architectures too?

**Comment by dan131riley** [comment]
Previous discussion in #33663.

**Comment by jpata** [comment]
if this is the same issue as https://github.com/cms-sw/cmssw/issues/33663, perhaps we should move all discussion there and close this?
