### ISSUE TITLE
Use after scope in DMRChecker::bookResidualsHistogram

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#37765]
ASAN found a stack-use-after-scope in `DMRChecker::bookResidualsHistogram()`

```
==24226==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc446a3140 at pc 0x2b899569c8c7 bp 0x7ffc446a24c0 sp 0x7ffc446a1c70
READ of size 16 at 0x7ffc446a3140 thread T0
    #0 0x2b899569c8c6 in printf_common ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:553
    #1 0x2b899569e235 in __interceptor_vsnprintf ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1668
    #2 0x2b8997f25505 in Format(char const*, __va_list_tag*) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/external/slc7_amd64_gcc11/lib/libCore.so+0x1f3505)
    #3 0x2b8997f2a40b in Form(char const*, ...) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/external/slc7_amd64_gcc11/lib/libCore.so+0x1f840b)
    #4 0x2b89f0c9b6ff in DMRChecker::bookResidualsHistogram(TFileDirectory, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/lib/slc7_amd64_gcc11/pluginAlignmentOfflinevalidationPlugins.so+0x1dd6ff)
    #5 0x2b89f0cadffe in DMRChecker::beginJob() (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/lib/slc7_amd64_gcc11/pluginAlignmentOfflinevalidationPlugins.so+0x1efffe)
```

I think the problem may be here:

https://github.com/cms-sw/cmssw/blob/1481a9564a25d5a6a65c426cb387a81f2e7ba66c/Alignment/OfflineValidation/plugins/DMRChecker.cc#L1968-L1972

where `.c_str()` is called on temporary objects that  immediately go out of scope.  No idea why this wasn't noticed before, it doesn't look like that code has been changed recently.

**Comment by tvami** [comment]
@antoniovagnerini and Sandra (I didnt find her github handle), can you please have a look and fix this? Thanks!

**Comment by tvami** [comment]
Tho I really see @mmusich to be the developer of that package, he'll be back from vacation after Wednesday

**Comment by mmusich** [comment]
> No idea why this wasn't noticed before, it doesn't look like that code has been changed recently.

Because tests have been added only recently (at https://github.com/cms-sw/cmssw/pull/37621) exactly to catch that sort of things.

**Comment by tvami** [comment]
+alca
 * for the record
