### ISSUE TITLE
[ARM] Crash in edm::refitem::GetRefPtrImp

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#37821]
Workflow 25403.18 step 1 crashed in CMSSW_12_4_X_2022-05-04-2300 on el8_aarch64_gcc10
```
Thread 10 (Thread 0x40011f158490 (LWP 286236) "cmsRun"):
#2  0x0000400043304cf8 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000400324230d94 in QuickTrackAssociatorByHitsImpl::trackingParticleContainsIdentifier(TrackingParticle const*, std::pair<unsigned int, EncodedEventId> const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#5  0x0000400324231d28 in std::vector<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double>, std::allocator<std::pair<edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, double> > > QuickTrackAssociatorByHitsImpl::associateTrack<edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, __gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > > >(TrackerHitAssociator const&, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > > const&, edm::IndexSet const*, __gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > >, __gnu_cxx::__normal_iterator<TrackingRecHit* const*, std::vector<TrackingRecHit*, std::allocator<TrackingRecHit*> > >) const [clone .isra.0] () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#6  0x0000400324241dcc in edm::AssociationMap<edm::OneToManyWithQualityGeneric<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, edm::View<reco::Track>, double, unsigned int, edm::RefProd<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, edm::RefToBaseProd<reco::Track>, edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> >, edm::RefToBase<reco::Track> > > QuickTrackAssociatorByHitsImpl::associateSimToRecoImplementation<edm::Handle<edm::View<reco::Track> >, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, TrackerHitAssociator>(edm::Handle<edm::View<reco::Track> > const&, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > > const&, edm::IndexSet const*, TrackerHitAssociator) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#7  0x0000400324232a9c in QuickTrackAssociatorByHitsImpl::associateSimToReco(edm::Handle<edm::View<reco::Track> > const&, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > > const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#8  0x00004003242edc78 in TrackAssociatorEDProducer::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociation_plugins.so
#9  0x000040003f0b0c50 in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#10 0x000040003f0a798c in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#11 0x000040003f003a28 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#12 0x000040003f003d74 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#13 0x000040003f00653c in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#14 0x000040003f596ed8 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreConcurrency.so

Thread 9 (Thread 0x40011e748490 (LWP 286235) "cmsRun"):
#2  0x0000400043304cf8 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x000040011f52de58 in edm::AssociationMap<edm::OneToManyWithQualityGeneric<edm::View<reco::Track>, std::vector<TrackingParticle, std::allocator<TrackingParticle> >, double, unsigned int, edm::RefToBaseProd<reco::Track>, edm::RefProd<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, edm::RefToBase<reco::Track>, edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > > >::get(unsigned long) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginValidationRecoTrackPlugins.so
#5  0x000040011f518388 in MultiTrackValidator::dqmAnalyze(edm::Event const&, edm::EventSetup const&, MultiTrackValidatorHistograms const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginValidationRecoTrackPlugins.so
#6  0x000040003f0b0c50 in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#7  0x000040003f0a798c in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#8  0x000040003f003a28 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#9  0x000040003f003d74 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#10 0x000040003f00653c in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#11 0x000040003f596ed8 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreConcurrency.so

Thread 8 (Thread 0x40011dd38490 (LWP 286234) "cmsRun"):
#2  0x0000400043304cf8 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x000040005c446918 in CaloHitResponse::makeAnalogSignal(PCaloHit const&, CLHEP::HepRandomEngine*) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimCalorimetryCaloSimAlgos.so
#5  0x000040005c4463a4 in CaloHitResponse::add(PCaloHit const&, CLHEP::HepRandomEngine*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimCalorimetryCaloSimAlgos.so
#6  0x000040011f2d7938 in HcalDigitizer::accumulateCaloHits(edm::Handle<std::vector<PCaloHit, std::allocator<PCaloHit> > > const&, edm::Handle<std::vector<PCaloHit, std::allocator<PCaloHit> > > const&, int, CLHEP::HepRandomEngine*, HcalTopology const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimCalorimetryHcalSimProducers.so
#7  0x000040011f2d8454 in HcalDigitizer::accumulate(PileUpEventPrincipal const&, edm::EventSetup const&, CLHEP::HepRandomEngine*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimCalorimetryHcalSimProducers.so
#8  0x000040011c641634 in edm::MixingModule::accumulateEvent(PileUpEventPrincipal const&, edm::EventSetup const&, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimGeneralMixingModulePlugins.so
#9  0x000040011c64176c in edm::MixingModule::pileAllWorkers(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimGeneralMixingModulePlugins.so
#10 0x000040011c64beac in void edm::PileUp::readPileUp<std::_Bind<bool (edm::MixingModule::*(std::reference_wrapper<edm::MixingModule>, std::_Placeholder<1>, edm::ModuleCallingContext const*, int, std::_Placeholder<2>, int, std::reference_wrapper<edm::EventSetup const>, edm::StreamID))(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&)> >(edm::EventID const&, std::vector<edm::SecondaryEventIDAndFileInfo, std::allocator<edm::SecondaryEventIDAndFileInfo> >&, std::_Bind<bool (edm::MixingModule::*(std::reference_wrapper<edm::MixingModule>, std::_Placeholder<1>, edm::ModuleCallingContext const*, int, std::_Placeholder<2>, int, std::reference_wrapper<edm::EventSetup const>, edm::StreamID))(edm::EventPrincipal const&, edm::ModuleCallingContext const*, int, int, int&, edm::EventSetup const&, edm::StreamID const&)>, int, edm::StreamID const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimGeneralMixingModulePlugins.so
#11 0x000040011c6468c0 in edm::MixingModule::doPileUp(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimGeneralMixingModulePlugins.so
#12 0x000040011c6e0560 in edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libMixingBase.so
#13 0x000040003f0c38ac in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#14 0x000040003f0a7ecc in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#15 0x000040003f003a28 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#16 0x000040003f003d74 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#17 0x000040003f00653c in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#18 0x000040003f596ed8 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreConcurrency.so

Thread 1 (Thread 0x400040bcb730 (LWP 267672) "cmsRun"):
#3  0x0000400043308600 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000400324239d00 in edm::refitem::GetRefPtrImpl<std::vector<reco::TrackExtra, std::allocator<reco::TrackExtra> >, reco::TrackExtra, edm::refhelper::FindUsingAdvance<std::vector<reco::TrackExtra, std::allocator<reco::TrackExtra> >, reco::TrackExtra>, unsigned int>::getRefPtr_(edm::RefCore const&, unsigned int) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#6  0x00004003242411f8 in edm::AssociationMap<edm::OneToManyWithQualityGeneric<edm::View<reco::Track>, std::vector<TrackingParticle, std::allocator<TrackingParticle> >, double, unsigned int, edm::RefToBaseProd<reco::Track>, edm::RefProd<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, edm::RefToBase<reco::Track>, edm::Ref<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle, edm::refhelper::FindUsingAdvance<std::vector<TrackingParticle, std::allocator<TrackingParticle> >, TrackingParticle> > > > QuickTrackAssociatorByHitsImpl::associateRecoToSimImplementation<edm::Handle<edm::View<reco::Track> >, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > >, TrackerHitAssociator>(edm::Handle<edm::View<reco::Track> > const&, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > > const&, edm::IndexSet const*, TrackerHitAssociator) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#7  0x00004003242328ec in QuickTrackAssociatorByHitsImpl::associateRecoToSim(edm::Handle<edm::View<reco::Track> > const&, edm::Handle<std::vector<TrackingParticle, std::allocator<TrackingParticle> > > const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginSimTrackerTrackAssociatorProducersAuto.so
#8  0x000040011f64e560 in TrackHistory::newEvent(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimTrackerTrackHistory.so
#9  0x000040011f641544 in TrackClassifier::newEvent(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libSimTrackerTrackHistory.so
#10 0x0000400324fd07a0 in BDHadronTrackMonitoringAnalyzer::analyze(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/pluginValidationRecoBPlugins.so
#11 0x000040003f0c38ac in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#12 0x000040003f0a7ecc in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#13 0x000040003f003a28 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#14 0x000040003f003d74 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#15 0x000040003f00653c in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreFramework.so
#16 0x000040003f596ed8 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/nweek-02731/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-05-04-2300/lib/el8_aarch64_gcc10/libFWCoreConcurrency.so

Current Modules:
Module: BDHadronTrackMonitoringAnalyzer:BDHadronTrackMonitoringAnalyze (crashed)
Module: MultiTrackValidator:trackValidatorFromPVAllTP
Module: MixingModule:mix
Module: TrackAssociatorEDProducer:trackingParticleRecoTrackAsssociation
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc10/CMSSW_12_4_X_2022-05-04-2300/pyRelValMatrixLogs/run/25403.18_H125GGgluonfusion_13+FS_H125GGgluonfusion_13_UP18_PU50+HARVESTUP18FS+MINIAODMCUP18FS/step1_H125GGgluonfusion_13+FS_H125GGgluonfusion_13_UP18_PU50+HARVESTUP18FS+MINIAODMCUP18FS.log#/

**Comment by makortel** [comment]
assign core
