### ISSUE TITLE
[ASAN_X] RelVal 138.3 failed with SIGSEGV

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#37885]
Log file (not too useful): [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_12_4_ASAN_X_2022-05-09-1100/pyRelValMatrixLogs/run/138.3_Splashes+RunMinimumBias2021Splash+COPYPASTER3+RECODR3Splash+HARVESTDR3/step3_Splashes+RunMinimumBias2021Splash+COPYPASTER3+RECODR3Splash+HARVESTDR3.log#/)

I ran the workflow under gdb on cmsdev machine, and this is the backtrace I got: [link](https://gist.github.com/iarspider/30af2f77d4f60f5150282bd6838e1ecb)

Short version:
```
#0  0x00007fff65d9709b in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#1  0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#2  0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) ()
(...)
#8050 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8051 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8052 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8053 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8054 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8055 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8056 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8057 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8058 0x00007fff65d98621 in Basic2DGenericTopoClusterizer::buildTopoCluster(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, unsigned int, std::vector<bool, std::allocator<bool> >&, reco::PFCluster&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8059 0x00007fff65d9ac6a in Basic2DGenericTopoClusterizer::buildClusters(edm::Handle<std::vector<reco::PFRecHit, std::allocator<reco::PFRecHit> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<reco::PFCluster, std::allocator<reco::PFCluster> >&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8060 0x00007fff65e851eb in PFClusterProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/pluginRecoParticleFlowPFClusterProducerPlugins.so
#8061 0x00007ffff726d758 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so
#8062 0x00007ffff71f6fa5 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so
#8063 0x00007ffff6ee1e05 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so
#8064 0x00007ffff6ee2974 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so
#8065 0x00007ffff6eee63a in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so
#8066 0x00007ffff7e131f2 in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-05-09-1100/lib/slc7_amd64_gcc11/libFWCoreConcurrency.so
#8067 0x00007ffff4b3f51c in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter> (t=0x7fff9a8d3700, waiter=..., this=0x7fffee3d9480) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/task_dispatcher.h:322
#8068 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter> (t=0x0, waiter=..., this=0x7fffee3d9480) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/task_dispatcher.h:463
#8069 tbb::detail::r1::arena::process (tls=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/arena.cpp:138
#8070 tbb::detail::r1::market::process (this=<optimized out>, j=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/market.cpp:597
#8071 0x00007ffff4b41654 in tbb::detail::r1::rml::private_worker::run (this=0x7fffed250080) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/private_server.cpp:267
#8072 tbb::detail::r1::rml::private_worker::thread_routine (arg=0x7fffed250080) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/private_server.cpp:221
#8073 0x00007ffff3d07ea5 in start_thread () from /lib64/libpthread.so.0
#8074 0x00007ffff3a30b0d in clone () from /lib64/libc.so.6
```

Could be a recursion issue?

**Comment by iarspider** [comment]
assign reco

**Comment by iarspider** [comment]
assign reconstruction

**Comment by makortel** [comment]
Duplicate of #37362

**Comment by iarspider** [comment]
@makortel oops.
