### ISSUE TITLE
AddressSanitizer error in ASAN IB workflow 537.0

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#37972]
Hello,

We're getting `AddressSanitizer` errors when trying to free memory `attempting free on address which was not malloc()` in workflow 537.0 in ASAN builds. Here the stack trace:

```
==29592==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x602000256250 in thread T0
    #0 0x2af15f2d8b87 in operator delete(void*, unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x2af1a8c0aff8 in ThePEG::FxFxReader::scan() (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/external/herwig7/7.2.2-508f2744a3ce53ba7de69d51a3599055/lib/Herwig/HwFxFx.so+0x5aff8)
    #2 0x2af1a8c0ee77 in ThePEG::FxFxReader::initialize(ThePEG::FxFxEventHandler&) (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/external/herwig7/7.2.2-508f2744a3ce53ba7de69d51a3599055/lib/Herwig/HwFxFx.so+0x5ee77)
    #3 0x2af1a8be6838 in ThePEG::FxFxFileReader::initialize(ThePEG::FxFxEventHandler&) (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/external/herwig7/7.2.2-508f2744a3ce53ba7de69d51a3599055/lib/Herwig/HwFxFx.so+0x36838)
    #4 0x2af1a8bf3e69 in ThePEG::FxFxEventHandler::initialize() (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/external/herwig7/7.2.2-508f2744a3ce53ba7de69d51a3599055/lib/Herwig/HwFxFx.so+0x43e69)
    #5 0x2af19e525d9a in ThePEG::EventGenerator::doinit() (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x1f7d9a)
    #6 0x2af19e52a4ba in ThePEG::EventGenerator::setup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::set<ThePEG::Pointer::RCPtr<ThePEG::InterfacedBase>, std::less<ThePEG::Pointer::RCPtr<ThePEG::InterfacedBase> >, std::allocator<ThePEG::Pointer::RCPtr<ThePEG::InterfacedBase> > >&, std::map<long, ThePEG::Pointer::RCPtr<ThePEG::ParticleData>, std::less<long>, std::allocator<std::pair<long const, ThePEG::Pointer::RCPtr<ThePEG::ParticleData> > > >&, std::set<ThePEG::Pointer::RCPtr<ThePEG::MatcherBase>, std::less<ThePEG::Pointer::RCPtr<ThePEG::MatcherBase> >, std::allocator<ThePEG::Pointer::RCPtr<ThePEG::MatcherBase> > >&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x1fc4ba)
    #7 0x2af19e56e9ef in ThePEG::Repository::makeRun(ThePEG::Pointer::TransientRCPtr<ThePEG::EventGenerator>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x2409ef)
    #8 0x2af19e5721a4 in ThePEG::Repository::exec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::ostream&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x2441a4)
    #9 0x2af19e572cae in ThePEG::Repository::execAndCheckReply(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::ostream&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x244cae)
    #10 0x2af19e572f49 in ThePEG::Repository::read(std::istream&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x244f49)
    #11 0x2af19e5733ed in ThePEG::Repository::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::ostream&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libThePEG.so.30+0x2453ed)
    #12 0x2af17f44cefa in (anonymous namespace)::HerwigGenericRead(Herwig::HerwigUI const&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/external/slc7_amd64_gcc11/lib/libHerwigAPI.so.2+0x8efa)
    #13 0x2af1855e1317 in Herwig7Interface::callHerwigGenerator() (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libGeneratorInterfaceHerwig7Interface.so+0x1d317)
    #14 0x2af1855e9429 in Herwig7Interface::initRepository(edm::ParameterSet const&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libGeneratorInterfaceHerwig7Interface.so+0x25429)
    #15 0x2af17d05a6a6 in Herwig7Hadronizer::initializeForInternalPartons() (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/pluginGeneratorInterfaceHerwig7HadronizerPlugins.so+0x206a6)
    #16 0x2af17d08bca7 in edm::GeneratorFilter<Herwig7Hadronizer, gen::ExternalDecayDriver>::beginLuminosityBlockProduce(edm::LuminosityBlock&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/pluginGeneratorInterfaceHerwig7HadronizerPlugins.so+0x51ca7)
    #17 0x2af1604bfefe in edm::one::EDFilterBase::doBeginLuminosityBlock(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x8c6efe)
    #18 0x2af160453276 in edm::WorkerT<edm::one::EDFilterBase>::implDoBegin(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x85a276)
    #19 0x2af15ffb9bd1 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x3c0bd1)
    #20 0x2af15ffbaac9 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x3c1ac9)
    #21 0x2af15ffd23d5 in void edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x3d93d5)
    #22 0x2af15ffd2af4 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::detail::d1::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x3d9af4)
    #23 0x2af15f209344 in tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreConcurrency.so+0xa344)
    #24 0x2af1624b9ae8 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/task_dispatcher.h:322
    #25 0x2af1624b9ae8 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/task_dispatcher.h:463
    #26 0x2af1624b9ae8 in tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/task_dispatcher.cpp:168
    #27 0x2af15fe9f03b in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x2a603b)
    #28 0x2af15fed23f0 in edm::EventProcessor::runToCompletion() (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCoreFramework.so+0x2d93f0)
    #29 0x40e711 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/bin/slc7_amd64_gcc11/cmsRun+0x40e711)
    #30 0x2af1624a78a7 in tbb::detail::r1::task_arena_impl::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_0_pre2-slc7_amd64_gcc11/build/CMSSW_12_4_0_pre2-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.5.0-9cee443edc603791565ef91dfd9ef546/tbb-v2021.5.0/src/tbb/arena.cpp:698
    #31 0x411e7f in main::{lambda()#1}::operator()() const (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/bin/slc7_amd64_gcc11/cmsRun+0x411e7f)
    #32 0x40c615 in main (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/bin/slc7_amd64_gcc11/cmsRun+0x40c615)
    #33 0x2af163324554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    #34 0x40c968  (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/bin/slc7_amd64_gcc11/cmsRun+0x40c968)

0x602000256250 is located 16 bytes to the right of 16-byte region [0x602000256230,0x602000256240)
allocated by thread T0 here:
    #0 0x2af15f2d7d07 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x2af1607bdfa2 in void std::vector<double, std::allocator<double> >::_M_realloc_insert<double>(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double&&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libFWCorePythonParameterSet.so+0x13afa2)
    #2 0x2af18d306e3c in double& std::vector<double, std::allocator<double> >::emplace_back<double>(double&&) (/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_ASAN_X_2022-05-16-1100/lib/slc7_amd64_gcc11/libDetectorDescriptionParser.so+0x5fe3c)
    #3 0x2af1a8c0ab62 in ThePEG::FxFxReader::scan() (/cvmfs/cms-ib.cern.ch/nweek-02733/slc7_amd64_gcc11/external/herwig7/7.2.2-508f2744a3ce53ba7de69d51a3599055/lib/Herwig/HwFxFx.so+0x5ab62)

SUMMARY: AddressSanitizer: bad-free ../../../../libsanitizer/asan/asan_new_delete.cpp:172 in operator delete(void*, unsigned long)
==29592==ABORTING
```

**Comment by makortel** [comment]
Looks like a duplicate of https://github.com/cms-sw/cmssw/issues/36646

**Comment by aandvalenzuela** [comment]
Ups, sorry! My bad
