### ISSUE TITLE
CMSSW_12_5_2_patch1 crash for HI runs

### ISSUE THREAD

**Issue by pmandrik** [cms-sw/cmssw#40111]
Many DQM clients crashed for recent HI runs [362296](https://cmsweb.cern.ch/dqm/dqm-square-k8/?run=362296&db=production),[362293](https://cmsweb.cern.ch/dqm/dqm-square-k8/?run=362293&db=production), [362290](https://cmsweb.cern.ch/dqm/dqm-square-k8/?run=362290&db=production).

Reproduced at lxplus locally. E.g. for CSC the crash is after `finished: processing event` call:
```
++++ finished: processing event : stream = 0 run = 362290 lumi = 5 event = 299493 time = 7167369903770124288
++++ starting: source event
++++ finished: source event
Begin processing the 63rd record. Run 362290, Event 306555, LumiSection 5 on stream 0 at 18-Nov-2022 17:27:27.888 CET
++++ starting: processing event : stream = 0 run = 362290 lumi = 5 event = 306555 time = 7167369916654472192
++++++ starting: processing path 'p' : stream = 0
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'dqmSaverPB' id = 10
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'dqmSaver' id = 9
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'dqmEnv' id = 8
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'cscMonitor' id = 7
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'cscSegments' id = 6
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'csc2DRecHits' id = 5
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'muonCSCDigis' id = 4
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'dqmCSCClient' id = 3
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'dqmCSCClient' id = 3
++++++++ starting: processing event for module: stream = 0 label = 'dqmCSCClient' id = 3
++++++++ finished: processing event for module: stream = 0 label = 'dqmCSCClient' id = 3
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'muonCSCDigis' id = 4
++++++++ starting: processing event for module: stream = 0 label = 'muonCSCDigis' id = 4
++++++++ finished: processing event for module: stream = 0 label = 'muonCSCDigis' id = 4
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'csc2DRecHits' id = 5
++++++++ starting: processing event for module: stream = 0 label = 'csc2DRecHits' id = 5
++++++++ finished: processing event for module: stream = 0 label = 'csc2DRecHits' id = 5
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'cscSegments' id = 6
++++++++ starting: processing event for module: stream = 0 label = 'cscSegments' id = 6
++++++++ finished: processing event for module: stream = 0 label = 'cscSegments' id = 6
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'cscMonitor' id = 7
++++++++ starting: processing event for module: stream = 0 label = 'cscMonitor' id = 7
++++++++ finished: processing event for module: stream = 0 label = 'cscMonitor' id = 7
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'dqmEnv' id = 8
++++++++ starting: processing event for module: stream = 0 label = 'dqmEnv' id = 8
++++++++ finished: processing event for module: stream = 0 label = 'dqmEnv' id = 8
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'dqmSaver' id = 9
++++++++ starting: processing event for module: stream = 0 label = 'dqmSaver' id = 9
++++++++ finished: processing event for module: stream = 0 label = 'dqmSaver' id = 9
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'dqmSaverPB' id = 10
++++++++ starting: processing event for module: stream = 0 label = 'dqmSaverPB' id = 10
++++++++ finished: processing event for module: stream = 0 label = 'dqmSaverPB' id = 10
++++++++ starting: processing event for module: stream = 0 label = 'p' id = 2
++++++++ finished: processing event for module: stream = 0 label = 'p' id = 2
++++++ finished: processing path 'p' : stream = 0
++++++++ starting: processing event for module: stream = 0 label = 'TriggerResults' id = 1
++++++++ finished: processing event for module: stream = 0 label = 'TriggerResults' id = 1
++++ finished: processing event : stream = 0 run = 362290 lumi = 5 event = 306555 time = 7167369916654472192

Thread 1 "cmsRun" received signal SIGSEGV, Segmentation fault.
```

gdb backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7b87347 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#2  0x00007ffff7c653d6 in edm::DataManagingProductResolver::resetProductData_(bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#3  0x00007ffff7c510a8 in edm::Principal::clearPrincipal() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#4  0x00007ffff7b9bdcd in edm::EventPrincipal::clearEventPrincipal() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#5  0x00007ffff7ba325e in edm::FunctorWaitingTask<edm::waiting_task::detail::WaitingTaskChain<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#4}>, edm::waiting_task::detail::Conditional<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#3}> >, edm::waiting_task::detail::Conditional<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#2}> >, edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#1}> >::runLast(edm::WaitingTaskHolder)::{lambda(std::__exception_ptr::exception_ptr const*)#1}>::execute() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#6  0x00007ffff7b8193f in tbb::detail::d1::function_task<edm::WaitingTaskHolder::doneWaiting(std::__exception_ptr::exception_ptr)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#7  0x00007ffff6357bec in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x7ffff1d4ac00, this=0x7ffff1d3fe00)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.h:322
#8  tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x7ffff1d3fe00)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.h:463
#9  tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.cpp:168
#10 0x00007ffff7bc0ffd in edm::FinalWaitingTask::wait() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#11 0x00007ffff7bac98c in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#12 0x00007ffff7bb7d53 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#13 0x000000000040a266 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const ()
#14 0x00007ffff63460eb in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/arena.cpp:698
#15 0x000000000040b094 in main::{lambda()#1}::operator()() const ()
#16 0x000000000040971c in main ()
```

#### To reproduce

```
scram project CMSSW_12_5_2_patch1
cd CMSSW_12_5_2_patch1/src; cmsenv
git cms-addpkg DQM/Integration
git fetch official-cmssw refs/pull/37737/*:refs/gh-remotes/pull/39597/*; git cms-merge-topic 39597
git fetch official-cmssw refs/pull/37802/*:refs/gh-remotes/pull/40071/*; git cms-merge-topic 40071
git fetch official-cmssw refs/pull/37741/*:refs/gh-remotes/pull/40073/*; git cms-merge-topic 40073
mkdir data
cp -r /afs/cern.ch/user/p/pmandrik/public/temp/run362290 ./data/.
```
Put `process.source.minEventsPerLumi = 99999999` to the `csc_dqm_sourceclient-live_cfg.py` and run:
```
cmsRun DQM/Integration/python/clients/csc_dqm_sourceclient-live_cfg.py runInputDir=./data runNumber=362290 runkey=hi_run scanOnce=True
```

**Comment by francescobrivio** [comment]
@pmandrik maybe close this issue and move the discussion in #40110 to avoid confusion?
