### ISSUE TITLE
Segfault in SerialTaskQueue destructor

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#40259]
Workflow 138.5 step 3 crashed in CMSSW_13_0_ROOT6_X_2022-12-07-2300 on el8_amd64_gcc11 with
```
 fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thu Dec  8 03:42:01 CET 2022
Thread 5 (Thread 0x2b0d65e00700 (LWP 24398) "cmsRun"):
#0  0x00002b0d1d0fd9b8 in nanosleep () from /lib64/libc.so.6
#1  0x00002b0d1d0fd8be in sleep () from /lib64/libc.so.6
#2  0x00002b0d224a5aa0 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b0d1d03c9bd in syscall () from /lib64/libc.so.6
#5  0x00002b0d1c12b797 in tbb::detail::r1::futex_wait (comparand=2, futex=0x2b0d2111b02c) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:103
#6  tbb::detail::r1::binary_semaphore::P (this=0x2b0d2111b02c) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:290
#7  0x00002b0d1c13e951 in tbb::detail::r1::rml::internal::thread_monitor::commit_wait (c=..., this=0x2b0d2111b020) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/rml_thread_monitor.h:243
#8  tbb::detail::r1::rml::private_worker::run (this=0x2b0d2111b000) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:274
#9  tbb::detail::r1::rml::private_worker::thread_routine (arg=0x2b0d2111b000) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:221
#10 0x00002b0d1cdeb1cf in start_thread () from /lib64/libpthread.so.0
#11 0x00002b0d1d03ce73 in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b0d64ea1700 (LWP 24397) "cmsRun"):
#0  0x00002b0d1d0fd9b8 in nanosleep () from /lib64/libc.so.6
#1  0x00002b0d1d0fd8be in sleep () from /lib64/libc.so.6
#2  0x00002b0d224a5aa0 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b0d1d03c9bd in syscall () from /lib64/libc.so.6
#5  0x00002b0d1c12b797 in tbb::detail::r1::futex_wait (comparand=2, futex=0x2b0d2111b12c) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:103
#6  tbb::detail::r1::binary_semaphore::P (this=0x2b0d2111b12c) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:290
#7  0x00002b0d1c13e951 in tbb::detail::r1::rml::internal::thread_monitor::commit_wait (c=..., this=0x2b0d2111b120) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/rml_thread_monitor.h:243
#8  tbb::detail::r1::rml::private_worker::run (this=0x2b0d2111b100) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:274
#9  tbb::detail::r1::rml::private_worker::thread_routine (arg=0x2b0d2111b100) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:221
#10 0x00002b0d1cdeb1cf in start_thread () from /lib64/libpthread.so.0
#11 0x00002b0d1d03ce73 in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b0d644a0700 (LWP 24396) "cmsRun"):
#0  0x00002b0d1d0fd9b8 in nanosleep () from /lib64/libc.so.6
#1  0x00002b0d1d0fd8be in sleep () from /lib64/libc.so.6
#2  0x00002b0d224a5aa0 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b0d1d03c9bd in syscall () from /lib64/libc.so.6
#5  0x00002b0d1c12b797 in tbb::detail::r1::futex_wait (comparand=2, futex=0x2b0d2111b0ac) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:103
#6  tbb::detail::r1::binary_semaphore::P (this=0x2b0d2111b0ac) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/semaphore.h:290
#7  0x00002b0d1c13e951 in tbb::detail::r1::rml::internal::thread_monitor::commit_wait (c=..., this=0x2b0d2111b0a0) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/rml_thread_monitor.h:243
#8  tbb::detail::r1::rml::private_worker::run (this=0x2b0d2111b080) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:274
#9  tbb::detail::r1::rml::private_worker::thread_routine (arg=0x2b0d2111b080) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_6_0_pre3-el8_amd64_gcc11/build/CMSSW_12_6_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.5.0-26deaf86b02cf9ce10d1fb9d6400c40a/tbb-v2021.5.0/src/tbb/private_server.cpp:221
#10 0x00002b0d1cdeb1cf in start_thread () from /lib64/libpthread.so.0
#11 0x00002b0d1d03ce73 in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b0d436a4700 (LWP 24239) "cmsRun"):
#0  0x00002b0d1cdf5672 in waitpid () from /lib64/libpthread.so.0
#1  0x00002b0d224a5c57 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#2  0x00002b0d224a680a in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  0x00002b0d1c90b9b4 in std::execute_native_thread_routine (__p=0x2b0d366da210) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#4  0x00002b0d1cdeb1cf in start_thread () from /lib64/libpthread.so.0
#5  0x00002b0d1d03ce73 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b0d1de9b080 (LWP 24197) "cmsRun"):
#0  0x00002b0d1d1280e1 in poll () from /lib64/libc.so.6
#1  0x00002b0d224a5f4f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#2  0x00002b0d224a68dc in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  0x00002b0d224a925b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b0d1a005be6 in edm::SerialTaskQueue::~SerialTaskQueue() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/libFWCoreConcurrency.so
#6  0x00002b0d1a22db3c in edm::eventsetup::EventSetupRecordIOVQueue::~EventSetupRecordIOVQueue() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#7  0x00002b0d1a1d1611 in edm::EventProcessor::~EventProcessor() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02762/el8_amd64_gcc11/cms/cmssw/CMSSW_13_0_ROOT6_X_2022-12-06-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#8  0x0000000000409b11 in (anonymous namespace)::EventProcessorWithSentry::~EventProcessorWithSentry() ()
#9  0x0000000000409729 in main ()

Current Modules:
Module: none (crashed)
Module: none
Module: none
Module: none

A fatal system signal has occurred: segmentation violation
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_0_ROOT6_X_2022-12-07-2300/pyRelValMatrixLogs/run/138.5_ExpressCollisions2021/step3_ExpressCollisions2021.log#/

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I wonder if #40253 might actually cure this rare(?) crash?
