### ISSUE TITLE
native `root` commands do not work in `cmssw`

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#40607]
e.g.:

```bash
rootls https://root.cern/files/tmva_class_example.root
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-24-2300/external/slc7_amd64_gcc11/bin/rootls", line 10, in <module>
    import cmdLineUtils
ImportError: No module named cmdLineUtils
```

or

```bash
rootbrowse https://root.cern/files/tmva_class_example.root
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-24-2300/external/slc7_amd64_gcc11/bin/rootbrowse", line 10, in <module>
    import cmdLineUtils
ImportError: No module named cmdLineUtils
```

**Comment by smuzaffar** [comment]
assign core

**Comment by smuzaffar** [comment]
thanks for reporting it @mmusich . Looks like `rootls` is using `python` instead of `python3` [a]. I will update our build recipe to fix this. For now please use 
```
python3 `which rootls` https://root.cern/files/tmva_class_example.root
```
in cmssw env


[a]
```
Singularity> head -1 `which rootls `
#!/usr/bin/env python
```
