### ISSUE TITLE
[CLANG_X] SIGSEGV in vecgeom::cxx::ExtrudedStruct::CreateTessellated RelVal 20034.0

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#41176]
Multiple relvals failed with same stacktrace, e.g [20034.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_CLANG_X_2023-03-23-2300/pyRelValMatrixLogs/run/20034.0_TTbar_14TeV+2026D86/step1_TTbar_14TeV+2026D86.log#/69-69)

Stack trace with source information:

```
Thread 6 (Thread 0x7f766593f700 (LWP 4131) "cmsRun"):
#0  0x00007f76a0d5c0e1 in poll () from /lib64/libc.so.6
#1  0x00007f769b10471c in (anonymous namespace)::full_read(int, char*, unsigned long, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#2  0x00007f769b1041c4 in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  0x00007f769b103aef in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f7668ac63b0 in vecgeom::cxx::ExtrudedStruct::CreateTessellated(unsigned long, vecgeom::cxx::XtruVertex2 const*, unsigned long, vecgeom::cxx::XtruSection const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/external/el8_amd64_gcc11/lib/libG4geome
try.so
#6  0x00007f7668ab1eca in G4ExtrudedSolid::G4ExtrudedSolid(G4String const&, std::vector<CLHEP::Hep2Vector, std::allocator<CLHEP::Hep2Vector> > const&, std::vector<G4ExtrudedSolid::ZSection, std::allocator<G4ExtrudedSolid::ZSection> > const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSS
W_13_1_CLANG_X_2023-03-23-2300/external/el8_amd64_gcc11/lib/libG4geometry.so
#7  0x00007f766918c868 in DDG4SolidConverter::extrudedpolygon (solid=...) at src/SimG4Core/Geometry/src/DDG4SolidConverter.cc:256
#8  0x00007f766916b1ff in DDG4Builder::convertSolid (this=this@entry=0x7f76659387b8, solid=...) at src/SimG4Core/Geometry/src/DDG4Builder.cc:53
#9  0x00007f766916ae62 in DDG4Builder::convertLV (this=this@entry=0x7f76659387b8, part=...) at src/SimG4Core/Geometry/src/DDG4Builder.cc:36
#10 0x00007f766916bbc5 in DDG4Builder::BuildGeometry (this=0x7f76659387b8, catalog=...) at src/SimG4Core/Geometry/src/DDG4Builder.cc:116
#11 0x00007f766916a5c3 in DDDWorld::DDDWorld (this=0x7f7664c5c230, pDD=0x7f763fc64680, pDD4hep=0x0, catalog=..., verb=0, cuts=true, pcut=<optimized out>) at src/SimG4Core/Geometry/src/DDDWorld.cc:47
#12 0x00007f766926bede in RunManagerMT::initG4(DDCompactView const*, cms::DDCompactView const*, HepPDT::ParticleDataTable const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/lib/el8_amd64_gcc11/libSimG4CoreApplication.so
#13 0x00007f76692645cd in std::thread::_State_impl<std::thread::_Invoker<std::tuple<OscarMTMasterThread::OscarMTMasterThread(edm::ParameterSet const&)::$_0> > >::_M_run() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-23-2300/lib/el8_amd64_gcc11/libSimG4CoreApplicat
ion.so
#14 0x00007f76a16939b4 in std::execute_native_thread_routine (__p=0x7f76695800e0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#15 0x00007f76a10051cf in start_thread () from /lib64/libpthread.so.0
#16 0x00007f76a0c70e73 in clone () from /lib64/libc.so.6
```

Full stacktrace [here](https://gist.github.com/iarspider/c57ace431ddb5f7a5e29a15a1258d739)

Possibly related to unit test failures in the same IB ( https://github.com/cms-sw/cmssw/issues/41171 )

**Comment by iarspider** [comment]
assign geometry

**Comment by dan131riley** [comment]
Looking at wf 20034 step 1 with SIGSEV
```
#5  0x00002b354d84a3b0 in vecgeom::cxx::ExtrudedStruct::CreateTessellated(unsigned long, vecgeom::cxx::XtruVertex2 const*, unsigned long, vecgeom::cxx::XtruSection const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02777/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_CLANG_X_2023-03-24-2300/external/el8_amd64_gcc11/lib/libG4geometry.so
```
Looking at the UBSAN build for the wf it flags
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ee7179e2e814836d709a4a8079418186/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_UBSAN_X_2023-03-24-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1354:59: runtime error: index 48 out of bounds for type 'double [48]'
```
so this is very likely the same issue as #41184 (and nice to have working UBSAN builds again!)

**Comment by makortel** [comment]
The CMSSW_13_1_CLANG_X_2023-03-22-2300 was still clean, whereas the next IB CMSSW_13_1_CLANG_X_2023-03-23-2300 shows the segfaults. The PR that introduced https://github.com/cms-sw/cmssw/issues/41184#issuecomment-1485216143 (https://github.com/cms-sw/cmssw/pull/41048) was merged between those two IBs.

**Comment by smuzaffar** [comment]
@iarspider , I guess this was fixed .... right? should we close this issue?

**Comment by iarspider** [comment]
@cmsbuild please close
