### ISSUE TITLE
[106X] SiStripDAQ_O2O_test fails in 10_6_X

### ISSUE THREAD

**Issue by tvami** [cms-sw/cmssw#41358]
From https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_6_X_2023-04-16-0000/unitTestLogs/CondTools/SiStrip#/

```
#5  0x00002ad862eb31b6 in std::vector<unsigned int, std::allocator<unsigned int> >::operator=(std::vector<unsigned int, std::allocator<unsigned int> > const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#6  0x00002ad88a55395b in SiStripPayloadHandler<SiStripBadStrip>::analyze(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/pluginOnlineDBSiStripO2OPlugins.so
#7  0x00002ad862e5392e in edm::EDAnalyzer::doEvent(edm::EventPrincipal const&, edm::EventSetupImpl const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#8  0x00002ad862e8cc02 in edm::WorkerT<edm::EDAnalyzer>::implDo(edm::EventPrincipal const&, edm::EventSetupImpl const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#9  0x00002ad862e3c0ba in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetupImpl const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetupImpl const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#10 0x00002ad862e3c27d in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetupImpl const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#11 0x00002ad862e3d90b in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetupImpl const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#12 0x00002ad862e3ef35 in void edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#13 0x00002ad862e3eff1 in edm::SerialTaskQueue::QueuedTask<void edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#14 0x00002ad864671931 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x2ad8683e7200, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:521
#15 0x00002ad862ee9220 in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#16 0x00002ad862ef2c71 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2023-04-16-0000/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#17 0x000000000040fe78 in main::{lambda()#1}::operator()() const ()
#18 0x000000000040e142 in main ()

Current Modules:

Module: SiStripO2OBadStrip:siStripO2O (crashed)

A fatal system signal has occurred: segmentation violation
```

The problem is not there in master anymore. I couldnt find when it started to appear in 10_6_X either.

**Comment by tvami** [comment]
assign db

**Comment by mmusich** [comment]
what about backporting https://github.com/cms-sw/cmssw/pull/40249 ?
