### ISSUE TITLE
Possibly wrong cms python type assigned in nanogen_cff.py

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#41693]
After the merge of https://github.com/cms-sw/cmssw/pull/41361 which enforces the cms python types in configurations, we have several nanoAOD workflow crashing in the IB tests with message like:
```
ANOGEN,DQM:@nanogenDQM
entry file:step1.root
Step: NANOGEN Spec: 
Step: DQM Spec: ['@nanogenDQM']
customising the process with customizeNanoGENFromMini from PhysicsTools/NanoAOD/nanogen_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/bin/el8_amd64_gcc11/cmsDriver.py", line 52, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/bin/el8_amd64_gcc11/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 2399, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 970, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/PhysicsTools/NanoAOD/python/nanogen_cff.py", line 78, in customizeNanoGENFromMini
    nanoGenCommonCustomize(process)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/PhysicsTools/NanoAOD/python/nanogen_cff.py", line 56, in nanoGenCommonCustomize
    setGenMassPrecision(process, CandVars.mass.precision)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/PhysicsTools/NanoAOD/python/nanogen_cff.py", line 148, in setGenMassPrecision
    process.genParticleTable.variables.mass.precision = precision
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/FWCore/ParameterSet/python/Mixins.py", line 285, in __setattr__
    self.__dict__[name] = self.__dict__[name]._checkAndReturnValueWithType(value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_X_2023-05-15-2300/src/FWCore/ParameterSet/python/Mixins.py", line 91, in _checkAndReturnValueWithType
    raise TypeError("Attempted to assign type {from_} to type {to}".format(from_ = str(type(valueWithType)), to = str(type(self))) )
TypeError: Attempted to assign type <class 'FWCore.ParameterSet.Types.int32'> to type <class 'FWCore.ParameterSet.Types.string'>
```

This can be reconducted to the assignment of `setGenMassPrecision` in PhysicsTools/NanoAOD/python/nanogen_cff.py, where the variable `mass` in the PSet is defined in https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/genparticles_cff.py#L40

The formulation is rather complicate for me, and I think the @cms-sw/xpog-l2 experts are needed to sort it out and fix the wrong assignment.

**Comment by perrotta** [comment]
See for example wfs 546.0, 547.0, 548.0  in https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_13_2/2023-05-15-2300?selectedArchs=el8_amd64_gcc11&selectedFlavors=X&selectedStatus=failed

**Comment by perrotta** [comment]
> I believe #41696 should fix this particular problem.

Thank you @Dr15Jones !

**Comment by perrotta** [comment]
Fixed by https://github.com/cms-sw/cmssw/pull/41696
