### ISSUE TITLE
Index out of bounds in HGCalLayerClusterProducer

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#41724]
We are seeing segmentation faults in some workflows in HGCalLayerClusterProducer, e.g. https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_13_2_X_2023-05-17-2300/pyRelValMatrixLogs/run/25234.911_TTbar_14TeV+2026D99_DD4hep/step3_TTbar_14TeV+2026D99_DD4hep.log#/.  UBSAN builds report "runtime error: index 14696 out of bounds for type 'vector [14676]'" just before the crash.  Stack traces from gdb and UBSAN:
```
Thread 4 (Thread 0x2b46e5686700 (LWP 6696) "cmsRun"):
#3  0x00002b469111aacb in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b4719e2ff7b in HGCalCLUEAlgoT<HGCalLayerTilesT<HGCalTilesConstants> >::makeClusters()::{lambda()#1}::operator()() const::{lambda(unsigned long)#1}::operator()(unsigned long) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so
#6  0x00002b4719e3622b in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d1::parallel_for_body_wrapper<HGCalCLUEAlgoT<HGCalLayerTilesT<HGCalTilesConstants> >::makeClusters()::{lambda()#1}::operator()() const::{lambda(unsigned long)#1}, unsigned long>, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so
#7  0x00002b468a8b39cd in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x2b47050fbb00, this=0x2b468e5ed400) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:322
#8  tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x2b468e5ed400) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:458
#9  tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.cpp:168
#10 0x00002b4719e35900 in tbb::detail::d1::task_arena_function<HGCalCLUEAlgoT<HGCalLayerTilesT<HGCalTilesConstants> >::makeClusters()::{lambda()#1}, void>::operator()() const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so
#11 0x00002b468a8a20ee in operator() (__closure=<optimized out>) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:767
#12 tbb::detail::d0::try_call_proxy<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> >::on_completion<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> > (on_completion_body=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/../../include/oneapi/tbb/detail/_template_helpers.h:230
#13 tbb::detail::r1::isolate_within_arena (d=..., isolation=<optimized out>) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-slc7_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/slc7_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:768
#14 0x00002b4719e2aa39 in HGCalCLUEAlgoT<HGCalLayerTilesT<HGCalTilesConstants> >::makeClusters() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so
#15 0x00002b4719e42c4e in HGCalLayerClusterProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-05-16-2300/lib/slc7_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so

Current Modules:

Module: HGCalLayerClusterProducer:hgcalLayerClusters (crashed)
Module: none
Module: none
Module: HGCalRecHitMapProducer:hgcalRecHitMapProducer



/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161/include/c++/11.2.1/array:57:36: runtime error: index 14696 out of bounds for type 'vector [14676]'
    #0 0x2aaea806841c  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x7a941c)
    #1 0x2aaea80be20c  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x7ff20c)
    #2 0x2aaea80c205f  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x80305f)
    #3 0x2aad1c3839cc in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:322
    #4 0x2aad1c3839cc in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:458
    #5 0x2aad1c3839cc in tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.cpp:168
    #6 0x2aaea7fc7c2a  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x708c2a)
    #7 0x2aad1c3720ed in operator() /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:767
    #8 0x2aad1c3720ed in on_completion<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> > /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/../../include/oneapi/tbb/detail/_template_helpers.h:230
    #9 0x2aad1c3720ed in tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, long) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:768
    #10 0x2aaea80769bd  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x7b79bd)
    #11 0x2aaea8176849  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x8b7849)

/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161/include/c++/11.2.1/array:57:36: runtime error: index 14696 out of bounds for type 'vector [14676]'
    #0 0x2aaea80683b6  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x7a93b6)
    #1 0x2aaea80bdec0  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x7feec0)
    #2 0x2aaea80c205f  (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02785/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_UBSAN_X_2023-05-15-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHGCalRecProducersPlugins.so+0x80305f)
    #3 0x2aad1c37c303 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:322
    #4 0x2aad1c37c303 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_1_0_pre3-el8_amd64_gcc11/build/CMSSW_13_1_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:458
```

**Comment by makortel** [comment]
assign reconstruction, upgrade

FYI @cms-sw/hgcal-dpg-l2

**Comment by clacaputo** [comment]
type hgcal

**Comment by mandrenguyen** [comment]
+reconstruction
https://github.com/cms-sw/cmssw/pull/41589 is merged now

**Comment by makortel** [comment]
@cmsbuild, please close
