### ISSUE TITLE
[GPU] Segfault in PixelTrackProducerFromSoAPhase1::storeTracks()

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#42522]
Workflow 141.008522 step 2 segfaulted in CMSSW_13_3_GPU_X_2023-08-08-2300 on el8_amd64_gcc11 + `NVIDIA A100-PCIE-40GB`
```
Thread 7 (Thread 0x2b5cc04b5700 (LWP 10101) "cmsRun"):
Thread 7 (Thread 0x2b5cc04b5700 (LWP 10101) "cmsRun"):
#2  0x00002b5c3861cb10 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b5c35b40359 in __memset_avx2_unaligned_erms () from /lib64/libc.so.6
#5  0x00002b5cbb323bf6 in MahiFit::doFit(std::array<float, 4ul>&, int) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libRecoLocalCaloHcalRecAlgos.so
#6  0x00002b5cbb3247af in MahiFit::phase1Apply(HBHEChannelInfo const&, float&, float&, float&, bool&, float&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libRecoLocalCaloHcalRecAlgos.so
#7  0x00002b5cbb334885 in SimpleHBHEPhase1Algo::reconstruct(HBHEChannelInfo const&, HcalRecoParam const*, HcalCalibrations const&, bool) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libRecoLocalCaloHcalRecAlgos.so
#8  0x00002b5cbb50522d in HBHEPhase1Reconstructor::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHcalRecProducers.so
#9  0x00002b5c3355c2bd in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#10 0x00002b5c33542a22 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#11 0x00002b5c334cd49a in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#12 0x00002b5c334cd948 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so

Thread 6 (Thread 0x2b5cbfab4700 (LWP 10100) "cmsRun"):
#2  0x00002b5c3861cb10 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b5cc1522a41 in CAHitNtupletGeneratorKernelsCPU<pixelTopology::Phase1>::buildDoublets(TrackingRecHitSoA<pixelTopology::Phase1>::TrackingRecHitSoALayout<128ul, false>::ConstViewTemplateFreeParams<128ul, false, true, false> const&, int, CUstream_st*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoPixelVertexingPixelTripletsPlugins.so
#5  0x00002b5cc1539267 in CAHitNtupletGeneratorOnGPU<pixelTopology::Phase1>::makeTuples(TrackingRecHitSoAHost<pixelTopology::Phase1> const&, float) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoPixelVertexingPixelTripletsPlugins.so
#6  0x00002b5cc151e881 in CAHitNtupletCUDAT<pixelTopology::Phase1>::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoPixelVertexingPixelTripletsPlugins.so
#7  0x00002b5c335481ab in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#8  0x00002b5c33541f82 in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#9  0x00002b5c334cd49a in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#10 0x00002b5c334cd948 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so

Thread 5 (Thread 0x2b5cbf0b3700 (LWP 10099) "cmsRun"):
#2  0x00002b5c3861cb10 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b5c3664ecee in ZSTD_HcFindBestMatch_noDict_4 () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#5  0x00002b5c366688c6 in ZSTD_compressBlock_lazy2 () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#6  0x00002b5c3662675b in ZSTD_compressBlock_internal () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#7  0x00002b5c36627dc0 in ZSTD_compress_frameChunk () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#8  0x00002b5c3662ade8 in ZSTD_compressEnd () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#9  0x00002b5c3662e820 in ZSTD_compressCCtx () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libzstd.so.1
#10 0x00002b5c34370375 in R__zipZSTD () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libCore.so
#11 0x00002b5c3382c3bb in TBasket::WriteBuffer() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libTree.so
#12 0x00002b5c3383c177 in std::_Function_handler<void (), ROOT::Internal::TBranchIMTHelper::Run<TBranch::WriteBasketImpl(TBasket*, int, ROOT::Internal::TBranchIMTHelper*)::{lambda()#1}>(TBranch::WriteBasketImpl(TBasket*, int, ROOT::Internal::TBranchIMTHelper*)::{lambda()#1} const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libTree.so
#13 0x00002b5c35e4107f in tbb::detail::d1::function_task<std::function<void ()> >::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libImt.so
#14 0x00002b5c349dca6d in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x2b5ce9deda00, this=0x2b5c36d7d480) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
#15 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x2b5c36d7d480) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
#16 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/task_dispatcher.cpp:168
#17 0x00002b5c35e40e09 in ROOT::Experimental::TTaskGroup::Wait() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libImt.so
#18 0x00002b5c338b52b8 in TTree::Fill() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_GPU_X_2023-08-08-2300/external/el8_amd64_gcc11/lib/libTree.so
#19 0x00002b5ce8c4ee48 in tbb::detail::d1::task_arena_function<edm::RootOutputTree::fillTree()::{lambda()#1}, void>::operator()() const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libIOPoolOutput.so
#20 0x00002b5c349ca15e in operator() (__closure=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/arena.cpp:757
#21 tbb::detail::d0::try_call_proxy<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> >::on_completion<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> > (on_completion_body=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/../../include/oneapi/tbb/detail/_template_helpers.h:230
#22 tbb::detail::r1::isolate_within_arena (d=..., isolation=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-f040c0e8f64041ec1d922ddb8c9f4cb1/tbb-v2021.9.0/src/tbb/arena.cpp:758
#23 0x00002b5ce8c4fa9e in edm::RootOutputTree::fillTree() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libIOPoolOutput.so
#24 0x00002b5ce8c4d57c in edm::RootOutputFile::fillBranches(edm::BranchType const&, edm::OccurrenceForOutput const&, unsigned int, std::vector<edm::StoredProductProvenance, std::allocator<edm::StoredProductProvenance> >*, edm::ProductProvenanceRetriever const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libIOPoolOutput.so
#25 0x00002b5ce8c4def3 in edm::RootOutputFile::writeOne(edm::EventForOutput const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libIOPoolOutput.so
#26 0x00002b5ce8c3824b in edm::PoolOutputModule::write(edm::EventForOutput const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libIOPoolOutput.so
#27 0x00002b5c334cf2fc in edm::core::OutputModuleCore::doEvent_(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#28 0x00002b5c33550749 in edm::one::OutputModuleBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#29 0x00002b5c33540032 in edm::WorkerT<edm::one::OutputModuleBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so

Thread 1 (Thread 0x2b5c368db580 (LWP 10038) "cmsRun"):
#3  0x00002b5c3862034b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b5cbc638b9d in void storeTracks<edm::Event, std::vector<std::pair<reco::Track*, std::vector<TrackingRecHit const*, std::allocator<TrackingRecHit const*> > >, std::allocator<std::pair<reco::Track*, std::vector<TrackingRecHit const*, std::allocator<TrackingRecHit const*> > > > > >(edm::Event&, std::vector<std::pair<reco::Track*, std::vector<TrackingRecHit const*, std::allocator<TrackingRecHit const*> > >, std::allocator<std::pair<reco::Track*, std::vector<TrackingRecHit const*, std::allocator<TrackingRecHit const*> > > > > const&, TrackerTopology const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoPixelVertexingPixelTrackFittingPlugins.so
#6  0x00002b5cbc63d58e in PixelTrackProducerFromSoAT<pixelTopology::Phase1>::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/pluginRecoPixelVertexingPixelTrackFittingPlugins.so
#7  0x00002b5c335481ab in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#8  0x00002b5c33541f82 in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-08-07-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so

Current Modules:\
Module: PixelTrackProducerFromSoAPhase1:hltPixelTracks (crashed)
Module: HBHEPhase1Reconstructor:hltHbherecoLegacy
Module: PoolOutputModule:FEVTDEBUGHLToutput
Module: CAHitNtupletCUDAPhase1:hltPixelTracksCPUOnly
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_GPU_X_2023-08-08-2300/pyRelValMatrixLogs/run/141.008522_Run3-2023_JetMET2023B_RecoHCALOnlyGPU/step2_Run3-2023_JetMET2023B_RecoHCALOnlyGPU.log#/

**Comment by makortel** [comment]
assign reconstruction, hlt, heterogeneous

FYI @cms-sw/trk-dpg-l2

**Comment by slava77** [comment]
type tracking

**Comment by makortel** [comment]
There are certainly no further reports, and perhaps with the focus moving to Alpaka code I agree this issue could be closed.
