### ISSUE TITLE
[ARM] Segfaults in tensorflow

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#42565]
Workflow 2500.1 step2 segfaulted in CMSSW_13_3_X_2023-08-10-2300 on el8_aarch64_gcc12 with
```
Thread 5 (Thread 0x40004be59c80 (LWP 690247) "cmsRun"):
#3  0x000040001c6d7208 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x000040003eef15cf in std::_Function_handler<void (std::function<void ()>), tensorflow::DirectSession::RunInternal(long, tensorflow::RunOptions const&, tensorflow::CallFrameInterface*, tensorflow::DirectSession::ExecutorsAndKeys*, tensorflow::RunMetadata*, tsl::thread::ThreadPoolOptions const&)::{lambda(tensorflow::DirectSession::PerPartitionExecutorsAndLib const&, tensorflow::Executor::Args*)#7}::operator()(tensorflow::DirectSession::PerPartitionExecutorsAndLib const&, tensorflow::Executor::Args*) const::{lambda(std::function<void ()>)#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libtensorflow_cc.so.2
#6  0x000040003ef01764 in tensorflow::DirectSession::RunInternal(long, tensorflow::RunOptions const&, tensorflow::CallFrameInterface*, tensorflow::DirectSession::ExecutorsAndKeys*, tensorflow::RunMetadata*, tsl::thread::ThreadPoolOptions const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libtensorflow_cc.so.2
#7  0x000040003ef03178 in tensorflow::DirectSession::Run(tensorflow::RunOptions const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor> > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tensorflow::RunMetadata*, tsl::thread::ThreadPoolOptions const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libtensorflow_cc.so.2
#8  0x0000400035c9bb08 in tensorflow::run(tensorflow::Session*, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor> > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tsl::thread::ThreadPoolOptions const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libPhysicsToolsTensorFlow.so
#9  0x0000400035c9bd08 in tensorflow::run(tensorflow::Session*, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor> > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tsl::thread::ThreadPoolInterface*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libPhysicsToolsTensorFlow.so
#10 0x000040005013bd8c in void DeepTauId::getPredictionsV2<pat::PackedCandidate, pat::Tau>(reco::BaseTau const&, unsigned long, edm::RefToBase<reco::BaseTau>, std::vector<pat::Electron, std::allocator<pat::Electron> > const*, std::vector<pat::Muon, std::allocator<pat::Muon> > const*, edm::View<reco::Candidate> const&, reco::Vertex const&, double, unsigned long long const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >&, (anonymous namespace)::TauFunc) [clone .lto_priv.0] () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginRecoTauTagRecoTauPlugins.so
#11 0x0000400050133568 in DeepTauId::getPredictions(edm::Event&, edm::Handle<edm::View<reco::BaseTau> >) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginRecoTauTagRecoTauPlugins.so
#12 0x00004000501352e4 in DeepTauId::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginRecoTauTagRecoTauPlugins.so
#13 0x000040001850b5dc in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#14 0x00004000184f2e10 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#15 0x000040001847fec4 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#16 0x0000400018480634 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so

Thread 4 (Thread 0x40004c869c80 (LWP 690246) "cmsRun"):
#2  0x000040001c6d2988 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x000040004dc25574 in MlasSgemmKernelZero () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#5  0x000040004dc0beb0 in MlasSgemmOperation(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, unsigned long, unsigned long, unsigned long, float, float const*, unsigned long, float const*, unsigned long, float, float*, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#6  0x000040004dc0c400 in MlasSgemmThreaded(long, long, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, unsigned long, unsigned long, unsigned long, MLAS_SGEMM_DATA_PARAMS const*, long) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#7  0x000040004dc0c484 in std::_Function_handler<void (long), MlasGemmBatch(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, unsigned long, unsigned long, unsigned long, MLAS_SGEMM_DATA_PARAMS const*, unsigned long, onnxruntime::concurrency::ThreadPool*)::{lambda(long)#1}>::_M_invoke(std::_Any_data const&, long&&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#8  0x000040004dc319c4 in MlasTrySimpleParallel(onnxruntime::concurrency::ThreadPool*, long, std::function<void (long)> const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#9  0x000040004dc0c5e0 in MlasGemmBatch(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, unsigned long, unsigned long, unsigned long, MLAS_SGEMM_DATA_PARAMS const*, unsigned long, onnxruntime::concurrency::ThreadPool*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#10 0x000040004dc0ffa0 in MlasConv(MLAS_CONV_PARAMETERS const*, float const*, float const*, float const*, float*, float*, onnxruntime::concurrency::ThreadPool*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#11 0x000040004d72a338 in onnxruntime::Conv<float>::Compute(onnxruntime::OpKernelContext*) const () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#12 0x000040004db42534 in onnxruntime::ExecuteKernel(onnxruntime::StreamExecutionContext&, unsigned long, unsigned long, bool const&, onnxruntime::SessionScope&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#13 0x000040004db3af10 in onnxruntime::LaunchKernelStep::Execute(onnxruntime::StreamExecutionContext&, unsigned long, onnxruntime::SessionScope&, bool const&, bool&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#14 0x000040004db459b0 in onnxruntime::RunSince(unsigned long, onnxruntime::StreamExecutionContext&, onnxruntime::SessionScope&, bool const&, unsigned long, bool) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#15 0x000040004db40160 in onnxruntime::ExecuteThePlan(onnxruntime::SessionState const&, gsl::span<int const, 18446744073709551615ul>, gsl::span<OrtValue const, 18446744073709551615ul>, gsl::span<int const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, onnxruntime::logging::Logger const&, onnxruntime::DeviceStreamCollection const*, bool const&, bool, bool) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#16 0x000040004db0e10c in onnxruntime::utils::ExecuteGraphImpl(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager const&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, onnxruntime::DeviceStreamCollection*, bool, onnxruntime::Stream*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#17 0x000040004db10790 in onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, bool, bool, onnxruntime::Stream*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#18 0x000040004db10ec0 in onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, ExecutionMode, OrtRunOptions const&, onnxruntime::logging::Logger const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#19 0x000040004d4a568c in onnxruntime::InferenceSession::Run(OrtRunOptions const&, gsl::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, gsl::span<OrtValue const, 18446744073709551615ul>, gsl::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >*, std::vector<OrtDevice, std::allocator<OrtDevice> > const*) [clone .localalias] () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#20 0x000040004d445f08 in OrtApis::Run(OrtSession*, OrtRunOptions const*, char const* const*, OrtValue const* const*, unsigned long, char const* const*, unsigned long, OrtValue**) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#21 0x000040004d384170 in cms::Ort::ONNXRuntime::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::vector<std::vector<long, std::allocator<long> >, std::allocator<std::vector<long, std::allocator<long> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long) const () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libPhysicsToolsONNXRuntime.so
#22 0x000040005f023ae8 in BoostedJetONNXJetTagsProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginRecoBTagONNXRuntimePlugins.so
#23 0x000040001850b5dc in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#24 0x00004000184f2e10 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so

Thread 3 (Thread 0x40004b449c80 (LWP 690245) "cmsRun"):
#2  0x000040001c6d2988 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000400052247d30 in Rivet::Vector3::pseudorapidity() const () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginGeneratorInterfaceRivetInterface_plugins.so
#5  0x000040005224c528 in Rivet::RivetAnalysis::analyze(Rivet::Event const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginGeneratorInterfaceRivetInterface_plugins.so
#6  0x00004000528041cc in Rivet::AnalysisHandler::analyze(HepMC::GenEvent const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libRivet.so
#7  0x000040005224e2e0 in ParticleLevelProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginGeneratorInterfaceRivetInterface_plugins.so
#8  0x0000400018501564 in edm::one::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#9  0x00004000184ea990 in edm::WorkerT<edm::one::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so

Thread 1 (Thread 0x40001a01cbc0 (LWP 689846) "cmsRun"):
#2  0x000040001c6d2988 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x000040004db44be8 in onnxruntime::StreamExecutionContext::WaitAll() () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#5  0x000040004db4016c in onnxruntime::ExecuteThePlan(onnxruntime::SessionState const&, gsl::span<int const, 18446744073709551615ul>, gsl::span<OrtValue const, 18446744073709551615ul>, gsl::span<int const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, onnxruntime::logging::Logger const&, onnxruntime::DeviceStreamCollection const*, bool const&, bool, bool) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#6  0x000040004db0e10c in onnxruntime::utils::ExecuteGraphImpl(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager const&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, onnxruntime::DeviceStreamCollection*, bool, onnxruntime::Stream*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#7  0x000040004db10790 in onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, bool, bool, onnxruntime::Stream*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#8  0x000040004db10ec0 in onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, gsl::span<OrtValue const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >&, ExecutionMode, OrtRunOptions const&, onnxruntime::logging::Logger const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#9  0x000040004d4a568c in onnxruntime::InferenceSession::Run(OrtRunOptions const&, gsl::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, gsl::span<OrtValue const, 18446744073709551615ul>, gsl::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, std::vector<OrtValue, std::allocator<OrtValue> >*, std::vector<OrtDevice, std::allocator<OrtDevice> > const*) [clone .localalias] () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#10 0x000040004d445f08 in OrtApis::Run(OrtSession*, OrtRunOptions const*, char const* const*, OrtValue const* const*, unsigned long, char const* const*, unsigned long, OrtValue**) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/external/el8_aarch64_gcc12/lib/libonnxruntime.so.1.14.1
#11 0x000040004d384170 in cms::Ort::ONNXRuntime::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::vector<std::vector<long, std::allocator<long> >, std::allocator<std::vector<long, std::allocator<long> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long) const () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libPhysicsToolsONNXRuntime.so
#12 0x000040005f023ae8 in BoostedJetONNXJetTagsProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/pluginRecoBTagONNXRuntimePlugins.so
#13 0x000040001850b5dc in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so
#14 0x00004000184f2e10 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02797/el8_aarch64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-10-2300/lib/el8_aarch64_gcc12/libFWCoreFramework.so

Current Modules:
Module: DeepTauId:deepTau2018v2p5ForNano (crashed)
Module: ParticleLevelProducer:particleLevel
Module: BoostedJetONNXJetTagsProducer:pfParticleNetFromMiniAODAK4CHSForwardJetTagsWithDeepInfo
Module: BoostedJetONNXJetTagsProducer:pfParticleNetFromMiniAODAK4CHSCentralJetTagsWithDeepInfo
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc12/CMSSW_13_3_X_2023-08-10-2300/pyRelValMatrixLogs/run/2500.1_NANOmc122Xrun3/step2_NANOmc122Xrun3.log#/

**Comment by makortel** [comment]
assign reconstruction, l1
