### ISSUE TITLE
GPU Profiling with RelVal 141.103 fails with `AttributeError: 'Process' object has no attribute '@standardDQM'`

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#42676]
ib-run-profiling-gpu jobs are failing in CMSSW_13_*_X IBs, see e.g. [this Jenkins log](https://cmssdt.cern.ch/jenkins/job/ib-run-profiling-gpu/3433/console):

```
01:50:02 Step: NANO Spec: ['@standardDQM', '@miniAODDQM', '@nanoAODDQM']
01:50:02 in prepare_nano @standardDQM+@miniAODDQM+@nanoAODDQM
01:50:02 Traceback (most recent call last):
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-08-27-0000/bin/el8_amd64_gcc11/cmsDriver.py", line 52, in <module>
01:50:02     run()
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-08-27-0000/bin/el8_amd64_gcc11/cmsDriver.py", line 28, in run
01:50:02     configBuilder.prepare()
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-08-28-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 2238, in prepare
01:50:02     self.addStandardSequences()
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-08-28-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 844, in addStandardSequences
01:50:02     getattr(self,"prepare_"+stepName)(stepSpec = '+'.join(stepSpec))
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-08-28-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1779, in prepare_NANO
01:50:02     self.scheduleSequence(_nanoSeq,'nanoAOD_step')
01:50:02   File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02800/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-08-28-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1318, in scheduleSequence
01:50:02     setattr(self.process,sn,getattr(cms,what)( getattr(self.process, s) ))
01:50:02 AttributeError: 'Process' object has no attribute '@standardDQM'
```

**Comment by iarspider** [comment]
assign core

**Comment by iarspider** [comment]
In case this helps: logs for [CMSSW_13_0_X](https://cmssdt.cern.ch/jenkins/job/ib-run-profiling-gpu/3417/console), [CMSSW_13_1_X](https://cmssdt.cern.ch/jenkins/job/ib-run-profiling-gpu/3423/console), [CMSSW_13_2_X](https://cmssdt.cern.ch/jenkins/job/ib-run-profiling-gpu/3435/console)

**Comment by Dr15Jones** [comment]
assign operations

The RelVal code is not managed by core

**Comment by makortel** [comment]
If I read the log correctly, the `cmsDriver.py` command has
```
cmsDriver.py step3 ... -s RAW2DIGI,L1Reco,RECO,SKIM:JetHTJetPlusHOFilter+EXOHighMET+EXODelayedJetMET+EXODisappTrk+LogError+LogErrorMonitor,PAT,NANO,DQM:@standardDQM+@miniAODDQM+@nanoAODDQM
```
but then the printout of `cmsDriver.py` has
```
RAW2DIGI,L1Reco,RECO,SKIM:JetHTJetPlusHOFilter+EXOHighMET+EXODelayedJetMET+EXODisappTrk+LogError+LogErrorMonitor,PAT,NANO:@standardDQM+@miniAODDQM+@nanoAODDQM,ENDJOB
...
Step: NANO Spec: ['@standardDQM', '@miniAODDQM', '@nanoAODDQM']
in prepare_nano @standardDQM+@miniAODDQM+@nanoAODDQM
```
It looks like the `DQM` part given to `cmsDriver.py` somehow disappears, and `DQM` sequence names get applied to `NANO`, that then (rightfully) fails.

**Comment by gartung** [comment]
I recently added this at Slava's suggestion. I will have a closer look.

**Comment by gartung** [comment]
I updated the Jenkins job to skip workflow 141.* like I fo for workflow 136.* which has the same issue.

**Comment by gartung** [comment]
@iarspider this can be closed. I re-ran the failed `ig-run-profing-gpu` job and it exits for wf 141.* as expected.
