### ISSUE TITLE
AttributeError: 'EDProducer' object has no attribute 'input'

### ISSUE THREAD

**Issue by TOPSONN** [cms-sw/cmssw#43061]
**When I try to run :**

cmsDriver.py  --mc --eventcontent FEVTDEBUGHLT  --datatier GEN-SIM-DIGI-RAW --conditions 102X_upgrade2018_realistic_v15  --step DIGI,L1,DIGI2RAW,HLT:@relval2018  -n -1  --geometry DB:Extended  --era Run2_2018  --filein file:step1_VBS.root  --fileout file:step2_VBS.root  --customise Configuration/DataProcessing/Utils.addMonitoring --pileup_input "dbs:/MinBias_TuneCP5_13TeV-pythia8/RunIIFall18GS-102X_upgrade2018_realistic_v9-v1/GEN-SIM"

**It shows the following error and i need some help:**

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_5/bin/slc7_amd64_gcc10/cmsDriver.py", line 52, in <module>
    run()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_5/bin/slc7_amd64_gcc10/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_5/src/Configuration/Applications/python/ConfigBuilder.py", line 2165, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_5/src/Configuration/Applications/python/ConfigBuilder.py", line 757, in addStandardSequences
    self.executeAndRemember(command)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_5/src/Configuration/Applications/python/ConfigBuilder.py", line 340, in executeAndRemember
    exec(re.sub(r"([^a-zA-Z_0-9]|^)(process)([^a-zA-Z_0-9])",r"\1self.process\3",command))
  File "<string>", line 1, in <module>
AttributeError: 'EDProducer' object has no attribute 'input'

**Comment by makortel** [comment]
assign package Configuration/Applications

**Comment by makortel** [comment]
I'd guess the pileup scenario is missing. E.g. workflow 11024.0 (TTbar+PU for 2018) has `--pileup AVE_50_BX_25ns --pileup_input das:/RelValMinBias_13/CMSSW_12_0_0_pre4-113X_upgrade2018_realistic_v5-v1/GEN-SIM`. Your `cmsDriver.py` command has `--pileup_input` but no `--pileup`.

**Comment by TOPSONN** [comment]
Sorry when i add the following command  : --pileup AVE_50_BX_25ns
It shows : 

%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 20-Oct-2023 08:58:48 CEST  pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/mc/RunIIFall18GS/MinBias_TuneCP5_13TeV-pythia8/GEN-SIM/102X_upgrade2018_realistic_v9-v1/00003/4A38E763-6A92-E811-9473-7CD30AD09F4C.root?tried=&xrdcl.requuid=bc2e15ba-68e2-4530-95f0-875d18902ff9.
%MSG
20-Oct-2023 08:58:48 CEST  Initiating request to open file root://xrootd-cms.infn.it//store/mc/RunIIFall18GS/MinBias_TuneCP5_13TeV-pythia8/GEN-SIM/102X_upgrade2018_realistic_v9-v1/00003/4A38E763-6A92-E811-9473-7CD30AD09F4C.root
20-Oct-2023 08:59:02 CEST  Successfully opened file root://xrootd-cms.infn.it//store/mc/RunIIFall18GS/MinBias_TuneCP5_13TeV-pythia8/GEN-SIM/102X_upgrade2018_realistic_v9-v1/00003/4A38E763-6A92-E811-9473-7CD30AD09F4C.root
----- Begin Fatal Exception 20-Oct-2023 08:59:35 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module GEMDigiToRawModule/'gemPacker'
Exception Message:
No "GEMChMapRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

**Comment by makortel** [comment]
Maybe the GlobalTag is wrong? It seems to be for 10_2_X, and you seem to be using 12_6_5. @cms-sw/alca-l2

**Comment by TOPSONN** [comment]
OK i will try 10_2_X

**Comment by makortel** [comment]
Is this still an issue, or could we close it?
