### ISSUE TITLE
null reference used in DAClusterizerInZ_vect::fill

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#44277]
The UBSAN build found the following

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_amd64_gcc12/CMSSW_14_1_UBSAN_X_2024-02-28-2300/pyRelValMatrixLogs/run/11602.0_SingleElectronPt35+2021/step3_SingleElectronPt35+2021.log

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096:17: runtime error: reference binding to null pointer of type 'double'
    #0 0x15231728b10f in __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >::operator*() const /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096
    #1 0x15231728b10f in std::vector<double, std::allocator<double> >::front() /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1207
    #2 0x15231728b10f in DAClusterizerInZ_vect::track_t::extractRaw() /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8f5acb06a30313f409279f6fb9d2d7bb/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_UBSAN_X_2024-02-26-2300/src/RecoVertex/PrimaryVertexProducer/interface/DAClusterizerInZ_vect.h:62
    #3 0x15231728b10f in DAClusterizerInZ_vect::fill(std::vector<reco::TransientTrack, std::allocator<reco::TransientTrack> > const&) const src/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc:211
    #4 0x1523172b507c in DAClusterizerInZ_vect::vertices_no_blocks(std::vector<reco::TransientTrack, std::allocator<reco::TransientTrack> > const&) const src/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc:770
    #5 0x1523172b7239 in DAClusterizerInZ_vect::vertices(std::vector<reco::TransientTrack, std::allocator<reco::TransientTrack> > const&) const src/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc:1335
    #6 0x15223a5f35b7 in PrimaryVertexProducer::produce(edm::Event&, edm::EventSetup const&) src/RecoVertex/PrimaryVertexProducer/plugins/PrimaryVertexProducer.cc:264
    #7 0x15240e15491e in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:82
```

The culprit appears to be here
https://github.com/cms-sw/cmssw/blob/402aaa8d730b384a986e3156044f22245d7ab229/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZT_vect.cc#L265

Where `extractRaw()` just assumes that `addItem` has been called. If no items have been added to the object, one gets the invalid reads.

A solution would be to only call `extractRaw()` if an item was added. Else a check could be added to `extractRaw()` to only do work if and only if the contains being used are not empty.

**Comment by Dr15Jones** [comment]
assign RecoVertex/PrimaryVertexProducer

**Comment by makortel** [comment]
FYI @cms-sw/tracking-pog-l2

**Comment by antoniovilela** [comment]
#44281 is merged

**Comment by makortel** [comment]
@cmsbuild, please close
