### ISSUE TITLE
No module named 'Configuration.StandardSequences.ReconstructionHeavyIons_cff'

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44326]
In CMSSW_14_1_X_2024-03-05-2300, unit test `TestConfigDP_4` fails with the following error:

```
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/test/RunExpressProcessing.py", line 97, in __call__
    process = scenario.expressProcessing(self.globalTag, **kwds)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/python/Impl/HeavyIons.py", line 88, in expressProcessing
    process = Reco.expressProcessing(self,globalTag, **args)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/python/Reco.py", line 146, in expressProcessing
    cb.prepare()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 2288, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 826, in addStandardSequences
    getattr(self,"prepare_"+stepName)(stepSpec = getattr(self,stepName+"DefaultSeq"))
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1745, in prepare_RECO
    _,_recoSeq,_ = self.loadDefaultOrSpecifiedCFF(stepSpec,self.RECODefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1277, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(_cff)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 354, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/FWCore/ParameterSet/python/Config.py", line 761, in load
    module = __import__(moduleName)
ModuleNotFoundError: No module named 'Configuration.StandardSequences.ReconstructionHeavyIons_cff'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/test/RunExpressProcessing.py", line 196, in <module>
    expressinator()
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/test/RunExpressProcessing.py", line 105, in __call__
    raise RuntimeError(msg)
RuntimeError: Error creating Express Processing config:
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/test/RunExpressProcessing.py", line 97, in __call__
    process = scenario.expressProcessing(self.globalTag, **kwds)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/python/Impl/HeavyIons.py", line 88, in expressProcessing
    process = Reco.expressProcessing(self,globalTag, **args)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/DataProcessing/python/Reco.py", line 146, in expressProcessing
    cb.prepare()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 2288, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 826, in addStandardSequences
    getattr(self,"prepare_"+stepName)(stepSpec = getattr(self,stepName+"DefaultSeq"))
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1745, in prepare_RECO
    _,_recoSeq,_ = self.loadDefaultOrSpecifiedCFF(stepSpec,self.RECODefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 1277, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(_cff)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 354, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-05-2300/src/FWCore/ParameterSet/python/Config.py", line 761, in load
    module = __import__(moduleName)
ModuleNotFoundError: No module named 'Configuration.StandardSequences.ReconstructionHeavyIons_cff'
```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-03-05-2300/unitTestLogs/Configuration/DataProcessing#/696-696)

The file was removed in [#43824](https://github.com/cms-sw/cmssw/pull/43824/files#diff-842b491c480b74a9c3d91a99023c39001757069bcd24073c117cf8d4004fedb2). Should the failing test be dropped as well?

**Comment by iarspider** [comment]
assign Configuration/DataProcessing

**Comment by fabiocos** [comment]
This issue seems a direct consequence of the integration of https://github.com/cms-sw/cmssw/pull/43824 , where the master HI reco configuration is removed, but DataProcessing has not been adapted accordingly

**Comment by mmusich** [comment]
looks like there's a lot of other places that need clean-up https://github.com/search?q=repo%3Acms-sw%2Fcmssw+ReconstructionHeavyIons_cff&type=code&p=1 (I suppose all these files could be removed as they are untested).

**Comment by mandrenguyen** [comment]
@iarspider @fabiocos Yes, the corresponding unit tests should be dropped as well.

**Comment by mandrenguyen** [comment]
assign reconstruction

**Comment by antoniovilela** [comment]
@cms-sw/reconstruction-l2 

Once the PR is in place, please mark it as urgent, since we will wait for it for building the pre-release.

**Comment by mandrenguyen** [comment]
> @cms-sw/reconstruction-l2
> 
> Once the PR is in place, please mark it as urgent, since we will wait for it for building the pre-release.

Ok, that's done:  https://github.com/cms-sw/cmssw/pull/44329

**Comment by antoniovilela** [comment]
In the end the pre-release was cut without the fix; let's keep it urgent so that it is fixed in the IBs as soon as possible.

**Comment by mandrenguyen** [comment]
+1
AFAIK this issue was addressed by https://github.com/cms-sw/cmssw/pull/44329
