### ISSUE TITLE
RelVal 2500.323: no function nanoL1TrigObjCustomizeFull

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44666]
RelVal 2500.323 is failing for all architectures:
```
RAW2DIGI,NANO:@L1DPG
entry filelist:step1_dasquery.log
found files:  ['/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/0379ef86-1d73-40df-a3fa-3e54fb417c09.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/05cfbe6c-a71a-48ae-8dc6-40602264c1a6.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/1267a7b7-9dfe-4fa0-bf63-2f458d7ab1b5.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/27ef73a6-d9ea-4754-9e91-77ed117f77c8.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/2f01b210-602f-46d4-b9ce-342853fa3dad.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/32e81a13-2594-4d5c-b832-32be2ead80f3.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/487a94a9-27fb-4491-94be-ec11f8368add.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/5488d417-6bb2-416e-9175-41ddeefbb78f.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/5b78169a-9e8e-4d25-aa8d-b7e99ffcd2c1.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/609b45ef-72ea-45ef-9cb1-eb8a0271e7af.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/6d0ad559-88a7-49ee-a295-a0f147167837.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/6f8c6cd8-ecfb-4f91-bf25-ffb7e9f0dfac.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/7051b507-9dbe-40de-b7f3-a61f3987fd6f.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/73ac48c6-9214-46d5-9fc9-39a41817a544.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/7ba6c816-fe32-432e-abc8-8a000401f98a.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/8116c80a-9a83-4083-9a09-b62655857d29.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/8854d98a-02b1-42b8-b5dc-9319d9c0c4d0.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/959ccbda-a883-40cf-93d4-47864823d438.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/a12ba961-1c37-44f3-b0c9-53ec11cd6265.root', '/store/data/Run2023D/Muon0/RAW-RECO/ZMu-PromptReco-v2/000/370/775/00000/a585f608-b64b-4a32-8609-46148429fb48.root']
Step: RAW2DIGI Spec: 
Step: NANO Spec: ['@L1DPG']
in prepare_nano @L1DPG
@L1DPG
NANO: scheduling: l1tNanoSequence from DPGAnalysis/L1TNanoAOD/l1tNano_cff
customising the process with addMonitoring from Configuration/DataProcessing/Utils
customising the process with customiseWithTimeMemorySummary from Validation/Performance/TimeMemorySummary
customising the process with nanoL1TrigObjCustomizeFull from PhysicsTools/NanoAOD/nano_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02832/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-08-2300/bin/el9_amd64_gcc12/cmsDriver.py", line 40, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02832/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-08-2300/bin/el9_amd64_gcc12/cmsDriver.py", line 16, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02832/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-08-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 2459, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02832/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-08-2300/src/Configuration/Applications/python/ConfigBuilder.py", line 952, in addCustomise
    raise Exception("config "+f+" has no function "+fcn)
Exception: config PhysicsTools/NanoAOD/nano_cff has no function nanoL1TrigObjCustomizeFull
```

Probably caused by https://github.com/cms-sw/cmssw/pull/43957

**Comment by iarspider** [comment]
assign xpog

**Comment by Senphy** [comment]
Also related to #44391 , where the `nanoL1TrigObjCustomizeFull` is moved from `nano_cff` to `l1trig_cff`. A simple solution may be changing [this line](https://github.com/cms-sw/cmssw/blob/CMSSW_14_1_X/PhysicsTools/NanoAOD/python/autoNANO.py#L37) for the correct declaration
