### ISSUE TITLE
RelVal 136.9: config TauAnalysis/MCEmbeddingTools/customisers has no function customiseGenerator

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44896]
Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-05-02-1100/pyRelValMatrixLogs/run/136.9_RunDoubleMuon2016C/step4_RunDoubleMuon2016C.log#/)

```
customising the process with customiseGenerator from TauAnalysis/MCEmbeddingTools/customisers
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02835/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-01-2300/bin/el8_amd64_gcc12/cmsDriver.py", line 40, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02835/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-01-2300/bin/el8_amd64_gcc12/cmsDriver.py", line 16, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02835/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-02-1100/src/Configuration/Applications/python/ConfigBuilder.py", line 2459, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02835/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-02-1100/src/Configuration/Applications/python/ConfigBuilder.py", line 952, in addCustomise
    raise Exception("config "+f+" has no function "+fcn)
Exception: config TauAnalysis/MCEmbeddingTools/customisers has no function customiseGenerator
````

Probably caused by #43871

**Comment by iarspider** [comment]
assign reconstruction, simulation
FYI @winterchristian

**Comment by iarspider** [comment]
type tau

**Comment by jfernan2** [comment]
This PR tries to amend this issue: https://github.com/cms-sw/cmssw/pull/44928

**Comment by civanch** [comment]
+1

**Comment by iarspider** [comment]
@cmsbuild please close
