### ISSUE TITLE
Few configuration fragments don't compile 

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#45106]
The following script shows that few cfi fragments are broken in `CMSSW_14_1_X_2024-05-29-2300`:

```bash
#!/bin/bash

# Array of module paths
modules=(
    "DQM.EcalMonitorDbModule.EcalCondDBWriter_cfi"
    "Geometry.ForwardCommonData.hfnoseV15ParametersInitialization_cfi"
    "Geometry.HcalEventSetup.HcalTrigTowerGeometry_cfi"
    "JetMETCorrections.TauJet.TCRecoTauDiscriminationAlgoComponent_cfi"
    "RecoMET.METPUSubtraction.mvaPFMET_leptons_cfi"
    "RecoTauTag.RecoTau.PFRecoTauProducer_cfi"
    "RecoTracker.MkFit.mkFitHitConverter_cfi"
    "L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0.0_cfi"
    "DQM.SiStripMonitorClient.SiStripDQMRecoConfigOfflineGlobalRunCAF_cfi"
    "RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi"
    "SimGeneral.MixingModule.mix_2015_25nsLowPU_matchData_PoissonOOTPU_cfi"
)

# Loop over the array and execute the python commands
for module in "${modules[@]}"; do
    echo "****************************************************************"
    python3 -m "$module"
done
echo "****************************************************************"
```

gives:

```console
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/EcalMonitorDbModule/python/EcalCondDBWriter_cfi.py", line 11, in <module>
    from DQM.EcalMonitorTasks.PNDiodeTask_cfi import ecalPnDiodeTask
ImportError: cannot import name 'ecalPnDiodeTask' from 'DQM.EcalMonitorTasks.PNDiodeTask_cfi' (/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/EcalMonitorTasks/python/PNDiodeTask_cfi.py)
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/Geometry/ForwardCommonData/python/hfnoseV15ParametersInitialization_cfi.py", line 3, in <module>
    from Geometry.HGCalCommonData.hgcalEEV15ParametersInitialization_cfi import *
ModuleNotFoundError: No module named 'Geometry.HGCalCommonData.hgcalEEV15ParametersInitialization_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/Geometry/HcalEventSetup/python/HcalTrigTowerGeometry_cfi.py", line 3, in <module>
    import Geometry.HcalEventSetup.hcalTrigTowerGeometry_cfi
ModuleNotFoundError: No module named 'Geometry.HcalEventSetup.hcalTrigTowerGeometry_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/JetMETCorrections/TauJet/python/TCRecoTauDiscriminationAlgoComponent_cfi.py", line 3, in <module>
    from RecoTauTag.RecoTau.TCTauAlgoParameters_cfi import *
ModuleNotFoundError: No module named 'RecoTauTag.RecoTau.TCTauAlgoParameters_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoMET/METPUSubtraction/python/mvaPFMET_leptons_cfi.py", line 66, in <module>
    from RecoTauTag.Configuration.HPSPFTaus_cff import hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits
ImportError: cannot import name 'hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits' from 'RecoTauTag.Configuration.HPSPFTaus_cff' (/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTauTag/Configuration/python/HPSPFTaus_cff.py)
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTauTag/RecoTau/python/PFRecoTauProducer_cfi.py", line 1, in <module>
    from RecoTauTag.RecoTau.pfRecoTauProducerDef_cfi import pfRecoTauProducerDef
ModuleNotFoundError: No module named 'RecoTauTag.RecoTau.pfRecoTauProducerDef_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTracker/MkFit/python/mkFitHitConverter_cfi.py", line 3, in <module>
    from RecoTracker.MkFit.mkFitHitConverterDefault_cfi import mkFitHitConverterDefault as _mkFitHitConverterDefault
ModuleNotFoundError: No module named 'RecoTracker.MkFit.mkFitHitConverterDefault_cfi'
****************************************************************
/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/external/el9_amd64_gcc12/bin/python3: Error while finding module specification for 'L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0.0_cfi' (ModuleNotFoundError: No module named 'L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0')
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/SiStripMonitorClient/python/SiStripDQMRecoConfigOfflineGlobalRunCAF_cfi.py", line 5, in <module>
    from DQM.SiStripMonitorClient.RecoForDQM_Cosmic_cff import *
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/SiStripMonitorClient/python/RecoForDQM_Cosmic_cff.py", line 11, in <module>
    siPixelDigis.InputLabel = 'source'
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 324, in __setattr__
    self.__addParameter(name, value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 290, in __addParameter
    raise TypeError(name+" does not already exist, so it can only be set to a cms.EDProducer or cms.EDAlias")
TypeError: InputLabel does not already exist, so it can only be set to a cms.EDProducer or cms.EDAlias
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoParticleFlow/PFProducer/python/pfGsfElectronCiCSelector_cfi.py", line 57, in <module>
    electronsCiCLoose = cms.EDFilter("EleIdCutBased",
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 173, in __init__
    super(EDFilter,self).__init__(type_,*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 137, in __init__
    super(_Module,self).__init__(type_,*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 397, in __init__
    super(_TypedParameterizable,self).__init__(*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 186, in __init__
    self.__setParameters(kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 268, in __setParameters
    self.__addParameter(name, value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 252, in __addParameter
    self.__raiseBadSetAttr(name)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 307, in __raiseBadSetAttr
    raise TypeError(name+" does not already exist, so it can only be set to a CMS python configuration type")
TypeError: electronIDType does not already exist, so it can only be set to a CMS python configuration type
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/SimGeneral/MixingModule/python/mix_2015_25nsLowPU_matchData_PoissonOOTPU_cfi.py", line 6, in <module>
    mix.input.nbPileupEvents.probFunctionVariable = cms.vint32(0,1,2,3,4,5,6,7,8,9,10,11,12),
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 291, in __setattr__
    self.__dict__[name].setValue(value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 656, in setValue
    self.extend(v)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 624, in extend
    raise TypeError("wrong type being extended to container "+self._labelIfAny())
TypeError: wrong type being extended to container vint32
****************************************************************
```

spotted from confDB parsing logs.

**Comment by Dr15Jones** [comment]
related to #45100

**Comment by makortel** [comment]
assign DQM/EcalMonitorDbModule,Geometry/ForwardCommonData,Geometry/HcalEventSetup,JetMETCorrections/TauJet,RecoMET/METPUSubtraction,RecoTauTag/RecoTau,RecoTracker/MkFit,L1Trigger/L1TCalorimeter,DQM/SiStripMonitorClient,RecoParticleFlow/PFProducer,SimGeneral/MixingModule

**Comment by makortel** [comment]
assign package DQM/EcalMonitorDbModule,Geometry/ForwardCommonData,Geometry/HcalEventSetup,JetMETCorrections/TauJet,RecoMET/METPUSubtraction,RecoTauTag/RecoTau,RecoTracker/MkFit,L1Trigger/L1TCalorimeter,DQM/SiStripMonitorClient,RecoParticleFlow/PFProducer,SimGeneral/MixingModule

**Comment by makortel** [comment]
assign package DQM/EcalMonitorDbModule

**Comment by makortel** [comment]
assign from DQM/EcalMonitorDbModule

**Comment by makortel** [comment]
assign DQM/EcalMonitorDbModule

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
@smuzaffar Either I'm doing something wrong, or the bot is not reacting :)

**Comment by iarspider** [comment]
@makortel yes, the bot is failing. Looking into it.

**Comment by slava77** [comment]
type tracking

For mkfit I think the origin is older; the file RecoTracker/MkFit/python/mkFitHitConverter_cfi.py is not used and can be removed.

@mmusich where do you need the fix?

**Comment by mmusich** [comment]
> where do you need the fix?

@slava77 master-only is fine. It's not a showstopper, just an annoyance as it shows as an error during the parsing. Thanks for the fix at https://github.com/cms-sw/cmssw/pull/45109

**Comment by jfernan2** [comment]
type tau

**Comment by jfernan2** [comment]
@mbluj @Ksavva1021 as Tau Reco Contacts, can you please take care of the "RecoTauTag.RecoTau.PFRecoTauProducer_cfi" ?

**Comment by jfernan2** [comment]
type jetmet

**Comment by jfernan2** [comment]
@laurenhay @michaelwassmer as JetMET Reco contacts, can you please take care of "JetMETCorrections.TauJet.TCRecoTauDiscriminationAlgoComponent_cfi"
"RecoMET.METPUSubtraction.mvaPFMET_leptons_cfi"
?

**Comment by jfernan2** [comment]
type pf

**Comment by jfernan2** [comment]
@stahlleiton as PF reco contact, can you please take care of
"RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi" ?

**Comment by stahlleiton** [comment]
> @stahlleiton as PF reco contact, can you please take care of "RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi" ?

Should be fixed in https://github.com/cms-sw/cmssw/pull/45184

**Comment by jfernan2** [comment]
ping @laurenhay @michaelwassmer

**Comment by jfernan2** [comment]
ping @mbluj @Ksavva1021

**Comment by mmusich** [comment]
the rest of them is taken care of by https://github.com/cms-sw/cmssw/issues/45106

**Comment by jfernan2** [comment]
+1

**Comment by tvami** [comment]
+1
  * resolved in https://github.com/cms-sw/cmssw/pull/45217
