### ISSUE TITLE
testSiStripPayloadInspector: SIGSEGV in SiStripTkMaps::drawMap

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#45952]
Since CMSSW_14_2_X_2024-09-06-1100, the testSiStripPayloadInspector unit test is failing with SIGSEGV in SiStripTkMaps::drawMap: 

```
*** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000014e72121ee0b in waitpid () from /lib64/libc.so.6
#1  0x000014e721172747 in do_system () from /lib64/libc.so.6
#2  0x000014e72540ef3d in TUnixSystem::StackTrace() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/external/el8_amd64_gcc12/lib/libCore.so
#3  0x000014e72540ca14 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/external/el8_amd64_gcc12/lib/libCore.so
#4  <signal handler called>
#5  0x000014e72b214631 in SiStripTkMaps::drawMap(TCanvas&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libDQMTrackerRemapper.so
#6  0x000000000049f306 in (anonymous namespace)::SiStripBadStripFractionTH2PolyTkMap::fill() [clone .lto_priv.0] ()
#7  0x000000000045aea5 in cond::payloadInspector::PlotImpl<(cond::payloadInspector::IOVMultiplicity)2, 0>::processData[abi:cxx11]() ()
#8  0x000014e72bd17c97 in cond::payloadInspector::PlotBase::exec_process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, unsigned long long>, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, unsigned long long> > > const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libCondCoreUtilities.so
#9  0x000014e72bd1818b in cond::payloadInspector::PlotBase::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pybind11::list const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libCondCoreUtilities.so
#10 0x000000000044d1c3 in main ()
===========================================================


The lines below might hint at the cause of the crash. If you see question
marks as part of the stack trace, try to recompile with debugging information
enabled and export CLING_DEBUG=1 environment variable before running.
You may get help by asking at the ROOT forum https://root.cern/forum
preferably using the command (.forum bug) in the ROOT prompt.
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs or (preferably) using the command (.gh bug) in
the ROOT prompt. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x000014e72b214631 in SiStripTkMaps::drawMap(TCanvas&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libDQMTrackerRemapper.so
#6  0x000000000049f306 in (anonymous namespace)::SiStripBadStripFractionTH2PolyTkMap::fill() [clone .lto_priv.0] ()
#7  0x000000000045aea5 in cond::payloadInspector::PlotImpl<(cond::payloadInspector::IOVMultiplicity)2, 0>::processData[abi:cxx11]() ()
#8  0x000014e72bd17c97 in cond::payloadInspector::PlotBase::exec_process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, unsigned long long>, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, unsigned long long> > > const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libCondCoreUtilities.so
#9  0x000014e72bd1818b in cond::payloadInspector::PlotBase::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pybind11::list const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-09-08-0000/lib/el8_amd64_gcc12/libCondCoreUtilities.so
#10 0x000000000044d1c3 in main ()
===========================================================
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_X_2024-09-08-0000/unitTestLogs/CondCore/SiStripPlugins#/76)

**Comment by iarspider** [comment]
assign dqm

**Comment by smuzaffar** [comment]
this was due to https://github.com/cms-sw/cmssw/pull/45795
