### ISSUE TITLE
hlt-p2-timing job failing for 14.1.X and 14.2.X IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46178]
https://cmssdt.cern.ch/jenkins/job/ib-run-hlt-p2-timing/ jenkins job which runs the hlt-p2-timing test is failing for both 14.1.X and 14.2.X since 25th Sep [a]. 
@rovere , can you please look in to it?

[a]
```
Cloning into 'patatrack-scripts'...
2 CPUs:
  0: AMD EPYC 7763 64-Core Processor (64 cores, 128 threads)
  1: AMD EPYC 7763 64-Core Processor (64 cores, 128 threads)

2 visible NVIDIA GPUs:
  0: Tesla T4
  1: Tesla T4

Benchmarking Phase2_L1P2GT_HLT.py
Warming up

Running 3 times over 1000 events with 4 jobs, each with 16 threads, 16 streams, and 1 GPUs
Traceback (most recent call last):
  File "/data/cmsbuild/workspace/ib-run-hlt-p2-timing/CMSSW_14_2_X_2024-09-25-1100/src/HLTrigger/Configuration/python/HLT_75e33/test/patatrack-scripts/benchmark", line 84, in <module>
    multiCmsRun(process, **options)
  File "/data/cmsbuild/workspace/ib-run-hlt-p2-timing/CMSSW_14_2_X_2024-09-25-1100/src/HLTrigger/Configuration/python/HLT_75e33/test/patatrack-scripts/multirun.py", line 507, in multiCmsRun
    overlap_fits[job] = stats.linregress(t, e)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02856/el8_amd64_gcc12/external/py3-scipy/1.10.0-635406fc44c855747cd0eff7770547c1/lib/python3.9/site-packages/scipy/stats/_stats_mstats_common.py", line 154, in linregress
    raise ValueError("Inputs must not be empty.")
ValueError: Inputs must not be empty.
```

**Comment by smuzaffar** [comment]
As this test start failing for both 14.1.X and 14.2.X so I guess latest changes in https://github.com/cms-patatrack/patatrack-scripts/commits/master/ might be the reason for this failure

**Comment by rovere** [comment]
See https://github.com/cms-sw/cmssw/pull/46185

**Comment by mmusich** [comment]
assign hlt

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/46185 has fixed this for 14.2.X.

**Comment by mmusich** [comment]
proposed solutions:
   *  https://github.com/cms-sw/cmssw/pull/46185 (master, `CMSSW_14_2_X`)
   * https://github.com/cms-sw/cmssw/pull/46193 (backport to `CMSSW_14_1_X`)

**Comment by mmusich** [comment]
+hlt
  * see https://github.com/cms-sw/cmssw/issues/46178#issuecomment-2388681581
  * functionality restored as of `CMSSW_14_2_X_2024-10-02-2300` and `CMSSW_14_1_X_2024-10-02-2300`
