### ISSUE TITLE
test_G2GainsValidator test failing in IB

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46177]
`test_G2GainsValidator` unit test start failing since Friday 27th. I think this is due to [cmsweb update](https://cms-talk.web.cern.ch/t/switching-cmsweb-frontends-to-aps-friday-2-30-p-m-27th-september/50460) . @cms-sw/db-l2 can you please look in to it? May be we need https://github.com/cms-sw/cmssw/pull/45767 now?

**Comment by perrotta** [comment]
https://github.com/cms-sw/cmssw/pull/45867 was intended to be a fix for it. But apparently the `cert_path` is not retrieved in https://github.com/cms-sw/cmssw/blob/master/CondCore/SiStripPlugins/scripts/G2GainsValidator.py#L37 :
```
===== Test "test_G2GainsValidator" ====
No certificate, nor proxy provided for Tier0 access
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_2_X_2024-09-30-2300/src/CondCore/SiStripPlugins/scripts/G2GainsValidator.py", line 157, in <module>
    FCSR = getFCSR(proxy=options.proxy, certs=certs)
  File "/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_14_2_X_2024-09-30-2300/src/CondCore/SiStripPlugins/scripts/G2GainsValidator.py", line 77, in getFCSR
    response = json.loads(out)["result"][0]
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02857/el8_amd64_gcc12/external/python3/3.9.14-c10287ae9cadff55334e60003302c349/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02857/el8_amd64_gcc12/external/python3/3.9.14-c10287ae9cadff55334e60003302c349/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02857/el8_amd64_gcc12/external/python3/3.9.14-c10287ae9cadff55334e60003302c349/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Failure running G2GainsValidator.py: status 1

---> test test_G2GainsValidator had ERRORS
```
@JanChyczynski @PonIlya @mmusich do you have any idea why?

**Comment by mmusich** [comment]
I thought https://github.com/cms-sw/cmssw/pull/45867 already addressed the issue.
Does the bot set `X509_USER_CERT` and `X509_USER_KEY` ?

**Comment by smuzaffar** [comment]
> I thought #45867 already addressed the issue. Does the bot set `X509_USER_CERT` and `X509_USER_KEY` ?

No, these variables are not set . I have opened https://github.com/cms-sw/cms-bot/pull/2345 to set these env variable

**Comment by smuzaffar** [comment]
cms-sw/cms-bot#2345 did not work. I have opened https://github.com/cms-sw/cmssw/pull/46179 which uses the `--user-mode` option so that `G2GainsValidator.py` can make use of `~/.globus/user*.pem` files
