### ISSUE TITLE
[UBSAN][DQM] shift exponent too large for 32-bit type int

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46483]
There are few UBSAN errors about shift exponent too large for 32-bit type int [a]. Normally this indicates that there might be some logical error. @cms-sw/dqm-l2 , can you please check the code and see if we can avoid this errors. 

One way to fix/avoid these errors is to use `1 << (variable&0x1F)` instead of `1 << variable` but I am not sure how portable this code will be.

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_14_2_X_2024-10-20-2300/
27 [DQM/GEM/plugins/GEMDAQStatusSource.cc:487](https://github.com/cms-sw/cmssw/blob/master/DQM/GEM/plugins/GEMDAQStatusSource.cc#L487):28: runtime error: shift exponent 32 is too large for 32-bit type 'int'
27 [DQM/GEM/plugins/GEMDAQStatusSource.cc:559](https://github.com/cms-sw/cmssw/blob/master/DQM/GEM/plugins/GEMDAQStatusSource.cc#L559):58: runtime error: shift exponent 39 is too large for 32-bit type 'int'
27 [DQM/GEM/plugins/GEMDAQStatusSource.cc:560](https://github.com/cms-sw/cmssw/blob/master/DQM/GEM/plugins/GEMDAQStatusSource.cc#L560]:50: runtime error: shift exponent 39 is too large for 32-bit type 'int'

**Comment by smuzaffar** [comment]
assign dqm

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 , we still have these runtime errors https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_15_1_X_2025-04-11-2300/ . Can you please look in to it ?

**Comment by akritkbehera** [comment]
The runtime errors reappeared again on `CMSSW_15_1_UBSAN_X_2025-08-04-2300`
```BASH
05-Aug-2025 17:01:11 CEST  Initiating request to open file file:step2.root
05-Aug-2025 17:02:10 CEST  Successfully opened file file:step2.root
Begin processing the 1st record. Run 1, Event 315, LumiSection 315 on stream 2 at 05-Aug-2025 17:04:31.828 CEST
src/DQM/GEM/plugins/GEMDAQStatusSource.cc:496:28: runtime error: shift exponent 32 is too large for 32-bit type 'int'
    #0 0x149040ad2359 in GEMDAQStatusSource::analyze(edm::Event const&, edm::EventSetup const&) src/DQM/GEM/plugins/GEMDAQStatusSource.cc:496
    #1 0x1491a50b440f in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:83
    #2 0x1491a4f03428 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:204
    #3 0x1491a45a20cc in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) src/FWCore/Framework/interface/maker/Worker.h:606
    #4 0x1491a45a20cc in edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}::operator()() const src/FWCore/Framework/interface/maker/Worker.h:1183
    #5 0x1491a45a20cc in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) src/FWCore/Utilities/interface/ConvertException.h:21
    #6 0x1491a45a2ae6 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1182
    #7 0x1491a45a2ae6 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1096
    #8 0x1491a45c97b4 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() src/FWCore/Framework/interface/maker/Worker.h:460
    #9 0x1491a1db60aa in operator() src/FWCore/Concurrency/src/WaitingTaskList.cc:206
    #10 0x1491a1db60aa in task_ptr_or_nullptr_impl<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:114
    #11 0x1491a1db60aa in task_ptr_or_nullptr<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:124
    #12 0x1491a1db60aa in execute /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:89
    #13 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:334
    #14 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:470
    #15 0x1491a1d24609 in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/arena.cpp:215
    #16 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher_client::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher_client.h:41
    #17 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher::process(rml::job&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher.cpp:195
    #18 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:271
    #19 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:221
    #20 0x14919abe81c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #21 0x14919d6628d2 in clone (/lib64/libc.so.6+0x398d2)

src/DQM/GEM/plugins/GEMDAQStatusSource.cc:568:58: runtime error: shift exponent 37 is too large for 32-bit type 'int'
    #0 0x149040ad2562 in GEMDAQStatusSource::analyze(edm::Event const&, edm::EventSetup const&) src/DQM/GEM/plugins/GEMDAQStatusSource.cc:568
    #1 0x1491a50b440f in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:83
    #2 0x1491a4f03428 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:204
    #3 0x1491a45a20cc in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) src/FWCore/Framework/interface/maker/Worker.h:606
    #4 0x1491a45a20cc in edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}::operator()() const src/FWCore/Framework/interface/maker/Worker.h:1183
    #5 0x1491a45a20cc in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) src/FWCore/Utilities/interface/ConvertException.h:21
    #6 0x1491a45a2ae6 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1182
    #7 0x1491a45a2ae6 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1096
    #8 0x1491a45c97b4 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() src/FWCore/Framework/interface/maker/Worker.h:460
    #9 0x1491a1db60aa in operator() src/FWCore/Concurrency/src/WaitingTaskList.cc:206
    #10 0x1491a1db60aa in task_ptr_or_nullptr_impl<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:114
    #11 0x1491a1db60aa in task_ptr_or_nullptr<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:124
    #12 0x1491a1db60aa in execute /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:89
    #13 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:334
    #14 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:470
    #15 0x1491a1d24609 in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/arena.cpp:215
    #16 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher_client::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher_client.h:41
    #17 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher::process(rml::job&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher.cpp:195
    #18 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:271
    #19 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:221
    #20 0x14919abe81c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #21 0x14919d6628d2 in clone (/lib64/libc.so.6+0x398d2)

src/DQM/GEM/plugins/GEMDAQStatusSource.cc:569:50: runtime error: shift exponent 37 is too large for 32-bit type 'int'
    #0 0x149040ad25b2 in GEMDAQStatusSource::analyze(edm::Event const&, edm::EventSetup const&) src/DQM/GEM/plugins/GEMDAQStatusSource.cc:569
    #1 0x1491a50b440f in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:83
    #2 0x1491a4f03428 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:204
    #3 0x1491a45a20cc in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) src/FWCore/Framework/interface/maker/Worker.h:606
    #4 0x1491a45a20cc in edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}::operator()() const src/FWCore/Framework/interface/maker/Worker.h:1183
    #5 0x1491a45a20cc in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) src/FWCore/Utilities/interface/ConvertException.h:21
    #6 0x1491a45a2ae6 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1182
    #7 0x1491a45a2ae6 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1096
    #8 0x1491a45c97b4 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() src/FWCore/Framework/interface/maker/Worker.h:460
    #9 0x1491a1db60aa in operator() src/FWCore/Concurrency/src/WaitingTaskList.cc:206
    #10 0x1491a1db60aa in task_ptr_or_nullptr_impl<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:114
    #11 0x1491a1db60aa in task_ptr_or_nullptr<const edm::WaitingTaskList::announce()::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:124
    #12 0x1491a1db60aa in execute /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/include/oneapi/tbb/task_group.h:89
    #13 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:334
    #14 0x1491a1d24609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:470
    #15 0x1491a1d24609 in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/arena.cpp:215
    #16 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher_client::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher_client.h:41
    #17 0x1491a1d24609 in tbb::detail::r1::thread_dispatcher::process(rml::job&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher.cpp:195
    #18 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:271
    #19 0x1491a1d1c6b7 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:221
    #20 0x14919abe81c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #21 0x14919d6628d2 in clone (/lib64/libc.so.6+0x398d2)
```
[Full Logs: RelVal 29751.85](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_1_UBSAN_X_2025-08-04-2300/pyRelValMatrixLogs/run/29751.85_HydjetQMinBias_5519GeV+Run4D110_hi/step3_HydjetQMinBias_5519GeV+Run4D110_hi.log#/)

**Comment by smuzaffar** [comment]
Debuging this a bit more I noticed that at 

https://github.com/cms-sw/cmssw/blob/7bfa23241b8ee9ebdc524ca61fdbf774de721f6b/DQM/GEM/plugins/GEMDAQStatusSource.cc#L481

`stationInfo.nMaxVFAT_` is sometimes `96` and `stationInfo.nNumModules_` is `1`  causing ` nNumVFATPerModule=96` and then loop 

https://github.com/cms-sw/cmssw/blob/7bfa23241b8ee9ebdc524ca61fdbf774de721f6b/DQM/GEM/plugins/GEMDAQStatusSource.cc#L495-L500

does `96` iterations causing UBSAN to generate a runtime error for `i=32` ( and ignore rest of the errors for `i>32`). Note that   vfatMask is 32 bits so if `vfatMask & (1 << i)) == 0` is true for `i==1` then it will be true for `i==33` and `i==65` etc. 

I think there might be a bug in in the value of `nMaxVFAT_` e.g. in the code below

https://github.com/cms-sw/cmssw/blob/7bfa23241b8ee9ebdc524ca61fdbf774de721f6b/DQM/GEM/src/GEMDQMBase.cc#L77-L119

we create an object of `MEStationInfo` by passing it `num_vfat` ( which is `num_etas * max_vfat`) instead of `max_vfat`

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 , can you please look in to this issue?

**Comment by smuzaffar** [comment]
same kind of runtime errors occurs from following code for `nIdxVFAT>=32`

https://github.com/cms-sw/cmssw/blob/7bfa23241b8ee9ebdc524ca61fdbf774de721f6b/DQM/GEM/plugins/GEMDAQStatusSource.cc#L565-L569

**Comment by gabrielmscampos** [comment]
Hi @smuzaffar, sure I can take a look. How urgent is this? I have other PPD tasks to tackle, so depending on its priority I might have a look now or in 2-3 weeks.

**Comment by smuzaffar** [comment]
@gabrielmscampos , this issue is there since 2024. I really do not know if it is a real bug or not ( e.g. should we be creating `MEStationInfo` with `num_vfat` or `max_vfat`? ). If it is a real bug then we should fix it as soon as possible.

**Comment by vlimant** [comment]
we can forward to the GEM experts ; is there such a label ?

**Comment by gabrielmscampos** [comment]
Tagging @cms-sw/gem-dpg-l2

**Comment by vlimant** [comment]
assign muon-dpg
