### ISSUE TITLE
[UBSAN][GEMDigi] shift exponent 3951 is too large for int

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46580]
UBSAN IBs report many runtime errors like [a]. The stack at the time of error is [b].  The call is triggered from https://github.com/cms-sw/cmssw/blob/master/EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc#L204 which was add in https://github.com/cms-sw/cmssw/pull/38062 . Such errors normally shows that there might be some logical errors.

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_14_2_X_2024-10-30-2300/logs/a4/a46e3025fea17bb12e2d7f9cf63e862f/log
```
10007.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 3951 is too large for 32-bit type 'int'
10026.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 3615 is too large for 32-bit type 'int'
10224.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 2424 is too large for 32-bit type 'int'
10224.15/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 3944 is too large for 32-bit type 'int'
10225.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 1740 is too large for 32-bit type 'int'
10424.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 3944 is too large for 32-bit type 'int'
10809.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 1759 is too large for 32-bit type 'int'
10842.0/step2:DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 2651 is too large for 32-bit type 'int'
```

[b] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_UBSAN_X_2024-10-30-2300/pyRelValMatrixLogs/run/10007.0_SingleMuPt10+2017/step2_SingleMuPt10+2017.log#/41-41
```
src/DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151:38: runtime error: shift exponent 3951 is too large for 32-bit type 'int'
    #0 0x1536313b5e86 in GEMOptoHybrid::addVFAT(GEMVFAT) src/DataFormats/GEMDigi/interface/GEMOptoHybrid.h:151
    #1 0x1536313b5e86 in GEMDigiToRawModule::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const src/EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc:204
    #2 0x153715b6d0fd in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/global/EDProducerBase.cc:69
    #3 0x153715b1dd58 in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:202
    #4 0x15371515934f in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, 
```

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
FYI @yeckang

**Comment by smuzaffar** [comment]
@yeckang @cms-sw/reconstruction-l2 , has any more looked in to this issue?

**Comment by jfernan2** [comment]
Kind ping  @jshlee @watson-ij as GEM DPG Reco responsibles,

**Comment by watson-ij** [comment]
Hi @jfernan2 looking through the workflows that are triggering the ubsan, it looks like its 2017/18 (when we had the GE1/1 slice test only, and I think we were using a different chmap class?) and phase-2, which will use dummy emaps, so its not triggered in run3 where we have properly defined emaps. @yeckang could you comment on what would be filled in them, and if theres a fix for the dummy emaps to avoid this?

**Comment by kpedro88** [comment]
@yeckang this issue is still present in the latest IBs

**Comment by kpedro88** [comment]
assign gem-dpg
