### ISSUE TITLE
[UBSAN][Align]Runtime error where there is no globalDerivativesCalibration

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46726]
For UBSAN IBs, we see runtime errors like [a]. This happens when we call https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc#L793 with empty `theIntBuffer, theFloatBufferX, theFloatBufferY`. Error goes away if we set [ignoreHitsWithoutGlobalDerivatives](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeAlignmentAlgorithm_cfi.py#L27) to true. 

@cms-sw/alca-l2 , can you please look in to this? 

[a] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_UBSAN_X_2024-11-15-2300/pyRelValMatrixLogs/run/1001.0_RunMinBias2011A/step3_RunMinBias2011A.log#/100-100
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1124:34: runtime error: reference binding to null pointer of type 'value_type'

    #0 0x148ef8da42ec in std::vector<float, std::allocator<float> >::operator[](unsigned long) /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1124
    #1 0x148ef8da42ec in MillePedeAlignmentAlgorithm::callMille2D(ReferenceCountingPointer<ReferenceTrajectoryBase> const&, unsigned int, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&) src/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc:1466
    #2 0x148ef8da7e75 in MillePedeAlignmentAlgorithm::callMille(ReferenceCountingPointer<ReferenceTrajectoryBase> const&, unsigned int, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&) src/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc:1366
    #3 0x148ef8db3142 in MillePedeAlignmentAlgorithm::addMeasurementData(edm::EventSetup const&, AlignmentAlgorithmBase::EventInfo const&, ReferenceCountingPointer<ReferenceTrajectoryBase> const&, unsigned int, AlignmentParameters*&) src/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc:793
    #4 0x148ef8dcfc4a in MillePedeAlignmentAlgorithm::addReferenceTrajectory(edm::EventSetup const&, AlignmentAlgorithmBase::EventInfo const&, ReferenceCountingPointer<ReferenceTrajectoryBase> const&) src/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc:574

```

**Comment by smuzaffar** [comment]
assign alca

**Comment by smuzaffar** [comment]
Note the runtime error occurs when we try to get the address of first element of zero size vector [float *newGlobDerivsX = &(newGlobDerivs[0]);](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc#L1466)

**Comment by mmusich** [comment]
> (since you were the last one who interacted with that MillePedeAlignmentAlgorithm.cc file in github)

@perrotta please refer to Tracker DPG.

**Comment by perrotta** [comment]
@cms-sw/trk-dpg-l2 (repeating what [above](https://github.com/cms-sw/cmssw/issues/46726#issuecomment-2485187525)): is there any reason not to set [ignoreHitsWithoutGlobalDerivatives](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeAlignmentAlgorithm_cfi.py#L27) as true by default?
As correctly written at [L1393](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc#L1393) "&(localDerivatives[0]) etc. are valid - as long as vector is not empty" and it is wrong trying to enter those methods if theFloatBufferX.empty() at [L788](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc#L788)

**Comment by mmusich** [comment]
Just for the record, this mechanism was put into place in 2016 (!) in https://github.com/cms-sw/cmssw/pull/14961. 
Why it is visible only now?

**Comment by smuzaffar** [comment]
@mmusich , I think this error was always there but as it is not directly coming from cmssw code that is why it was never shown up in [ubsan errors summary page](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_15_0_X_2024-11-29-2300/).

**Comment by mmusich** [comment]
>  I think this error was always there but as it is not directly coming from cmssw code that is why it was never shown up 

What does it mean not coming from cmssw code?  
In any case judging from the content of PR https://github.com/cms-sw/cmssw/pull/14961 (and the old hypernews thread pointed therein) it does not look a good idea to just switch on [ignoreHitsWithoutGlobalDerivatives](https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeAlignmentAlgorithm_cfi.py#L27) as true by default, as it would probably make the output mille binaries produced in the tier0 too large to handle.

**Comment by smuzaffar** [comment]
the script looks for `:runtime error:` message and then check for the source file. In this case we have 
```
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1124:34: runtime error: reference binding to null pointer of type 'value_type'
```
so though the error is due to bug in cmssw but as it was reported via gcc header file that is why it was not reported in the ubsan errors summary page
